### ISSUE TITLE
cannot declare encoding

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#101]
I sometimes write scripts to run both inside & outside the DrawBot application.
Here’s a catch-22: I don’t have to worry about declaring the script’s encoding when working in DrawBot, but I have to do it when on the command line.

If I run a script with encoding declaration from DrawBot, I get the following traceback:
```
Traceback (most recent call last):
  File "<untitled>", line 0
SyntaxError: encoding declaration in Unicode string
```

And – of course – if I run a script with encoding declaration from the command line, I get the unavoidable
```
SyntaxError: Non-ASCII character '\xe2' in file xxxxx.py on line 73, but no encoding declared; …
```

**Comment by typemytype** [comment]
This should be fixed
