### ISSUE TITLE
Error when using ImageObject.perspectiveTransform() with attributes

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#107]
I’m sorry to bother you again so soon after my last question, but I would appreciate any quick tips you might have on using `ImageObject.perspectiveTransform()`. 

It works fine when I run the filter with no attributes, but if I try to use the attributes to customize the shape, it throws an error if I specify any other value for `topLeft`, `topRight`, `bottomLeft` or `bottomRight`.

```
im = ImageObject()
with im:
    size(500, 500)
    rect(0, 0, 500, 500)

im.perspectiveTransform(topLeft=2.0, topRight=0, bottomRight=0, bottomLeft=0)
image(im, (250, 250))
```

```
Traceback (most recent call last):
  File "<untitled>", line 7, in <module>
  File "drawBot/drawBotDrawingTools.pyc", line 1127, in image
  File "drawBot/context/tools/imageObject.pyc", line 143, in _nsImage
  File "drawBot/context/tools/imageObject.pyc", line 136, in _ciImage
  File "drawBot/context/tools/imageObject.pyc", line 201, in _applyFilters
ValueError: NSInvalidArgumentException - -[OC_PythonNumber X]: unrecognized selector sent to instance 0x600000801950
```

Running v3.88.

Thanks so much!

**Comment by djrrb** [comment]
Oh I forgot to mention: I get the same behavior with `perspectiveCorrection`

**Comment by typemytype** [comment]
oh, first they need to be tuples... and drawBot has to convert them to `CIVector` objects

this works but is not user friendly :(
```
import AppKit

im = ImageObject()

with im:
    size(500, 500)
    rect(0, 0, 500, 500)


im.perspectiveTransform(
        topLeft=AppKit.CIVector.vectorWithValues_count_((98, 624), 2), 
        topRight=AppKit.CIVector.vectorWithValues_count_((704, 687), 2), 
        bottomRight=AppKit.CIVector.vectorWithValues_count_((548, 140), 2), 
        bottomLeft=AppKit.CIVector.vectorWithValues_count_((155, 153), 2))

image(im, im.offset())
```

**Comment by typemytype** [comment]
also see https://developer.apple.com/library/content/documentation/GraphicsImaging/Reference/CoreImageFilterReference/#//apple_ref/doc/filter/ci/CIPerspectiveTransform

**Comment by typemytype** [comment]
this should fix it c9d6ec4276f0eca5ee869ba11c895c53cbe0b2b7

**Comment by djrrb** [comment]
You are the best. Thank you! 

I'm closing this issue, but FYI it might also be worth updating [the docs](http://www.drawbot.com/content/image/imageObject.html#drawBot.context.tools.imageObject.ImageObject.perspectiveCorrection) to say that these attributes should be tuples instead of floats

thanks again!

**Comment by typemytype** [comment]
done c2e2ef6071ff97ce7c8a52df0af1586b0dcee0a6

thanks
