### ISSUE TITLE
ImageObject creating empty page

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#110]
The following snippet creates one blank page, and a page containing the image. This didn't used to be the case. The first (empty) page should not be created.

```python
newPage(500, 500)  # or size(500, 500)

im = ImageObject()
with im:
    size(200, 200)
    rect(50, 50, 100, 100)

im.gaussianBlur(8)

image(im, (0, 0))
```

**Comment by typemytype** [comment]
this should do it: 03691c1a55d7626eb682fe9a4769b5eca56f912e

**Comment by justvanrossum** [comment]
It does, thanks!
