### ISSUE TITLE
Linear Gradient in SVG Context

### ISSUE THREAD

**Issue by MBurvill** [typemytype/drawbot#114]
I find that if I use linear gradient in an artwork and export JPG, PDF and SVG, the SVG isn't coloured in the same way as the JPG and PDF. 
The JPG is the same as the PDF so I think there is an issue with the SVG context.

I get the same colours in all formats if I am simply using fill(), so I assume there's an issue with the linear gradients.

The image is of the same artwork exported as JPG (left) and SVG (right). you can see they have the same elements at the same position, but the colouring is different.

I am calling linearGradient() in a loop once for each oval()

<img width="1125" alt="screen shot 2017-10-13 at 15 13 44" src="https://user-images.githubusercontent.com/12418488/31550423-3540fe5a-b029-11e7-9036-2915343a205d.png">

**Comment by justvanrossum** [comment]
Can you provide a small test script that shows the problem? Simpler/smaller is better.

**Comment by MBurvill** [comment]
Thanks you, 
This is a simple script that replicates the problem, just FYI running in latest version 3.89 (3.89)
[https://gist.github.com/MBurvill/f4f98b919ab3732094da238e7ea507cd](https://gist.github.com/MBurvill/f4f98b919ab3732094da238e7ea507cd)

**Comment by justvanrossum** [comment]
How do you view your SVG? If I view in Finder or with Safari (on 10.10) I see no difference.
<img width="885" alt="svg_screenshot" src="https://user-images.githubusercontent.com/4246121/31559641-9f674e6a-b051-11e7-8c91-38edea4fb424.png">

(AI CC 2014 doesn't read it correctly, but that's probably an unrelated problem.)

**Comment by MBurvill** [comment]
Ah you're right it works there. 
I'm viewing in Chrome (Version 61.0.3163.100) and also get the same bad result if I open with Firefox (56.0) or Affinity designer (1.5.5) for editing.

**Comment by justvanrossum** [comment]
Time for some SVG debugging I'm afraid :(

**Comment by typemytype** [comment]
it seems like some svg def got the same id
and that is ... euh ... not so good

**Comment by MBurvill** [comment]
I first started looking into it after getting this error; I wanted to be sure the issue was with the SVG and not with my code in a more complex script, but maybe it helps:

Line 121 is saveImage(...file.svg)
The script is attempting to save approx 6000 of those gradient-filled ovals with different colours in each one, perhaps that's unwise but maybe the error can help.

> Traceback (most recent call last):
>   File "myFile.py", line 121, in <module>
>   File "drawBot/drawBotDrawingTools.pyc", line 300, in saveImage
>   File "drawBot/drawBotDrawingTools.pyc", line 102, in _drawInContext
>   File "drawBot/context/baseContext.pyc", line 1546, in save
>   File "drawBot/context/svgContext.pyc", line 195, in copy
>   File "drawBot/context/baseContext.pyc", line 1354, in copy
>   File "drawBot/context/svgContext.pyc", line 73, in copy
> TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by MBurvill** [comment]
I see your commit; is it something I can test already? Are you pushing an update?

**Comment by typemytype** [comment]
uploaded a fresh binary, please test. 
thanks

**Comment by MBurvill** [comment]
Hi I wasn't entirely sure what you meant by uploaded a fresh binary, so I downloaded the latest app from the drawbot website and replaced the old app. 
Now everything is working fine.

Thank you both for looking into this so quickly
