### ISSUE TITLE
Variation font support

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#116]
oke here we go:

support in coreText and how to access variation, 
this should be fairly easy to implement.... but (see below)

``` python
import CoreText
import AppKit

"""
see 

https://developer.apple.com/documentation/coretext/ctfont/font_variation_axis_dictionary_keys?language=objc
https://developer.apple.com/documentation/coretext/1508650-ctfontdescriptorcreatecopywithva?language=objc
"""

def convertNumberToFontAxis(v):    
    hexString = "%08X" % v
    output = []
    for i in range(0, len(hexString), 2):
        unicodeString = hexString[i:i + 2]
        unicodeValue = int(unicodeString, 16)
        output.append(unichr(unicodeValue))
    return "".join(output)

def convertFontAxisToNumber(axis):
    assert len(axis) == 4, "Axis tag must contain 4 characters"    
    hexString = []
    for char in axis:        
        hexString.append("%0X" % ord(char))
    return int("".join(hexString), 16)
        

def listVariationAxes(fontName):
    axes = []
    font = CoreText.CTFontCreateWithName(fontName, 12, None)
    variationAxesDescriptions = CoreText.CTFontCopyVariationAxes(font)
    for variationAxesDescription in variationAxesDescriptions:
        axisTag = convertNumberToFontAxis(variationAxesDescription[CoreText.kCTFontVariationAxisIdentifierKey])
        axes.append(axisTag)
    return axes

print listVariationAxes("Skia")



f = AppKit.NSFont.fontWithName_size_("Skia", 10)

axis = []

for data in CoreText.CTFontCopyVariationAxes(f):
    print data[CoreText.kCTFontVariationAxisIdentifierKey]
    print convertNumberToFontAxis(data[CoreText.kCTFontVariationAxisIdentifierKey])
    print data[CoreText.kCTFontVariationAxisNameKey]
    print data[CoreText.kCTFontVariationAxisMinimumValueKey]
    print data[CoreText.kCTFontVariationAxisMaximumValueKey]
    print data[CoreText.kCTFontVariationAxisDefaultValueKey]
    print

print CoreText.CTFontCopyVariation(f)

desc = CoreText.CTFontDescriptorCreateCopyWithVariation(f.fontDescriptor(), convertFontAxisToNumber("wght"), 0.48)
desc = CoreText.CTFontDescriptorCreateCopyWithVariation(desc, convertFontAxisToNumber("wdth"), 0.62)

f = AppKit.NSFont.fontWithDescriptor_size_(desc, 10)

print CoreText.CTFontCopyVariation(f)
```

what would be the drawBot API for it??
similar as to `openTypeFeatures(tag=True)`

## set a variation
* `fontVariation(tag=0.6, otherTag=.7)`
* `variationAxes(tag=0.6)`

should those number be normalised by drawBot, from coreText we can extract the min max value
(I would vote to normalise between 0-1)

## a list of all supported axis for a given font
`listVariationAxes(fontName)` 

## errors

* what is a font does not have any variation axes? should drawBot check?
* what is a axis is not in a chosen font? should drawBot check?
* raise when the normalised value is smaller then 0, zero and bigger then 1, one
* raise when a axis tag argument is not 4 char long?

**Comment by justvanrossum** [comment]
I suggest (close that what you already did):

- `fontVariations(wdth=0.4, wght=0.8)`  # note: plural
- `listFontVariations()`

Re. your questions:
1. Yes, asking for variations to a non-varfont should raise an exception
2. Yes, if asking for an axis not in the font, an exception should be raised
3. No, values should be clipped between minValue and maxValue, and they should *not* be normalized values
4. Yes, but is implied by 2.

**Comment by typemytype** [comment]
> Yes, if asking for an axis not in the font, an exception should be raised

`openTypeFeatures` does not do this: raise when a feature is not available in the font...

**Comment by justvanrossum** [comment]
Maybe it should? I would love to receive an exception if I misspell an axis tag or a feature tag. Is there a purpose for letting such things pass silently?

**Comment by typemytype** [comment]
maybe it should be a warning, similar as setting `font("Timez")` will simple warn with: `*** DrawBot warning: font: Timez is not installed, back to the fallback font: LucidaGrande ***`

**Comment by typemytype** [comment]
initial var font support here https://github.com/typemytype/drawbot/commit/8ed868888095da746384ddd44c87d844a9b66941

**Comment by justvanrossum** [comment]
> maybe it should be a warning, similar as setting font("Timez") will simple warn with: *** DrawBot warning: font: Timez is not installed, back to the fallback font: LucidaGrande ***

Yeah, maybe that's a nice way to do it.

**Comment by justvanrossum** [comment]
> initial var font support here 8ed8688

SUPERRRRRR!!!!

**Comment by typemytype** [comment]
warnings added here https://github.com/typemytype/drawbot/commit/56522257fa4eae09cdb4bb76a8843dffb5d64017

**Comment by typemytype** [comment]
now the order is maintained but it does not look nice. Dont know how important it is to keep the order of axes in a drawBot environment 

see https://github.com/typemytype/drawbot/blob/master/drawBot/context/tools/variation.py#L27

**Comment by justvanrossum** [comment]
What doesn't look nice? The repr of an OrderedDict? I think it is important to keep the order (it should be used when building a slider UI) and the fact that the repr shows that there is an order is a good hint.

**Comment by typemytype** [comment]
yeah the repr of an OrderedDict, I understand that order is more important than the print statement

this issue can be closed, unless there are other comments and questions...

**Comment by justvanrossum** [comment]
Let's close it. New issues deserve, uhm, new issues :)
