### ISSUE TITLE
Problem with appendGlyph() when specifying a font from its path

### ISSUE THREAD

**Issue by andyclymer** [typemytype/drawbot#119]
This issue is related to the closed pull request #111, it looks like there's still a problem.

I can't seem to use appendGlyph() when the current style of the FormattedString uses a font that was loaded from its path, and not loaded by name. There's no traceback, the text box just shows an empty space instead of the glyph.

I think this sample code will help show what's going on:

```
import drawBot as db

db.newDrawing()
db.size(100, 100)

# This works, I can appendGlyph when the font is called by name
txt1 = db.FormattedString()
txt1.append("abc", font="Helvetica", fontSize=20, fill=(1, 0, 0))
txt1.appendGlyph("dollar") # This works fine
txt1.append("123")
db.text(txt1, (10, 50))

# This doesn't work, the appended glyph doesn't show up when I specify the font from its path
txt2 = db.FormattedString()
txt2.append("def", font="/path/to/font.otf", fontSize=20, fill=(0, 0, 1))
txt2.appendGlyph("dollar") # This glyph won't be drawn
txt2.append("456")
db.text(txt2, (10, 20))

db.saveImage("test.pdf")
```

**Comment by justvanrossum** [comment]
This also warns that the `"/path/to/font.otf"` isn't installed, yet it displays just fine.

**Comment by typemytype** [comment]
I see

.append(...) does not do the same things as .font()

While it should install the font if a path is provided
