### ISSUE TITLE
Color questions on ColorCombinations.py by Nina Stössinger

### ISSUE THREAD

**Issue by alizborsa** [typemytype/drawbot#12]
Using Nina's ColorCombinations.py script to generate combos for a project. I took the RGB values from the InDesign file [Color Settings: Adobe RGB (1998)] to work with in DrawBot.
The result in DB is very different, rather greyish and shady. The screenshot shows the InD file and the DB window.
![screen shot 2015-04-10 at 1 31 56 pm](https://cloud.githubusercontent.com/assets/11886738/7087890/28c5541c-df90-11e4-8a64-8566cbbd6111.png)

Generating pdfs from DB and InD (with no color conversion) and opened them in Preview also shows differences in colors.
![screen shot 2015-04-10 at 2 16 12 pm](https://cloud.githubusercontent.com/assets/11886738/7087935/6785701a-df90-11e4-9b64-5801186b2e3c.png)

What would be the solution for this issue? Thanks!

**Comment by typemytype** [comment]
I don't know directly a handy solution, colours are mysterious :)
A additional setting controlling the color profile / color space

will think about it

```Python
from AppKit import *

"""
see https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSColorSpace_Class/index.html
"""

r, g, b, a = 0.74, 0.51, 1.04, 1

# create a color
base = NSColor.colorWithCalibratedRed_green_blue_alpha_(r, g, b, a)

colorSpaces = [
        NSColorSpace.genericRGBColorSpace(),
        NSColorSpace.adobeRGB1998ColorSpace(),
        NSColorSpace.deviceRGBColorSpace(),
        NSColorSpace.sRGBColorSpace()
    ]


print "Base Color:"
print base.redComponent(), base.greenComponent(), base.blueComponent()
print 

x = 0
for colorSpace in colorSpaces:
    print colorSpace
    c = base.colorUsingColorSpace_(colorSpace)
    r, g, b = c.redComponent(), c.greenComponent(), c.blueComponent()
    print r, g, b
    fill(r, g, b)
    w = width()/len(colorSpaces)
    rect(x, 0, w, height())
    x += w
    print

```

**Comment by ninastoessinger** [comment]
Thanks Frederik, that could be cool. DrawBot is so useful as an InDesign replacement for generating certain kinds of output, such an option might make it even more useful also in a professional context.

**Comment by alizborsa** [comment]
I agree with Nina! I find this question exciting and the code shown above is great and funky! Thanks for the support!

**Comment by typemytype** [comment]
A proposal:
( @LettError and @justvanrossum )

colorSpace(space)

        Set the color space.
        Options are `genericRGB`, `adobeRGB1998`, `sRGB`
        The default is `genericRGB`. 
        `None` will reset it back to the default.

```Python
r, g, b, a = 0.74, 0.51, 1.04, 1

colorSpaces = ['sRGB', 'genericRGB', 'adobeRGB1998']

x = 0
w = width() / len(colorSpaces)

for space in colorSpaces:
    
    # set a color space
    colorSpace(space)
    # this will alter all colors set afterwards
    # and it should work with save() and restore()
    fill(r, g, b)
    rect(x, 0, w, height())
    x += w
```

![screen shot 2015-04-11 at 14 06 24](https://cloud.githubusercontent.com/assets/1190358/7101319/f9c6106a-e053-11e4-9993-97aca4722ef8.png)

**Comment by LettError** [comment]
Is there a way to query which colorspaces are available?

Erik

**Comment by typemytype** [comment]
that could be added, those are all accessible AppKit colorSpaces https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSColorSpace_Class/index.html



    listColorSpaces()

returns a list of available colorSpaces names ['genericRGB', 'adobeRGB1998', 'sRGB']

**Comment by ninastoessinger** [comment]
Now I’m wondering, would it be interesting (or sensical, or even possible) to add spaces/profiles for CMYK too? I guess it depends how much you’d want to support a graphic design / print production workflow…

**Comment by typemytype** [comment]
see the link above, AppKit only provides only a generic and device CMYK profile. 

also see https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DrawColor/Concepts/AboutColorSpaces.html#//apple_ref/doc/uid/20000758-BBCHACHA

**Comment by typemytype** [comment]
committed see https://github.com/typemytype/drawbot/commit/62974b4ca70ad226ec222acf1417b07112b30fee

usage see http://www.drawbot.com/content/color.html#color-spaces
