### ISSUE TITLE
method intersection()

### ISSUE THREAD

**Issue by RafalBuchner** [typemytype/drawbot#123]
I think that BezierPath's method called intersection is buggy: I couldn't use it and I don't know how can I repair it.

this is output from my DrawBot:

Traceback (most recent call last):
  File "intersection_problem.py", line 13, in <module>
  File "drawBot/context/baseContext.pyc", line 499, in intersection
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/booleanOperations/booleanOperationManager.py", line 112, in intersection
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/booleanOperations/booleanOperationManager.py", line 64, in _performOperation
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/booleanOperations/flatten.py", line 64, in __init__
  File "drawBot/context/baseContext.pyc", line 52, in drawToPointPen
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/booleanOperations/flatten.py", line 342, in addPoint
AssertionError

here is my code:
>    stroke(0)
>    fill(None)
>    bezier = BezierPath()
>    bezier.moveTo((100,100))
>    bezier.curveTo((100,200),(200,200),(200,100))
>    drawPath(bezier)

>    bezier2 = BezierPath()
>    bezier2.moveTo((222,200))
>    bezier2.curveTo((200,100),(10,200),(50,100))
>    drawPath(bezier2)

>    bezier2.intersection(bezier)

**Comment by justvanrossum** [comment]
Can't check right now, but it could be because your paths are note closed. (If so, the error message could be better, yes...)

**Comment by justvanrossum** [comment]
Also, intersection() will return a new path if I'm not mistaken.

**Comment by typemytype** [comment]
What is your DrawBot version? I guess this is an older one...

boolean operations on paths requires to have closed paths

this works fine in the current version

```python
stroke(0)
fill(None)
bezier = BezierPath()
bezier.moveTo((100,100))
bezier.curveTo((100,200),(200,200),(200,100))
bezier.closePath()
drawPath(bezier)

bezier2 = BezierPath()
bezier2.moveTo((222,200))
bezier2.curveTo((200,100),(10,200),(50,100))
bezier2.closePath()

drawPath(bezier2)

result = bezier2.intersection(bezier)

fill(1, 0, 0, .5)
stroke(None)
drawPath(result)
```

<img width="1392" alt="screen shot 2017-11-06 at 21 33 13" src="https://user-images.githubusercontent.com/1190358/32462647-6c82d77a-c33a-11e7-82a8-630e8bbe044a.png">

@justvanrossum drawBot could either auto close bezierPaths send to booleanOperations or raise an issue with an open path?

**Comment by RafalBuchner** [comment]
@justvanrossum, @typemytype closing paths works! thanks!
@typemytype I think that I've got last version: 3.101

**Comment by RafalBuchner** [comment]
@typemytype another problem, Is it possible to get intersections between BezeirPath object and another BezierPath object which contains only one line?
```
stroke(0)
fill(None)
bezier = BezierPath()
bezier.moveTo((100,100))
bezier.curveTo((100,200),(200,200),(200,100))
bezier.closePath()
drawPath(bezier)

bezier2 = BezierPath()
bezier2.moveTo((222,200))
bezier2.lineTo((50,100))
bezier2.closePath()

drawPath(bezier2)

result = bezier2.intersection(bezier)

print result.onCurvePoints
```
right now last line of code (`print result.onCurvePoints`) returns empty list

**Comment by typemytype** [comment]
how should the result shape look like?

all paths where the area is 0, zero, will be ignored during a boolean operation

**Comment by justvanrossum** [comment]
@typemytype DrawBot should raise an exception that tells it doesn't support open paths for boolean operations. An AssertionError is rather unfriendly. I vote -1 on implicitly closing paths.

**Comment by RafalBuchner** [comment]
@typemytype you're right. I didn't thought of that, because thing that I'm looking for are only intersection on-curve points. Is there different way to do it without figuring out math from the scratch?

**Comment by typemytype** [comment]
@RafalBuchner BooleanOperations has support to `getIntersections` this can be added in drawBot

see https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/booleanOperationManager.py#L119

**Comment by justvanrossum** [comment]
What is the status of this?

**Comment by typemytype** [comment]
the boolean operation `getIntersections` is not (yet) implemented in a BezierPath. This is still open for debate. 

`aListOfXYIntersections = bezierPath.listIntersections(otherBezierPath)`
