### ISSUE TITLE
UI: cmd-f collapses code panel

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#126]
DrawBot Version 3.102 (3.102) on macOS 10.13 (17A405).

Hitting cmd-f to look for a particular bit of code moves the middle divider bar all the way to the right of the window. The bar cannot be dragged back, DrawBot needs a restart.

**Comment by typemytype** [comment]
mmm, I cannot reproduce it on 10.10

**Comment by typemytype** [comment]
mmm, on 10.13 it shows the thumbnail view here, but then got stuck somewhere

**Comment by dyyybek** [comment]
DrawBot Version 3.106 (3.106) on macOS 10.13

Now cmd-f moves the left divider bar but i can drag it back if i drag it all the way to the edge of the window. Searching (cmd-g) doesn't work unless i click somewhere in the code panel after typing what i want to find. The bar between code panel and output panel is not movable.

<img width="1699" alt="screen shot 2017-11-23 at 00 09 11" src="https://user-images.githubusercontent.com/2214359/33153544-ab7c0fa0-cfe2-11e7-8be5-bb31cb5fcbd8.png">

**Comment by justvanrossum** [comment]
@typemytype / @typesupply: this is possibly caused by new SplitView

**Comment by justvanrossum** [comment]
Btw. when using tabs in full screen mode, adding a new tab will also cause this.
(Sorry, I just observed on a student's machine, I can't reproduce here.)

**Comment by typemytype** [comment]
All cmd f and cmd g shoet keys are send to performFindPanelAction
There is an issue in osx with cmd g see https://github.com/typemytype/drawbot/blob/2f712265cafeba4ccc250554cd72237332bc5c6e/DrawBot.py#L199

I guess my workaround is causing this...

**Comment by typemytype** [comment]
huh good news: Ive tested it on the latest 10.13.2 and it seems to be resolved. This with the current version of DrawBot 3.110

Im able to go full screen and add tabs
Im able to cmd + F or G to toggle the find bar in the coding or print view

If possible please test and report back...

this feels like a bug solved in the OS...

**Comment by typemytype** [comment]
and I cannot find anything the 10.13.2 release notes

**Comment by frankrolf** [comment]
Confirmed. Maybe it was a OS bug too embarrassing to include in the release notes.

**Comment by justvanrossum** [comment]
@RafalBuchner,
