### ISSUE TITLE
DrawBotPy3: the entire Python std library needs to be embedded.

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#127]
As a little todo for Python3 (where we don't have a local Python available).

http://learning-python.com/pyedit-products/unzipped/build/build-app-exe/macosx/include-full-stdlib.py
http://learning-python.com/pyedit-products/unzipped/build/build-app-exe/macosx/setup.py

**Comment by typemytype** [comment]
this list https://github.com/jackmaney/python-stdlib-list/blob/master/stdlib_list/lists/3.6.txt
can be inserted in  https://github.com/typemytype/drawbot/blob/master/setup.py#L104
only for the PY3 version...

and I guess the list can also be smaller: I dont feel to need to support `email`, `mailbox`, `telnetLib`, `tkinter`.... and some more, maybe we have to look at the size?

**Comment by justvanrossum** [comment]
That list seems to be made with the code I reference above, and is far from complete, it's missing a lot of `_underscore` modules. Yest, `tkinter` doesn't make sense, because it won't work together with Cocoa, but for the rest I really want to offer a complete Python stdlib. Why wouldn't someone want to program some email visualisations with DrawBot? I don't want to make any assumptions.

I'm working on it, will push a PR today.

**Comment by justvanrossum** [comment]
Implemented via https://github.com/typemytype/drawbot/commit/876359559a05916bf128856915107656ba19eb08
