### ISSUE TITLE
canvas flipped

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#13]
Hi Frederik,
Just bumped into a weird bug.
Double click the frame border to hide the canvas. Then pull the border back to reveal the canvas. Than my canvas was flipped... 
Running the script again will not solve this problem. Close and reopen will.

after some test:
Seems that it has to do with the canvas size. If canvas height is so high that parts of top and bottom are hidden, then this bug will strike...
 
Is it reproducible on your side?

Best, Thom

**Comment by typemytype** [comment]
nope... I cannot reproduce this

os version?

**Comment by thomgb** [comment]
10.10.3

**Comment by thomgb** [comment]
- I can also redo the bug so the canvas is flipped twice and alright..
- A flipped canvas exports un-flipped images

**Comment by typemytype** [comment]
weird

> A flipped canvas exports un-flipped images

the canvas you see is just an other representation, same as `saveImage(...)`

**Comment by thomgb** [comment]
Really? Sometimes there are (minor) changes in what the canvas shows and how the exported images look like...

left canvas, right export:
![screen shot 2015-04-14 at 17 32 10](https://cloud.githubusercontent.com/assets/1517937/7140559/3e752046-e2cc-11e4-999c-c0b9ae89b4b6.png)

**Comment by typemytype** [comment]
nice, could you share or make an example script?

**Comment by thomgb** [comment]
You've got mail

**Comment by typemytype** [comment]
an error that is also visible in Preview.app
that makes sense cause DrawBot is using the same API to display the pdf

I guess I cannot really help on this one...

![screen shot 2015-04-14 at 22 49 26](https://cloud.githubusercontent.com/assets/1190358/7147107/c7c5f074-e2f8-11e4-942d-44003a483624.png)
