### ISSUE TITLE
app file size

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#130]
with ffmpeg embedded the dmg grows in file size

but there are several duplications of files inside the .app bundle, this could be managed better...

**Comment by typemytype** [comment]
use dataFiles according to @karstenw

only this extra binary tools needs to be accessible for each context in both the .app bundle, the standalone module as in the RoboFont extension, whiteout checking to much what the current environment actually is.

> The external tools belong in the "data_files" section of the setup() command.
> 
> Like this:
> 
> dataFiles = [
>     "Resources/English.lproj",
>     "drawBot/context/tools/gifsicle",
>     ...
> 
> ...
> setup(
>     data_files=dataFiles,
>     ....
> 
> I have the impression that the setup.py makes a lot of unnecessary copying.

**Comment by justvanrossum** [comment]
While using `data_files` makes our setup.py a lot simpler, it doesn't prevent those tools to be included in the site packages zip.

Perhaps the tools should live in a separate place in git (say, `externalTools` on the repo root level), and have the setupAsModule.py script do something special to get them copied to the package itself?

Unless there's an easy way to exclude those files from the packed package.

**Comment by karstenw** [comment]
I'm sorry, that was a premature comment.

The main problem seems to be the location "drawbot.context.tools" which is imported. So all files in there go to the "site-packages.zip".

A solution would be to relocate external tools to Resources, include them via "data_files" and adapt the loading code.

In another project I included ffmpeg via data_files and located it with:

bundle = NSBundle.mainBundle()
resourceFolder = bundle.resourcePath()
ffmpegpath = os.path.join(resourceFolder, "ffmpeg")

**Comment by justvanrossum** [comment]
Yeah, just moving them to Resources would be best. I'm just not sure of the repercussions in the drawbot-as-module-scenario.

**Comment by karstenw** [comment]
It looks easy (maybe it's not) to adapt setupAsModule.py.

The labour part seems to be adapting the loading code for app and module.

**Comment by typemytype** [comment]
oke lets plan this:

* move the tools to the resource folder
* fix setupAsModule to move it again to the `drawBot.context.tools` dir 
* and fix the robofont ext builder so those tools are also copied to `drawBot.context.tools`
*  also create a `mp4Tools.py` containing all the mp4 tools
* search the path of the tool in the same dir (will work for the module and RF ext) if the paths does not exists search it with the NSBundle

**Comment by justvanrossum** [comment]
> also create a mp4Tools.py containing all the mp4 tools

There is nothing right now. What would be useful is an "executeExternalProcess()" function that is general, doesn't use the shell, and doesn't use temp files. Right now there are at least three ad-hoc solutions, and none of those are great. I'll work on something.

**Comment by justvanrossum** [comment]
See https://github.com/typemytype/drawbot/commit/99237380dfcc380ab70771cb8c8e97ad3df5cb3d

**Comment by typemytype** [comment]
will close this issue as this is done see https://github.com/typemytype/drawbot/commit/c0421632652c96c9a469d4d738465d97b6141040
