### ISSUE TITLE
Implement command-period cancelling while script is running

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#141]
I've looked at running a thread that would peek into the event queue, and would then post a SIGINT signal to the main thread, but I can't get that to work: I can't seem to access the main thread events from a secondary thread.

What will work is this: use a trace function, to be used in `sys.settrace(mytrace)`. However, that causes quite some overhead (things slow down by a factor of 1.5 - 2). But if we implement such mechanism in C, the overhead should be _much_ smaller, as at the C level the trace function is just a C function, no Python overhead at all. Will need to experiment with that.

**Comment by justvanrossum** [comment]
Hm, even a C trace function slows down the running code by about a factor of two. A pure Python no-op function actually slows down the code by a factor of 3.

**Comment by typemytype** [comment]
could this be a preference?

**Comment by justvanrossum** [comment]
Absolutely.

**Comment by justvanrossum** [comment]
Ok, I'm back to the old solution: run a thread which polls the event queue. The problem with that is twofold:
- Carbon's `CheckEventQueueForUserCancel()` has no Cocoa equivalent. (`NSApp().nextEventMatchingMask_...` doesn't work from a thread)
- Python doesn't support Carbon anymore, so `Evt.CheckEventQueueForUserCancel()` no longer exists

However, Carbon.framework is still there, and with ctypes I can actually use it after all.

Whipping up a PR now that pretty much reimplements the old DrawBot solution.
