### ISSUE TITLE
PyObjC DeprecationWarning: Using struct wrapper as sequence

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#147]
fe `width, height = image.size()`

should be 
```python
size = image.size()
width = size.width
height = size.height
```

this happens everywhere...

**Comment by justvanrossum** [comment]
See:
https://sourceforge.net/p/pyobjc/mailman/message/36160210/
I just followed up with a "this will break a LOT of code" message.

**Comment by justvanrossum** [comment]
@ronaldoussoren, this project is a tip of the iceberg of PyObjC code that uses the deprecated idiom. As you see in the example above, the alternative is a lot more cumbersome and a less readable. Is there any way we can convince you to "undeprecate" the sequence behavior?

**Comment by justvanrossum** [comment]
It will be undeprecated! https://sourceforge.net/p/pyobjc/mailman/message/36162350/
