### ISSUE TITLE
colorsys module is missing in py3 build

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#148]
Hey Just! Hey Frederik!

I just noticed that colorsys module is not included into the Drawbot py3 build.
Was this intended?

That module is quite helpful for converting colors between RGB to HLS and back.
Could you please consider to include it again?

Cheers

**Comment by justvanrossum** [comment]
Not intended, but a known issue. For now, the workaround is to install Python 3.6 from python.org.

We need to include the entire standard library for Python 3. See #127.

**Comment by justvanrossum** [comment]
(DrawBot will find colorsys (or any stdlib module) from a local Python 3.6 install, but right now we only support the python.org version.)

**Comment by roberto-arista** [comment]
I just installed python3 with homebrew (it works fine from terminal), but DrawbotPy3 still does not find the colorsys module. However, good to know that this issue is in good company :)

Should I run it as module installed from my brand new python 3.6?

**Comment by justvanrossum** [comment]
That's why I explicitly said "we only support the python.org version". Maybe it wasn't explicit enough: we don't currently support homebrew :)

**Comment by justvanrossum** [comment]
Closing, and renamed #127 to something more clear.

**Comment by justvanrossum** [comment]
Solved via https://github.com/typemytype/drawbot/commit/876359559a05916bf128856915107656ba19eb08

**Comment by roberto-arista** [comment]
🎉 🎉 🎉
