### ISSUE TITLE
size() doesn't honour transform()

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#15]
I tried to crop my canvas but it seems this is not the way?

example:
```python
rect(100,200,300,400)
translate(100,200)
size(300,400)
```

The result is cropped from the original origin. Not the one set in line 2. 

I know there is an advice to use `size()` on the top of the script, but I what if you don't know where something will be drawn? 
I have some scripts where (randomly) things are drawn. The script keeps track of the minimum-x, minimum-y, max-x and max-y. Later I want to crop the canvas and/or expand it, to fit it all nicely...

Any ideas?

Thanks, Thom

**Comment by typemytype** [comment]
Hi Thom

see http://www.drawbot.com/content/canvas/pages.html#size <http://www.drawbot.com/content/canvas/pages.html#size>

It is advised to use size() always at the top of the script

gr Frederik
www.typemytype.com

**Comment by thomgb** [comment]
Hi Frederik,

Thanks. I know about the advice. 
There is -for now- no way to crop the canvas, after some drawing is done?

Thom

**Comment by justvanrossum** [comment]
Calculate your positions first, then do the appropriate size() and translate(), then do your drawing.

**Comment by justvanrossum** [comment]
Closing this issue: there's no way size() can honor the current transformation. Imagine a skew or rotation...

**Comment by thomgb** [comment]
Thanks Just. 
Your suggestion is already my current set up :)
