### ISSUE TITLE
hyphenation does not work with Italian

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#154]
Hey!
I assume this is a MacOs issue, but the hyphenation behaves oddly.

Consider the following script (py3)

`myString = "Lo spazio entra a far parte in maniera coerente e strutturale del sistema scrittura. Per chi si occupa di grafica, sarebbe interessante riuscire a trattare grafica e scrittura nella maniera sfumata e continua in cui appaiono. È sterile cercare di costringere la scrittura entro determinati confini. Perché tentare di scindere scrittura e visualizzazione, quando può essere proficuo, dal punto di vista progettuale, considerarle come un insieme unitario? L’idea di cercare di averne una visione più estesa, di espanderne il più possibile i limiti, forse può non essere un approccio rigoroso, ma può portare a sviluppare nuove possibilità."

size(300,400)
hyphenation(True)
language('it_IT')
fontSize(16)
textBox(myString, (20, 0, 210, 400), align='left')
saveImage('hyphenationMistake.png')`

which returns the following image (the red line is added by me afterwards)
![hyphenationmistake](https://user-images.githubusercontent.com/2218712/34203646-39306c0c-e57c-11e7-8c60-92c40ccb2416.png)

the word "interessante" should break as "interes-sante"  instead of "intere-ssante".
Should I send a letter to Cupertino?

**Comment by typemytype** [comment]
hm yeah, drawBot and coreTexr are using the os hyphenation dictionaries. Does it also happen in TextEdit?

**Comment by roberto-arista** [comment]
It's a bit tricky to replicate, because I am not sure which hyphenation dictionary TextEdit is using.
My OS language is set to English, but I think TextEdit recognizes that the language typed is Italian. For example, if I mistype something consciouly, the grammar checker suggests an Italian term as correction. "abracio" --> "abbraccio"

Here is TextEdit screenshot
<img width="183" alt="screenshot 2017-12-20 15 43 09" src="https://user-images.githubusercontent.com/2218712/34212660-48fb1bfc-e59d-11e7-939b-c8b6d3ad23db.png">

TextEdit breaks "interessante" properly, but makes a mistake with "estesa".
It should be "e-ste-sa".

¯\_(ツ)_/¯

**Comment by typemytype** [comment]
Im sorry DrawBot could not help you out more....
