### ISSUE TITLE
adding a small test font to fallback to

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#157]
see https://github.com/typemytype/drawbot/blob/master/tests/testExamples.py#L115
see http://www.drawbot.com/content/text/drawingText.html#drawBot.installFont

**Comment by justvanrossum** [comment]
Yes! Let's add MutatorSans.ttf to the `tests/data` folder. Preferably also an open source otf and non-var ttf. From google fonts or IBM Plex.

**Comment by typemytype** [comment]
MutatorSans.tff is added as test font in #319
