### ISSUE TITLE
euh 'Music' font

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#163]
an installed font with a name like `Music` will cause some issues cause the folder `<user>/Music` also exists. (fe in `listOpentypeFeatures`)

https://github.com/typemytype/drawbot/blob/master/drawBot/drawBotDrawingTools.py#L2137

**Comment by justvanrossum** [comment]
Seems like the ext checking should be done earlier. Also, `not os.path.isdir(path)` may help.
