### ISSUE TITLE
PostScript error when printing from Drawbot

### ISSUE THREAD

**Issue by harbortype** [typemytype/drawbot#164]
I’m using Drawbot to generate proofs for my typefaces during development. My printer is a Kyocera Ecosys M2040dn/L with PostScript emulation (which they call KPDL). 

In previous versions of Drawbot, the printer would sometimes crash when receiving a print job. In Drawbot 3.111 the printer outputs a PostScript error message, as follows:

```
ERROR: invalidcontext 
OFFENDING COMMAND: xshow 

STACK: 

[10.899 10.899 4.9914 11.7774 8.5608 10.0728 8.28 9.0 10.0728 11.5848 
8.5428 4.9914 11.214 10.53 11.5848 10.0728 4.9914 13.9572 10.899 5.8356 
4.9914 12.9366 11.4606 8.28 8.5428 11.4606 11.5848 4.9914 19.2474 
14.2038 4.9914 10.899 10.899 10.899 10.899 10.899 5.8356 4.9914 10.899 
4.9914 13.2012 10.53 8.5608 11.5488 10.0728 11.5848 4.9914 19.7586 10.53 
 6.6618 11.5308 5.8356 4.9914 11.7774 10.53 17.5086 11.4966 8.5608 
5.6952 11.5488 11.5488 10.0728 4.9914 11.7774 12.9360 10.899 4.9914 
10.899 11.6712 19.7586 4.9914 14.238 13.9212 0.0 ] 
(
!"#$%&' (&) *#+,) &#-. /#01' *l) #23#4" ! ! . 5#6#7, %8&) #9, : ; /#$, <=%>8?&#$0@#AB9#CD# 
)
```

I have absolutely no idea what it all means, so maybe you can shed a light on it. 

It is worth mentioning my script automatically saves a PDF file as well. I have noticed that, whenever this error occurs, I can print the PDF normally from Acrobat and Preview.

I’m on MacOS High Sierra 10.13.2

**Comment by justvanrossum** [comment]
What happens if you generate a PDF instead, and try to view and print that with Preview.app?

**Comment by harbortype** [comment]
Sorry for the loooong silence. I've had other problems with the Kyocera and ended up getting a new (old) Xerox Phaser 4510, so I can no longer try this issue. I'm closing this as I suspect the culprit is Kyocera and their faulty drivers.
