### ISSUE TITLE
FormattedString inherited feature state

### ISSUE THREAD

**Issue by andyclymer** [typemytype/drawbot#169]
I found some questionable behavior with 4b2fb67 (from October, I hadn't updated in a while!)

Starting with this commit, as I append more formatted text to a FormattedString the previous feature state is inherited in an unexpected way.

```python
string = db.FormattedString()

string.append("Hello1 ", font="Operator-Medium", openTypeFeatures=dict(smcp=True))
# smcp is turned on

string.append("Hello2 ") 
# No features are specified, should (and does) continue using the previous feature state

string.append("Hello3 ", openTypeFeatures=dict(ss01=True))
# New features are set. 
# Old code would reset feature state (i.e. no smcp), new code keeps smcp on and also turns on ss01

string.append("Hello4!", openTypeFeatures=dict(smcp=False))
# smcp is finally off, but ss01 is still on
```

I just wonder, is this intentional? If it is, I imagine there should be a method to reset the feature state or an attribute to list the current state. 

Thanks!

**Comment by justvanrossum** [comment]
I see a similiar behavior in this snippet:

```python
font("HoeflerText-Regular")
fontSize(50)
openTypeFeatures(liga=False)
openTypeFeatures(lnum=True)
text("Hello 123 fles", (50, 50))
```

The setting from the first `openTypeFeatures()` call is not overridden by the second, which is counter to what I would expect. Indeed, that seems to imply there is no way to reset all features to their default setting.

**Comment by typemytype** [comment]
`openTypeFeatures` (and also `fontVariations`) works like switches, it will not reset the whole opentype feature or font variations settings. 

you can always reset with `openTypeFeatures(None)` or use it in a `with savedState()` block.
With FormattedString you can use:

```python
string = db.FormattedString()
string.append("Hello1 ", font="Operator-Medium", openTypeFeatures=dict(smcp=True))
# reset the opentype features back to the default settings (mind that liga is on)
string.openTypeFeatures(None)
string.append("Hello2 ") 
```

**Comment by justvanrossum** [comment]
Ok, makes sense.

However, I find the `openTypeFeatures(None)` notation super unituitive, for a function that otherwise only takes keyword arguments. It also has no equivalent in the `append()` method.

Also, you're terribly sloppy in argument checking; this is also silently accepted: `openTypeFeatures(1, 2, 3, liga=True)` :)

Let's find an alternative. Maybe simply `openTypeFeatures()` should mean "reset". And then
`string.append(..., openTypeFeatures=dict())` could be used there.

**Comment by typemytype** [comment]
initially written similar to `fill(r=1, g=0, b=0)` and `fill(None)`

I find `openTypeFeatures()` more ambiguous and confusing, it feels like you request something, instead of setting OT fea data. 

proposal:
what about keeping it as it :)
and add:

`openTypeFeatures(liga=False)` disable liga and return the copy of OT fea dict ` {"liga": False}`
`openTypeFeatures(liga=True)` enable liga and return `{"liga": False}`
`openTypeFeatures(smcp=True)` enable smcp and liga (which is still active) and return `{"liga": False, "smcp": True}`

`openTypeFeatures(None)` reset and return `{}`

`openTypeFeatures()` do nothing and return the current OT fea dict `{}`

**Comment by typemytype** [comment]
I know the comparison with `fill` is not completely correct

so as addition:

`openTypeFeatures(liga=False)` --> reset and set enable liga and return the current OT fea dict {'liga' : False)

**Comment by andyclymer** [comment]
I think it makes sense for font variations but it still feels kind of weird because I'm appending a string with some amount of formatting (i.e. the small-capped word) but a little unusual that I then have to turn the feature state back off. Color is a good example, I can't just set the red component and have it inherit the green and blue from the previous character (or can I?)

It's also strange that a change of font still keeps the feature state from the previous:

```python
string.append("Hello", font="Surveyor Text", openTypeFeatures=dict(smcp=True))
string.append("Hello again!", font="Operator-Medium") # still smcp=True
```

**Comment by typemytype** [comment]
> It's also strange that a change of font still keeps the feature state from the previous:

it should, I think, you can swap font but keep the features

a proposal:

```python
from drawBot.misc import DrawBotError


class Test(object):
    
    _defaultOpenTypeFeaturs = dict(liga=True)
    
    def __init__(self):    
        self._openTypeFeatures = dict(self._defaultOpenTypeFeaturs)
        
    def openTypeFeatures(self, *args, **features):
        # return the features dict as reference
        if not args and not features:
            return dict(self._openTypeFeatures)
        # if args and kwargs
        if args and features:
            raise DrawBotError("bla bla bla error")
        # reset with the default data
        self._openTypeFeatures = dict(self._defaultOpenTypeFeaturs)
        # args can only be None: reset
        if args:
            if len(args) == 1 and args[0] is None:
                self._openTypeFeatures = dict(self._defaultOpenTypeFeaturs)
            else:
                raise DrawBotError("bla bla bla error")
        # update if there are key arguments feature given
        elif features:            
            self._openTypeFeatures.update(features)
        # return the features dict as reference
        return dict(self._openTypeFeatures)
        
        
t = Test()

print(t.openTypeFeatures(smcp=True))
print(t.openTypeFeatures(abcd=False, smcp=True))
print(t.openTypeFeatures())
print(t.openTypeFeatures(None))
print(t.openTypeFeatures(test=True))
```

**Comment by justvanrossum** [comment]
I want to give this some more thought. I think I agree with the core principles, but I am strongly opposed to the `openTypeFeatures(None)` notation.

**Comment by justvanrossum** [comment]
Ok, I figured out how it should be done. Proposal:

- deprecate `openTypeFeatures(None)`
- introduce an additional `resetFeatures` keyword argument:
    `openTypeFeatures(liga=False, resetFeatures=True)`
- similarly: `fontVariations(wdth=400, resetVariations=True)`

I will make a PR soon.

**Comment by typemytype** [comment]
top!

so `resetFeatures =True` would reset the internal dict and `resetFeatures=False` would keep adding to the internal dict?

I also like that the method `openTypeFeatures(liga=False, resetFeatures=True)` returns a copy of the dict... as reference

**Comment by andyclymer** [comment]
Sounds good! Thanks you two!

**Comment by justvanrossum** [comment]
I'm working on this now.

> so resetFeatures =True would reset the internal dict and resetFeatures=False would keep adding to the internal dict?

Yes.

About returning the current set of features: that is hard (or impossible) unless the OS offers some way to get at the list of features that are currently on. The way it's done in the `Test` proposal above doesn't work, I think, because what features are on depends on the script and language settings.

**Comment by justvanrossum** [comment]
Returning the current set of features would be very nice, but (if it's possible to doat all) let's do it as a separate PR.

**Comment by typemytype** [comment]
in preparation of that PR see  https://github.com/typemytype/drawbot/issues/178
