### ISSUE TITLE
No more animated gifs

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#17]
`saveImage` a multi page document as `.gif` was an animated gif.
I am no longer able to do so...

**Comment by thomgb** [comment]
Oops. It my own doing. 
I altered the misc.py, so I unzipped the site-packages…
Since misc.py as nothing to do with gif, how should this work again?
Rezip the folder, and delete the unzipped folder did nit help, instead it got worst, the app did not even open :)
Is site-packages a special kind of zip?

O and this is what I altered:
I need a TextEditor :)
https://github.com/thomgb/drawbot/commit/7ca714f809fb36e600400f7a3759b1ffe14616cc

**Comment by typemytype** [comment]
why changing that zip? 

you already forked the source, you just have compile a .app from it.

terminal actions:

    cd path/todrawBotDirectory
    python setup.py py2app -A

`-A` options lets the app work as an alias, so you can edit your code without recompiling the app

I will see how a TextEditor can be added to Variables

thanks and good luck!

**Comment by typemytype** [comment]
could you test this: https://github.com/typemytype/drawbot/commit/d040b593e3e1d5f34277f95e44e68fd2e97186b6

```Python
Variable([
        dict(name="myText", ui="TextEditor"),
    ], globals())
    
print myText
```

Should produce this 

![screen shot 2015-06-12 at 11 27 08](https://cloud.githubusercontent.com/assets/1190358/8127314/f97d600e-10f5-11e5-90d7-66f23dbb2749.png)

thanks!

**Comment by thomgb** [comment]
Thanks for al the info.
Opening the compiled app gives an error. 
`ImportError: No module named vanilla`
I have vanilla in /Library/Python/2.7/site-packages/ 
Should the modules also be copied to path/todrawBotDirectory?

Thanks!

**Comment by typemytype** [comment]
if this isn't resolved yet, please reopen this issue

(vanilla should not be copied to the drawBot root)
