### ISSUE TITLE
RGB Color in exported images not identical to fill() args

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#171]
Somehow RGB colors get calibrated along the way. I've tried to play with different ways of constructing the NSColor in baseContext.py, but I don't notice any change. I tried to set colorSpace() to various values, to no effect, either. Is there some way we can gain exact control over the RGB values in exported images?

Oh, I see I haven't played with the color space name in `imagePixelColor()`. Will do that later, and compare values from PIL.

```python
canvasSize = 400
newPage(canvasSize, canvasSize)

bands = 4
bandWidth = canvasSize / bands

fontSize(10)

for i in range(bands):
    x = i * bandWidth
    for j in range(bands):
        y = j * bandWidth
        r = i / bands
        g = j / bands
        b = 0.5
        fill(r, g, b)
        rect(x, y, bandWidth, bandWidth)
        fill(0)
        text("%s,%s,%s" % (r, g, b), (x + 3, y + 5))

fn = "color_blocks1.png"
saveImage(fn)

# 'genericRGB', 'adobeRGB1998', 'sRGB', 'genericGray', 'genericGamma22Gray'

# colorSpace("sRGB")

for i in range(bands):
    x = (i + 0.5) * bandWidth
    for j in range(bands):
        y = (j + 0.5) * bandWidth
        pix = imagePixelColor(fn, (x, y))
        print(pix)
```

**Comment by justvanrossum** [comment]
Actually, PIL gives the exact same result:

```python
from PIL import Image

canvasSize = 400
newPage(canvasSize, canvasSize)

bands = 4
bandWidth = canvasSize / bands

fontSize(10)

for i in range(bands):
    x = i * bandWidth
    for j in range(bands):
        y = j * bandWidth
        r = i / bands
        g = j / bands
        b = 0.5
        fill(r, g, b)
        rect(x, y, bandWidth, bandWidth)
        fill(0)
        text("%s,%s,%s" % (r, g, b), (x + 3, y + 5))

fn = "color_blocks1.png"
saveImage(fn)

# 'genericRGB', 'adobeRGB1998', 'sRGB', 'genericGray', 'genericGamma22Gray'

colorSpace("genericRGB")

im = Image.open(fn)

for i in range(bands):
    x = (i + 0.5) * bandWidth
    for j in range(bands):
        y = (j + 0.5) * bandWidth
        r, g, b, a = imagePixelColor(fn, (x, y))
        print(" CG:", r, g, b)
        r, g, b, a = im.getpixel((x, canvasSize - y))
        print("PIL:", r/255, g/255, b/255)
```

**Comment by justvanrossum** [comment]
Sorry, I placed the colorSpace() call in the wrong place. Still doesn't have an effect if I move it up, after newPage().

**Comment by justvanrossum** [comment]
I suspect it has to do with the intermediate PDF step.

**Comment by typemytype** [comment]
while [creating the pdf context ](https://github.com/typemytype/drawbot/blob/master/drawBot/context/pdfContext.py#L54) some additional keys could be provided that could help with colors, (I guess) 

see [CGPDFContextCreate](https://developer.apple.com/documentation/coregraphics/1454204-cgpdfcontextcreate?language=objc)

see [Auxiliary Dictionary Keys](https://developer.apple.com/documentation/coregraphics/cgpdfcontext/auxiliary_dictionary_keys?language=objc)

and see [kCGPDFXDestinationOutputProfile](https://developer.apple.com/documentation/coregraphics/kcgpdfxdestinationoutputprofile?language=objc)

hope this helps

**Comment by justvanrossum** [comment]
Thanks, that was new to me. Yet I don't think the solution is there, because apparently PDF doesn't have a global color space, but the color space can be per color.

I seem to be having success by using `Quartz.CGColorCreate` instead of `Quartz.CGColorCreateGenericRGB` in `_rgbNSColorToCGColor()` in `PDFContext`:

```python
        return Quartz.CGColorCreate(Quartz.CGColorSpaceCreateDeviceRGB(), (c.redComponent(), c.greenComponent(), c.blueComponent(), c.alphaComponent()))
        ###return Quartz.CGColorCreateGenericRGB(c.redComponent(), c.greenComponent(), c.blueComponent(), c.alphaComponent())
```

Now, the larger question is probably how to get at the appropriate color space, and make it work with the DB `colorSpace()` function. I will look further.

**Comment by justvanrossum** [comment]
Tangentially interesting: https://github.com/typemytype/drawbot/issues/12
