### ISSUE TITLE
ImportError while installing drawBot module

### ISSUE THREAD

**Issue by jtanadi** [typemytype/drawbot#172]
`from fontTools.misc.py23 import basestring, PY2, unichr`
`ImportError: cannot import name PY2`

I'm getting this ImportError because it seems that I have an older version of fontTools (I'm guessing installed with RoboFont a while back). Reinstalled fontTools from pip and drawBot module installation works.

**Comment by justvanrossum** [comment]
Wait, so you found a problem, then managed to fix it? I suppose we can close this, right?

Perhaps the `setupAsModule.py` should check for a fonttools version number, in `setup_requires` or whatever it's called.

**Comment by typemytype** [comment]
it should check the min version of fontTools...

**Comment by jtanadi** [comment]
Yes, I just wanted to let you know of the slight hiccup in case there’s anything you want to do (check version of fontTools, for instance).
