### ISSUE TITLE
Drawbot window does not open properly.

### ISSUE THREAD

**Issue by typerdeli** [typemytype/drawbot#176]
When opening a new file or an existing file, only the canvas and the pages part to the left can be seen, the coding area to the right is not there. Restarting computer and new installation of Drawbot doesn't help. My mac uses the operating system 10.13.1. Has anybody an idea?

**Comment by justvanrossum** [comment]
Upgrade to 10.13.2, there are some issues with 10.13.1. Please let us know whether that helped!

**Comment by typerdeli** [comment]
It workes with 10.13.2!! Thank you very much!!!
