### ISSUE TITLE
Find/Cmd+F causes issues

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#181]
A small non-urgent thing I wanted to let you know about, running Drawbot 3.114 with Mac OS 10.13.1 (17B1003):

When I use Edit > Find or `cmd`+`f`, it causes code portion of the window to get minimized to its narrowest possible setting, and for the preview portion to get maximized. When I attempt to drag it back, I’m unable to return to the original settings where I see both code and preview at the same time. Here is a video: https://youtu.be/-myTtWZXG64

This is not new to 3.114 for me, and might have something to do with High Sierra rather than your app, but I haven’t seen it anywhere else so I figured I might as well report it.

Again, no big deal, but let me know if any additional information would be helpful. Thank you!

**Comment by typemytype** [comment]
what OS are you on?

see https://github.com/typemytype/drawbot/issues/126

this was identified as a macOS bug :)

**Comment by djrrb** [comment]
Sorry, missed that one. Thank you! ;-)
