### ISSUE TITLE
'rvrn' feature support?

### ISSUE THREAD

**Issue by casasin** [typemytype/drawbot#190]
AFAIK the 'rvrn' feature is needed for jumps in VAR (as in $, p.e.). Is it planned to be supported?

**Comment by justvanrossum** [comment]
That's up to CoreText. But see #165, the font @thomgb uses `rvrn`, and it works to some extent. It exposed a CoreText bug, though, that apparently is fixed in the next 10.13 update.

**Comment by casasin** [comment]
Hmm, ok. I'm still under 10.12.6… Will try in a newer OSX version. Thanks!

**Comment by casasin** [comment]
Confirmed: `rvrn` works in latest OSX Beta. Cool and thanks again.

**Comment by justvanrossum** [comment]
What do you mean "still"? I'm on 10.10 :)

**Comment by casasin** [comment]
Old school stay true ; )
