### ISSUE TITLE
print command w/ parentheses yields unexpected result

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#191]
I am sitting in a workshop with @andyclymer, and he is teaching the new-style `print` statement (always using parentheses), although we are effectively still running Python 2.7.

It works well, except in this example:

```
print()
```
yields
```
()
```

**Comment by frankrolf** [comment]
🤔 This seems to happen in the command-line Python too, so I’ll close this.

**Comment by typemytype** [comment]
in py2 it is actually printing a tuple 
in py3 its calling a method

**Comment by justvanrossum** [comment]
You can solve this by adding
```python
from __future__ import print_function
```
at the top of your script.

**Comment by justvanrossum** [comment]
To get Py3 print behavior in Py2, that is.

**Comment by frankrolf** [comment]
Thanks Just, I am aware of that.
Using the parentheses mainly was an attempt to not confuse students.

**Comment by justvanrossum** [comment]
In that case, just use Py3 DrawBot.
