### ISSUE TITLE
Fit canvas to the view after hitting run

### ISSUE THREAD

**Issue by typoman** [typemytype/drawbot#193]
In a case canvas is big like say an "A4" document, after hitting run the upper part of the canvas does not appear in the view. I was wondering if it would be possible to add this option to fit the canvas to the screen after hitting run. At current setup it's not convenient to scroll to the top after changing a value which could happen a lot during coding.

**Comment by typemytype** [comment]
its nice now it remembers the zooming state: it could be fitted to the canvas but also zoomed into a specific area. 

You can use a right click contextual menu to set the zooming level
