### ISSUE TITLE
Multiple python installations and site-packages

### ISSUE THREAD

**Issue by typoman** [typemytype/drawbot#194]
If a user has installed a new python installation and is not using the default system python, installed packages will not be in the site-packages that drawbot reads. This caused an issue with using pagebot which I referenced below. I solved it by changing the system python to default installed python but I guess this could also be solved by having an option to change where the drawbot reads the new installed libraries. Maybe a user wants to have a specific library?

https://github.com/TypeNetwork/PageBot/issues/119

**Comment by typemytype** [comment]
depending on the python version during startup a few local paths are added to search for external packages: see https://github.com/typemytype/drawbot/blob/master/drawBot/scriptTools.py#L92-L104

**Comment by justvanrossum** [comment]
Also, so called `.pth` files are searched in these paths, so it's easy to make it search in custom locations.

Beware that you probably don't want to mix Py3 and Py2 packages.

**Comment by typoman** [comment]
Very nice. I think I will use .pth files for this purpose from now on. Thank you!
