### ISSUE TITLE
3d support?

### ISSUE THREAD

**Issue by liavkoren** [typemytype/drawbot#197]
How difficult would it be to add 3d drawing support, similar to the way Processing can draw 3d graphics? I've spent _maybe_ an hour reviewing the math/algos and poking through the drawbot source code, so I don't yet have a good idea if this is a reasonable thing to be asking about. 

If you wanted to chat about how this might be done, I have time and interest and might be able to do implementation.

**Comment by typemytype** [comment]
3D support will likely not happen natively inside DrawBot. However there are packages around able to project a 3D transformation into a 2D world. DrawBot allows to import local packages. 

Hope this helps!
