### ISSUE TITLE
path.union depends on winding order

### ISSUE THREAD

**Issue by cburns4563** [typemytype/drawbot#199]
I would have expected the result of these unions to be the same. Instead, it appears to depend on the winding order of rect2. 

````
def rect1(x,y,w,h):
        p = drawBot.BezierPath()
        p.rect(x,y,w,h)
        return p;

def rect2(x, y, w, h):
        p = drawBot.BezierPath()
        p.moveTo((x, y))
        p.lineTo((x, y + h))
        p.lineTo((x + w, y + h))
        p.lineTo((x + w, y))
        p.closePath()
        return p

def draw(p, x, y):
        p.translate(x, y)
        drawBot.drawPath(p)

drawBot.fill(None)
drawBot.stroke(1,0,0)
r1 = rect1(100,200,300,100)
r2 = rect1(200,100,100,300)
r3 = rect2(200,100,100,300)
draw(r1.union(r2), 0, 0)
draw(r1.union(r3), 500, 0)
````

**Comment by justvanrossum** [comment]
For better or for worse, that's the nature of the beast that implements these operations (booleanOperations via the Clipper library). I'm fairly sure it's not easy to change this behavior.

**Comment by cburns4563** [comment]
Thanks for the reply. 
I decided to use Polygon ( http://www.j-raedler.de/projects/polygon ) for all my boolean ops. It seems to be working well. Converting to drawBot paths just before drawing.
