### ISSUE TITLE
DrawBot py3 — Randomly(?) shifting baseline when drawing with `BezierPath.text(`

### ISSUE THREAD

**Issue by stenson** [typemytype/drawbot#200]
Though not all typefaces seem to have this problem, some typefaces when rendered via `BezierPath.text` in the experimental py3 build of DrawBot seem to have a randomly shifting baseline, which does not occur at all for any typefaces I've tested in the python 2 version.

An example with Times, with the text rendered at `y = 0` in all cases:

Py2 version
![baseline_normal_times](https://user-images.githubusercontent.com/89770/39274447-d4c65582-4896-11e8-8197-a458a0e47470.png)

Py3 version
![baseline_error_times](https://user-images.githubusercontent.com/89770/39274455-e1160b16-4896-11e8-9575-b02977662297.png)

(the red dots indicate the `miny` as calculated from `BezierPath.bounds`)

Other typefaces seem to have more random values than Times ever-increasing one, here's Hobeaux from OHno:

Py2
![baseline_normal_hobeaux](https://user-images.githubusercontent.com/89770/39274624-6f5c4e94-4897-11e8-8c17-da566f674682.png)
Py3
![baseline_error_hobeaux](https://user-images.githubusercontent.com/89770/39274627-7248e932-4897-11e8-95f7-610fbeb55458.png)

Have seen the same issue in the Version 3.113 (3.113) app downloaded from the site as well as a module version built on my machine from the python 3 branch, with sha `4a0d8c8ae3c2`

I tried playing with various options of the `FormattedString` class, but nothing seemed to change the issue.

I realize as I write this that I can programmatically solve for this by translating before drawing according to the calculated `miny` from `.bounds()`, but I thought I'd report it as the behavior differs significantly from the current py2 version.

Here's the code I used to generate the images above:

```python
size(800,200)

font_size = 10
x_offset = 10
i_offset = 0

FONT = "Times"

for i in range(0,120):
    save()
    font_size += 4
    bp = BezierPath()
    fs = FormattedString()
    fs.font(FONT)
    fs.fontSize(font_size)
    fs.append("A")
    bp.text(fs, (0,0))
    _, miny, maxx, _ = bp.bounds()
    fill(0,0,0,0.2)
    x_offset += (maxx * 0.15)
    translate(x_offset, 0)
    drawPath(bp)
    restore()
    fill(1,0,0,0.8)
    i_offset += 0.2
    rect(i_offset, miny, 1, 1)

saveImage("~/Desktop/baseline_error.png")
```

**Comment by justvanrossum** [comment]
I can't reproduce it. On which OS are you?

**Comment by stenson** [comment]
Using High Sierra 10.13.4

**Comment by stenson** [comment]
Was trying to find a workaround and realized that setting the FormattedString `lineHeight` explicitly to any value >= the intended fontSize alleviates the problem completely — I guess there's some incorrect default lineHeight being used when calling the `text` method on High Sierra?

**Comment by justvanrossum** [comment]
> setting the FormattedString lineHeight explicitly to any value >= the intended fontSize alleviates the problem completely

I can confirm this. This should indeed be a good clue about what we need to do to fix the issue.

**Comment by justvanrossum** [comment]
@typemytype, does this issue still exist?

**Comment by typemytype** [comment]
I cannot reproduce it anymore, please test this with the upcoming 3.122 release

**Comment by stenson** [comment]
Also can no longer reproduce in 3.122 — seems fixed!

**Comment by justvanrossum** [comment]
Thanks Rob! Will close.
