### ISSUE TITLE
ModuleNotFoundError: No module named 'fontTools.misc'; 'fontTools' is not a package

### ISSUE THREAD

**Issue by NorbertKrausz** [typemytype/drawbot#201]
Hello. I installed drawBot as a Python Module. When I try to run a simple script (just to see if the module had been correctly installed), I get the following error message:
+++++
  File "/usr/local/lib/python3.6/site-packages/drawBot-3.114-py3.6.egg/drawBot/__init__.py", line 3, in <module>
    from .drawBotDrawingTools import _drawBotDrawingTool
  File "/usr/local/lib/python3.6/site-packages/drawBot-3.114-py3.6.egg/drawBot/drawBotDrawingTools.py", line 11, in <module>
    from .context import getContextForFileExt, getContextOptions, getFileExtensions, getContextOptionsDocs
  File "/usr/local/lib/python3.6/site-packages/drawBot-3.114-py3.6.egg/drawBot/context/__init__.py", line 3, in <module>
    from .pdfContext import PDFContext
  File "/usr/local/lib/python3.6/site-packages/drawBot-3.114-py3.6.egg/drawBot/context/pdfContext.py", line 9, in <module>
    from .tools import gifTools
  File "/usr/local/lib/python3.6/site-packages/drawBot-3.114-py3.6.egg/drawBot/context/tools/gifTools.py", line 8, in <module>
    from drawBot.misc import executeExternalProcess, getExternalToolPath
  File "/usr/local/lib/python3.6/site-packages/drawBot-3.114-py3.6.egg/drawBot/misc.py", line 6, in <module>
    from fontTools.misc.transform import Transform
ModuleNotFoundError: No module named 'fontTools.misc'; 'fontTools' is not a package
+++++
I am wondering, what could be wrong, because fontTools is acutally installed.
Thanks for any help in advance.

**Comment by typemytype** [comment]
I guess this is not the `fontTools` drawBot requires.. 

`pip3 install fontTools` must get you the latest version 

see  https://github.com/typemytype/drawbot#compile-drawbot-from-source

or use this [requirements.txt](https://github.com/typemytype/drawbot/blob/master/requirements.txt) with pip

**Comment by NorbertKrausz** [comment]
Thank you very much for the prompt help. After pip3 install fontTools I getthe following message:
++++
~$ pip3 install fontTools
Requirement already satisfied: fontTools in /usr/local/lib/python3.6/site-packages (3.25.0)
++++
So its seems fine. You mentioned the requirements.txt. How can I use it with pip? Just typing the commands from the file one after each other?

**Comment by typemytype** [comment]
strange, 
fontTools.misc must be available....

----

```
cd path/to/the/drawBot/repo
pip3 install requirements.txt
```
(you can also drag the path of the requirements.txt from the drawBot repo in the terminal to get the correct path to that file)

**Comment by anthrotype** [comment]
try do

pip install —upgrade fonttools

**Comment by anthrotype** [comment]
or pip3 or whatever pip you are using

**Comment by anthrotype** [comment]
if you ask pip to install a generic “fontTools”, and some version is already installed, it will say that requirement is already satisfied. If you want a specific version you say pip install fonttools==3.25.0 or fonttools>=3.21 etc. Passing —upgrade will get you the latest

**Comment by NorbertKrausz** [comment]
Thanks for the additional input. Indeed "pip3 install --upgrade fonttools" prints "Requirement already up-to-date: fonttools in /usr/local/lib/python3.6/site-packages (3.25.0)". Thats the latest official version of fonttools, isn't it. Do I need a previous version to successfully run drawbot?

When I "cd" to the drawBot repo and type "pip3 install requirements.txt", I get the following message:
++++
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
++++

**Comment by anthrotype** [comment]
you install from requirements.txt files using the `-r` option, e.g. `pip install -r requirements.txt`

make sure that the `pip3` executable that you are using is linked with the same python interpreter that you are using to import the drawbot module. Try do `pip3 --version` and see what it prints.

Also try calling pip as a module as `<your_python_executable> -m pip`, instead as `pip3` script, so that you make sure you're installing the dependencies for the expected python environment.

**Comment by NorbertKrausz** [comment]
`pip3 install -r requirements.txt` gives me the following message:
++++
Collecting git+https://github.com/typesupply/vanilla (from -r requirements.txt (line 1))
  Cloning https://github.com/typesupply/vanilla to /private/var/folders/fz/8xvnj9_171ldg1sy_f9zq2djvx3qfp/T/pip-req-build-kf3evu3l
Collecting git+https://github.com/typemytype/defconAppKit (from -r requirements.txt (line 3))
  Cloning https://github.com/typemytype/defconAppKit to /private/var/folders/fz/8xvnj9_171ldg1sy_f9zq2djvx3qfp/T/pip-req-build-x_j2p_t4
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fz/8xvnj9_171ldg1sy_f9zq2djvx3qfp/T/pip-req-build-x_j2p_t4/setup.py", line 9
        print "*** Warning: defcon requires FontTools, see:"
                                                           ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fz/8xvnj9_171ldg1sy_f9zq2djvx3qfp/T/pip-req-build-x_j2p_t4/
++++

For both, `pip --version` and `pip3 --version` I get "pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)" So both seem to link to the correct python interpreter.

Sorry, what I didn't get is the last comment. `<your_python_executable>` should be replaced by what exactly? The test script which causes the initial "ModuleNotFoundError: No module named 'fontTools.misc'; 'fontTools' is not a package" error?

**Comment by anthrotype** [comment]
in requirements.txt, replace "https://github.com/typemytype/defconAppKit" with  "https://github.com/typesupply/defconAppKit"

the upstream defconAppKit has been updated to support python3, whereas the typemytype fork seems out of sync

> what I didn't get is the last comment. <your_python_executable> should be replaced by what exactly?

use the same python interpreter that you used to import the drawbot module.

**Comment by NorbertKrausz** [comment]
requirements.txt almost worked, but now it crashes with the same error at a different place:
++++
Collecting git+https://github.com/typesupply/ufo2svg (from -r requirements.txt (line 16))
  Cloning https://github.com/typesupply/ufo2svg to /private/var/folders/fz/8xvnj9_171ldg1sy_f9zq2djvx3qfp/T/pip-req-build-v7xw5bjv
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fz/8xvnj9_171ldg1sy_f9zq2djvx3qfp/T/pip-req-build-v7xw5bjv/setup.py", line 9
        print "*** Warning: ufo2svg requires FontTools, see:"
                                                            ^
    SyntaxError: Missing parentheses in call to 'print'
++++

**Comment by musca1997** [comment]
try to replace the ufo2svg module url with "https://github.com/musca1997/ufo2svg" in "requirements.txt"
it's just because python3 doesn't support the old "print" thing in python2
