### ISSUE TITLE
Missing method?

### ISSUE THREAD

**Issue by schriftgestalt** [typemytype/drawbot#202]
https://github.com/typemytype/drawbot/blob/8eeb7a8230e72f8ad0fe9a1b3ce5fb0268bd00ff/drawBot/ui/drawBotController.py#L185

```
    # pop up a show put file sheet
    self.showPutFile(["pdf"], callback=self._savePDF)
```
I can’t find where that method is implemented.

**Comment by gferreira** [comment]
[defconAppKit.windows.baseWindow.BaseWindowController](http://github.com/typesupply/defconAppKit/blob/master/Lib/defconAppKit/windows/baseWindow.py#L49)

**Comment by schriftgestalt** [comment]
Thanks.
