### ISSUE TITLE
Feature request: ".drawBot" package file

### ISSUE THREAD

**Issue by andyclymer** [typemytype/drawbot#208]
Making a small design tool with DrawBot can be a very valuable and useful product to provide to a client. It's easy to imagine the kinds of scripts that could be useful to hand off to a customer, but it would be even better to hide the code behind a simple interface. I'm picturing a simple way to turn a script into more of a final "product" for someone else to use. 

The reasoning for this is that I think some people are a little bit scared away by running code, and even more, leaving a code window open might invite hacking that will break the tool and end up making more tech support for the developer. Also, currently, things can get separated easily if a DrawBot script also requires a folder of support files.

It's already possible to make interfaces with Vanilla in DrawBot, but I'd like for someone to avoid having to see the editing window and have to click "Run" in the first place.

So here's what I propose:

A ``.drawBot`` file format, which is really just a package containing an ``init.py`` or ``main.py`` which is auto-run when the file is opened (without the code being shown in a code editor), and as many folders and files of Python documents and resources as the script needs. The script that's auto-run would simply pop open its own interface, just like how extensions work in our favorite font editor. 

The file name extension makes it clear that this is something to be run in the DrawBot app. If someone really wants to dig into the package and edit the Python files they can, this isn't meant to be any security measure to close the source, but it just keeps the code away from the user and puts the interface first.

Thoughts?

**Comment by typemytype** [comment]
`.drawBot` files/packages sounds like a nice solution for this issue: a package can use all the drawBot embedded packages without the need to install anything. 

I assume you also want to 'save' a script as a `.drawBot` package or build one from a root directory. How should this happen?

This should not be that difficult to make. Could you propose a spec for such a file?

**Comment by typemytype** [comment]
must such a packages contains a info.plist with fe requirements? what happens when you run an newer .drawBot file in an old DrawBot.app?

**Comment by justvanrossum** [comment]
Nice idea indeed! Let's try to figure out what needs to be shipped with such a bundle (possibly images and other data).

I would suggest `.drawbot` as a file extension, I somehow dislike camelCase for file extensions.

A next step could be to bundle this bundle with a modified DB app to become a fully standalone thing...

**Comment by andyclymer** [comment]
@typemytype: 

I think you're right that an info.plist would be useful, to at least specify the minimum RoboFont version requirement. But since these files aren't "installed" I'm not totally sure where any other data might show up.

```
Package spec:

    MyTool.drawbot (package)
        info.plist
        lib/
            main.py
            anotherScript.py
            anImage.jpg
```
The ``lib`` folder might not even be needed, but modeling it after the ``.roboFontExt`` file this would leave some room open for new features in the future. But what do you think?

As for the info.plist:

```
info.plist

    name (optional)
    version (optional)
    developer (optional)
    developerURL (optional)
    requiresVersionMajor (required)
    requiresVersionMinor (required)
    mainScript (optional, default to 'lib/main.py' if this isn't specified?)
```

Would it create too much complexity to make a "DrawBot Package Builder" modeled after the "RoboFont Extension Builder"?

**Comment by andyclymer** [comment]
@justvanrossum 
"A next step could be to bundle this bundle with a modified DB app to become a fully standalone thing..."

Whoaa...I like it! Could this be done without recompiling the app, maybe some "autorun" folder in the DrawBot package that this new ".drawbot" file can be added to?

**Comment by typemytype** [comment]
that spec looks good
* code should idd be in a lib folder.
* info.plist: the whole plist could be optional

info.plist

    name: optional, default to <name>.drawBot
    version: optional, default to 0.0, but advised to set
    developer: optional, default to None
    developerURL: optional, default to None
    requiresVersionMajor: optional, default to all versions
    requiresVersionMinor: optional, default to all versions
    mainScript: optional, default to 'lib/main.py' if this isn't specified?)

I guess drawBot should also warn users they are executing something inside DrawBot
similar as a drawBot url
drawbot://www.drawbot.com/_downloads/blendMode.py

@andyclymer drawbot package icon ideas?? :)

**Comment by justvanrossum** [comment]
Please let the package extension be `.drawbot`, not `.drawBot`

**Comment by typemytype** [comment]
.drawbot is fine!
(edited above)

**Comment by typemytype** [comment]
will create a PR for this...
but an initial sketch of an implementation

https://gist.github.com/typemytype/0e220f7c0b24ec26a48db9ab8ee3f426

**Comment by typemytype** [comment]
done!!

thanks for the wicked icon
