### ISSUE TITLE
Installing as module in editable mode using pip?

### ISSUE THREAD

**Issue by typoman** [typemytype/drawbot#212]
I wanted to install the drawbot as a module in the editable mode using:

`pip install -e .`

But apparently it's building the app because I get this:

`ModuleNotFoundError: No module named 'py2app'
`

I know there is setupAsModule.py to install it as a module but I'm not sure if it's handy for someone who wants to change the code and test it many time. Is there a method to install the drawbot as a module in editable mode?

**Comment by justvanrossum** [comment]
I was just realizing that indeed, pip will have a problem with setup.py not being called setup.py... Not sure what the solution is.

**Comment by justvanrossum** [comment]
Solution 1:
- rename setup.py to setupApp.py
- rename setupAsModule.py to setup.py

Solution 2:
- somehow merge both into one setup.py

**Comment by typoman** [comment]
Solution 1 works perfectly. Since it's only installed once, it's easy to rename it back to what it was for the future commits.

Thanks Just again!

**Comment by justvanrossum** [comment]
Still needing a permanent solution. I would also love for the module to be installable via pip + github repo url.

**Comment by anthrotype** [comment]
:1 for solution 1

**Comment by typemytype** [comment]
as pip + setup.py would be used more (if its been setup :) ) then building the app itself, solution 1 is a gogogo
