### ISSUE TITLE
Drawbot install issue

### ISSUE THREAD

**Issue by RenaudFutterer** [typemytype/drawbot#216]
Hi there, I'm trying to install drawbot as a python library but I'm failling, I tried to install every bits needed but there is still an issue

Here is the message, I can't figure it out...

thanks if anyone can figure this one! I'll keep trying to figure it out.

> $ sudo python setup.py install
> 
> Traceback (most recent call last):
>   File "setup.py", line 7, in <module>
>     from drawBot.drawBotSettings import __version__
>   File "/Users/renaudfutterer/Documents/Python/drawbot-master/drawBot/__init__.py", line 3, in <module>
>     from .drawBotDrawingTools import _drawBotDrawingTool
>   File "/Users/renaudfutterer/Documents/Python/drawbot-master/drawBot/drawBotDrawingTools.py", line 11, in <module>
>     from .context import getContextForFileExt, getContextOptions, getFileExtensions, getContextOptionsDocs
>   File "/Users/renaudfutterer/Documents/Python/drawbot-master/drawBot/context/__init__.py", line 3, in <module>
>     from .pdfContext import PDFContext
>   File "/Users/renaudfutterer/Documents/Python/drawbot-master/drawBot/context/pdfContext.py", line 11, in <module>
>     from .baseContext import BaseContext
>   File "/Users/renaudfutterer/Documents/Python/drawbot-master/drawBot/context/baseContext.py", line 15, in <module>
>     from .tools import openType
>   File "/Users/renaudfutterer/Documents/Python/drawbot-master/drawBot/context/tools/openType.py", line 468, in <module>
>     CoreText.NSFontFeatureTypeIdentifierKey: featureType,
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_lazyimport.py", line 163, in __getattr__
>     raise AttributeError(name)
> AttributeError: NSFontFeatureTypeIdentifierKey

**Comment by anthrotype** [comment]
it's not a good idea to have the setup.py attempt to import the same package one is trying to install.
If you really want to have the version string in one place, you can have the setup.py script use the `ast` module to parse the version string from the package `__init__` module, like fontParts does for example:

https://github.com/robofab-developers/fontParts/blob/6c9f088bd6de94dac0c3c13845d20ee2cde73aab/setup.py#L22-L30  

i'm not sure this will fix the current issue, but it might work.

**Comment by anthrotype** [comment]
also `sudo python setup.py install` is not very advisable either.
I'd recommend you install a separate python distribution (either via homebrew or by downloading the installer from python.org website) and leave the system python alone.

**Comment by RenaudFutterer** [comment]
Thanks for this, I've look into it see now why I don't want to use sudo. I do have an installed separate python distribution working ok on my machine though.

But I'm a bit confused to how I'm suppose to install the drawbot module without the setup.py? I also have the same errors without sudo and using the py2app method. I followed all the instruction here https://github.com/typemytype/drawbot/blob/master/README.md

I'm sorry I don't know anything about the ast module you are mentioning nor how it would work, too much of a newb for this :)

**Comment by typemytype** [comment]
the attribute `NSFontFeatureTypeIdentifierKey` is introduced in a newer version of pyobjc 

I would recommend to install python 3 and install all the required packages, in there. 
Use this [requirement.txt](https://github.com/typemytype/drawbot/blob/master/requirements.txt) with pip to install all the packages.


Good luck!
