### ISSUE TITLE
Emoji encoding and permissions problem

### ISSUE THREAD

**Issue by nedkamburov** [typemytype/drawbot#217]
Hello, 
I encountered a problem while trying to display characters from "AppleColorEmoji" typeface and I read on https://pypi.org/project/emoji/ that I can install a library with pip. Unfortunately, I couldn't install it.

<img width="1430" alt="screen shot 2018-09-19 at 15 51 00" src="https://user-images.githubusercontent.com/11830669/45757508-d4828180-bc23-11e8-9eed-0915ddb71fca.png">

<img width="687" alt="screen shot 2018-09-19 at 15 46 22" src="https://user-images.githubusercontent.com/11830669/45757438-a735d380-bc23-11e8-821e-94d3458fc7c7.png">

**Comment by typemytype** [comment]
try: `sudo pip3 install emoji --upgrade`

sudo will prompt you for password, this helps with the permission error you get

good luck!!

**Comment by typemytype** [comment]
but DrawBot should manage to draw emoji characters 

```python
t = FormattedString()
t.font("AppleColorEmoji")
t += "All Apple Color Emoji:\n"
t.appendGlyph(*t.listFontGlyphNames())


while t:
    newPage(1000, 1000)
    t = textBox(t, (0, 0, 1000, 1000))    
```

![screen shot 2018-09-19 at 16 04 28](https://user-images.githubusercontent.com/1190358/45758351-b289fe80-bc25-11e8-8ac2-2c55cd7cdc31.png)

**Comment by nedkamburov** [comment]
Hello Frederik,
thanks for your help, I don’t know why it doesn’t work in my example then. I see that it displays emojis but I don’t see why when I write them later in the shape they come out as a string instead of the emojis.

thanks for your quick response and sorry for my newbie problem…

all the best,
ned

**Comment by nedkamburov** [comment]
Oops, something else happened now…
I did use the sudo command, but perhaps it’s not enough

**Comment by typemytype** [comment]
Could you show a smaller example where you add the glyph name to the formatted string object?

Im guessing you are using the glyph names as strings while drawing, in this case DrawBot will draw the glyph names instead of the character with a given glyph name.

**Comment by nedkamburov** [comment]
But this screenshot was actually from the sketch you send me…
Just in case I checked if it works with other typeface—no problem. Do you think it’s some kind of python permission problem with my system? I was updating some python version, pip, I already included some emoji library, maybe I messed up something.

**Comment by nedkamburov** [comment]
Okay, 
Sorry Frederik for the whole hassle. I reinstalled Drawbot and now everything works.

Thank you!
