### ISSUE TITLE
Switch off macOS Text Replacement in code window

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#219]
It is not possible to switch off macOS text replacement in the code window.
This always results in odd behavior for me – for instance, `print(c)` will automatically be replaced by `print©` on my system – which is annoying.
In theory, I could just uncheck the option on right-click, but for some reason it does not seem possible in DrawBot.

<img width="588" alt="screen shot 2018-09-21 at 14 52 12" src="https://user-images.githubusercontent.com/2049645/45882470-8bab0400-bdae-11e8-974a-cc19a1f4e2a4.png">

**Comment by justvanrossum** [comment]
Off sounds like a better default.

Why is it not switchable by the user?

**Comment by typemytype** [comment]
added in #213
