### ISSUE TITLE
Attempting to switch off default "calt" feature for FormattedString fails, string does not render

### ISSUE THREAD

**Issue by ninastoessinger** [typemytype/drawbot#22]
In a `FormattedString`, even when `openTypeFeatures` are set to `None`, some features still seem to be activated by default – certainly contextual alternates, not sure what else. (Normal strings also appear to have calt on by default, FWIW.) 
I can switch additional features *on* but have not been able to force this one *off*, like so:
```
k = FormattedString()
k.openTypeFeatures(calt=False)
```
This does not only not switch the calt off, but in fact makes the entire string not render at all.

It would be really nice to have full control over what the glyphs are in the FormattedString and not have CoreText do some kind of magic on it. Do you think there’s any chance the above can be made to work?

**Comment by karstenw** [comment]
Have you checked with ```listOpenTypeFeatures``` if the font contains the 'calt' feature?

A Test run with this little snippet gave exactly 0 fonts on my machine .

```python


fonts = installedFonts()

for font in fonts:
    l = listOpenTypeFeatures( font )
    if not l:
        continue
    if 'calt' in l:
        print font, l

```

**Comment by typemytype** [comment]
There is an issue with a `calt` feature, this is automatically enabled by CoreText. Switching it off prevent the replacement in an attributed string with a NSGlyphInfo. Im investigating...

**Comment by ninastoessinger** [comment]
> Have you checked with listOpenTypeFeatures if the font contains the 'calt' feature?

Yes – I know it’s there, and I can see it being on. :)

**Comment by ninastoessinger** [comment]
PS. For what it’s worth, I just realized that `calt=False` actually appears to work fine when the FormattedString was put together using `append()`, just not for glyphs appended via `appendGlyph()`.

**Comment by typemytype** [comment]
This should be fixed in https://github.com/typemytype/drawbot/commit/ff3ce72ce97e1b61db513a5f99aa434cad5fb514

`.appendGlyph(...)` should always disable the `calt`feature, I guess this is the only one that is automatically on. If there are more features on by default, please report.

**Comment by ninastoessinger** [comment]
That was fast :D Thank you very much!
Are changes here automatically carried over to the drawBotRoboFontExtension? (I’m using drawBot as a module currently)

**Comment by typemytype** [comment]
Not yet, diner first ;)

gr
Frederik
www.typemytype.com

**Comment by ninastoessinger** [comment]
Haha, eet smakelijk :)

**Comment by typemytype** [comment]
done, 

enjoy!
