### ISSUE TITLE
setting frameDuration creates empty page

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#221]
There are a few DrawBot-inherent methods that create an empty page, most of them make sense.
I wonder though why `frameDuration` is among them? It won’t actually output anything visible, so the page is mainly just confusing.

**Comment by typemytype** [comment]
`frameDuration` is an attribute of a page, so a page is required, if there is no page it auto creates one. Similar as other methods which requires a page, like most of the drawing callbacks.

**Comment by frankrolf** [comment]
Got it.
