### ISSUE TITLE
newPage() not possible w/o arguments

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#223]
If a page is not explicitly created, DrawBot will automatically make a new page measuring 1000 by 1000 points. Why is it not possible to imply that using the `newPage()` method without any arguments?

**Comment by frankrolf** [comment]
¯\_(ツ)_/¯
Mainly posting student questions at this point, I’d also expected that (new 1000 × 1000 page) to happen.

**Comment by typemytype** [comment]
so your asking to have a `newPage()` where the fallback is set to 1000, 1000?

**Comment by typemytype** [comment]
it could also fallback to the previous page width height...

**Comment by justvanrossum** [comment]
Yeah, falling back to the previous page size makes most sense to me.

**Comment by typemytype** [comment]
added in #213

**Comment by frankrolf** [comment]
This now works if there is a pre-existing page size, but does not work if there is nothing at all.
(just `newPage()` as the first line of the script).

**Comment by justvanrossum** [comment]
That's not good. I can't verify as my build is broken.

**Comment by justvanrossum** [comment]
Ok, I tested. The following works fine:

```python
rect(100, 100, 100, 100)
newPage()
```
The following doesn't:


```python
newPage()
```

```
Traceback (most recent call last):
  File "drawBot/ui/drawBotController.pyc", line 120, in createContext
  File "drawBot/drawBotDrawingTools.pyc", line 121, in _drawInContext
  File "drawBot/context/baseContext.pyc", line 1914, in newPage
drawBot.misc.DrawBotError: A page must have a width
```

**Comment by typemytype** [comment]
the above commit fixes this
