### ISSUE TITLE
Emoji throw off syntax coloring

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#225]
<img width="561" alt="screen shot 2018-09-26 at 18 44 06" src="https://user-images.githubusercontent.com/2049645/46095285-707c3200-c1bc-11e8-9288-8093c5576062.png">

**Comment by typemytype** [comment]
Emoji counts for two...

**Comment by frankrolf** [comment]
… not in Python 3!

**Comment by frankrolf** [comment]
![screen shot 2018-10-31 at 14 38 17](https://user-images.githubusercontent.com/2049645/47793129-d9a41780-dd1d-11e8-8802-b94ec501ebe3.png)
Maybe the syntax coloring could be applied line-by-line? Would that still work for multiline strings?

**Comment by justvanrossum** [comment]
The problem most likely lies in the difference between Cocoa and Python strings with unicode chars > 0xffff:

```python
from Foundation import NSString, NSUTF8StringEncoding
content = '😎😎😎😎😎😎😎'
s = NSString.alloc().initWithData_encoding_(content.encode("utf-8"), NSUTF8StringEncoding)
print(len(s), s.length())
print(s)
```
```
7 14
😎😎😎😎😎😎😎
```

**Comment by justvanrossum** [comment]
Or rather: it's likely a 4-byte per char vs. 2-byte per char problem.

**Comment by typemytype** [comment]
Oh that still strange in py3 with full unicode support...

It should use the nsstring lenght and substring methods instead of the python len and slice

https://github.com/typemytype/drawbot/blob/master/drawBot/ui/codeEditor.py

**Comment by typemytype** [comment]
a test case:

the range is not correct when there is emoji (or unicode bigger then uFFFF+) when setting a attributes in the attribute string


```python
from pygments.lexers import PythonLexer
from Foundation import NSString, NSUTF8StringEncoding
import AppKit 

lexer = PythonLexer()

text = """
content = '😎😎'
print("hello")
"""

attr = AppKit.NSMutableAttributedString.alloc().initWithString_(text)
setattrs = attr.setAttributes_range_

location = 0

for pos, token, value in lexer.get_tokens_unprocessed(text):
    value = value.strip()
    if value:
        value = NSString.alloc().initWithData_encoding_(value.encode("utf-8"), NSUTF8StringEncoding)
        lenValue = value.length()
        setattrs({"value": token}, (location + pos, lenValue))
        
# this is the correct range for string
# setattrs({"test": 1}, (11, 6))

print(attr)
```
