### ISSUE TITLE
FormattedString doesn't show glyph references in its __repr__

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#231]
```python
f1 = FormattedString()
f1.append("abc")

f2 = FormattedString()
f2.appendGlyph("a")
f2.appendGlyph("b")
f2.appendGlyph("c")
print("f1:", len(f1), f1)
print("f2:", len(f2), f2)
```

```
f1: 3 abc
f2: 3    
```

See also https://twitter.com/ThomHendrik/status/1049909775314669569

**Comment by typemytype** [comment]
a posible solution:

```python
f = FormattedString()
f.append("abc")
f.appendGlyph("a")
f.appendGlyph("b")
f.appendGlyph("c")
f.append("xyz")

def __repr__(self):
    return str(self).replace(chr(160), "<glyph>")

print(__repr__(f))
```
```
>>> abc<glyph><glyph><glyph>xyz
```

**Comment by typemytype** [comment]
the appended glyph could be anything, also a glyph without an unicode value "A.smcp", so there is no textual representation...

**Comment by justvanrossum** [comment]
That's a great improvement. Perhaps it could show FL glyphname notation:

`abc/a/b/c xyz` (but oh that space is ugly...)

**Comment by typemytype** [comment]
I guess there a good reason why NSString is replacing it with an no breaking space... as textual representation

**Comment by justvanrossum** [comment]
I think the non-breaking space is a fairly arbitrary placeholder: the actual glyph reference is in the attributes, no? That's how I thought it works.

**Comment by typemytype** [comment]
mmm, maybe its easier to change the https://github.com/typemytype/drawbot/blob/master/drawBot/context/baseContext.py#L1710

into `FFFD` �, which is the default unicode replacement character...

**Comment by justvanrossum** [comment]
> into `FFFD` �, which is the default unicode replacement character...

That makes a lot of sense. If that doesn't break anything else, I'd say: go for it!
