### ISSUE TITLE
can't open current dmg on 10.10 and 10.11

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#233]
<img width="484" alt="capture d ecran 2018-10-17 a 09 41 50" src="https://user-images.githubusercontent.com/1190358/47070395-5ea51200-d1f1-11e8-81c6-321c6764fab6.png">

**Comment by justvanrossum** [comment]
Oops. Confirmed on 10.10.5:
![image](https://user-images.githubusercontent.com/4246121/47073420-8ea3e380-d1f8-11e8-9382-4c62c8787ecd.png)

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/drawbot/commit/7e71896ff9b131fab337d08f4ad54357d2b3382e
