### ISSUE TITLE
Drawbot crashes when trying to change colors in preferences

### ISSUE THREAD

**Issue by sandersturing** [typemytype/drawbot#234]
Drawbot crashes when you try to change the color of an element in the preference pane.
The colorwheel comes up, but Drawbot crashes when changing the colors. When it doesn't crash right away it doesn't save the color.

Only on changing colors for elements; the background color **can** be changed. Also bold/italic/underline can be changed (and the change is reflected in the app). Happens on OSX 10.14

**Comment by typemytype** [comment]
fixed in the source, will be solved in the next release

thanks!
