### ISSUE TITLE
Frequent crashing when switching between two scripts that both use Variable()

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#24]
...and actually misbehaving in general.

- Run script 1, drag slider.
- Run script 2, looks good so far, pull slider: Vars from script 1 are shown.

**Comment by justvanrossum** [comment]
[vars_bug_test.zip](https://github.com/typemytype/drawbot/files/82505/vars_bug_test.zip)

**Comment by typemytype** [comment]
this should fix it:

https://github.com/typemytype/drawbot/commit/b9a5279f271fe36675b1687b3b9f39dd5584afaa

**Comment by justvanrossum** [comment]
The behavior is correct now. Let's hope it'll be crashing less, too :)
