### ISSUE TITLE
no notification for update available

### ISSUE THREAD

**Issue by gferreira** [typemytype/drawbot#241]
DrawBot 3.117 is out, but I didn’t get any notification to upgrade (from 3.116) even though *Check for updates at startup* is checked in the Preferences. and *Check Now* says “DrawBot 3.116 is currently the newest version”…  🤔

**Comment by frankrolf** [comment]
I was looking for that as well today. I was also wondering if there could be a conventional “check for updates” item in the File menu?

**Comment by typemytype** [comment]
there is the "Check Now" button in the pref window?
(but there was a ssl bug so it takes 2 generations to have this working properly...)
