### ISSUE TITLE
GetFile raises NotImplementedError

### ISSUE THREAD

**Issue by arialcrime** [typemytype/drawbot#249]
Hey there,

For a font proofing script inside Drawbot 3.117 I thought it would be handy to use GetFile from fontParts. So as a test, I tried to import and use it like this:

```
from fontParts.ui import GetFile

print(GetFile())
```

Sadly, this throws a NotImplementedError. I can imagine that this was a conscious decision, nevertheless I wanted to ask if it would be possible to make it accessible within Drawbot. Or is there another and/or better way to do something like this?

Thanks in advance!

**Comment by typemytype** [comment]
For fontPart an implementation must set those callbacks. 

DrawBot could maybe set some of the ui callbacks, but not all as there is not such a thing as CurrentFont or CurrentGlyph

**Comment by justvanrossum** [comment]
I think it's ok for fontParts to behave the same in DB as it would from Terminal, so I don't really see a bug here.
