### ISSUE TITLE
textSize and center alignment offset by tracking

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#25]
In v3.68, I am using tracking() along with textSize() and textBox(align="center"). In both cases, it pads the right side of the text with tracking, resulting in a textSize() width that is wider than the actual text, and a centered textBox that isn't actually centered.

Attached is a simple script that shows what I am talking about.

[drawBotTracking.py.zip](https://github.com/typemytype/drawbot/files/82807/drawBotTracking.py.zip)

Is it possible (or desirable) to adjust these so that they measure the right side without the additional tracking? Thanks!

**Comment by justvanrossum** [comment]
Hm, this gives a hint: http://stackoverflow.com/questions/23741850/nsstring-drawinrectwithattributes-not-correctly-centered-when-using-nskernattr But that's still a mess with a FormattedString I suppose.

**Comment by justvanrossum** [comment]
(And that idea, to apply the "kerning" only to the n-1 chars won't work for a text longer than one line, als also wrapped lines are not centered the way one could expect.

**Comment by typemytype** [comment]
But I guess drawbot could ignore the last NSKernAttributeName

All text is draw as lines.... Split in attribute runs

gr
Frederik
www.typemytype.com

**Comment by justvanrossum** [comment]
Well, if the text engine makes that possible without much hassle... Sounds like a multilingual/directional can of worms.

**Comment by typemytype** [comment]
mmm, it some how works magically with arabic, almost amazingly...
but it has to be applied before the drawing not while drawing.
so this will not work...

Apple's TextEdit has the same issue. And it makes sense: its called `tracking` in drawBot but Apple calls it kerning (argh). 

<img width="761" alt="screen shot 2016-01-08 at 19 41 26" src="https://cloud.githubusercontent.com/assets/1190358/12206196/dae4abc6-b63f-11e5-9ea8-299a186af3e8.png">

maybe the best solution:
make the the textBox a bit wider `+myTracking`.

**Comment by justvanrossum** [comment]
That will be hard if not impossible with a FormattedString that wildly mixes sizes and trackings. I think we'll just have to accept that this is how it works and the user can correct for it easily in most cases.

**Comment by djrrb** [comment]
I didn't realize that this was happening at a deeper level. 

I have no problem adjusting my textBox size to account for the additional tracking, especially now that I know that you plan for it to stay that way (and I won't be breaking future boxes).

Thanks to both of you for looking into it!

<img width="1133" alt="screen shot 2016-01-08 at 4 11 55 pm" src="https://cloud.githubusercontent.com/assets/6578861/12209656/94471cfc-b622-11e5-88c1-b4e31bb2202c.png">
