### ISSUE TITLE
embedded expected test result are OS depended 

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#252]
this is not so nice: fe fonts and shadow are renderend differently on different OSs... the current expected result in the repo is build and visually check on 10.10. 

The result are different on 10.13 (see [travis test log](https://travis-ci.org/typemytype/drawbot/builds/468057169))

some proposals:
* allow a bigger difference between image files where fonts are used... 
* only test pdf data, image data is build in the current OS and compared as such (so both tested the image data and the expected image data is build on the current OS)
* have more expected test result: `example_installFont@10.13.png` when the current result is macOS10.13, `example_installFont.png` must be used as fallback, this allows us to test very specific image data on multiple OSs, on travis I could setup the test for multiple OSs.

**Comment by typemytype** [comment]
* An other options is to allow some test to fail based on the OS and test those on pdf data or drawing stack...

**Comment by justvanrossum** [comment]
For the images we should try to use `testSupport.compareImages()`, as that allows us to specify how different the images are allowed to be.

**Comment by typemytype** [comment]
a compare error marge is perfect, for me, the diff are mostly in the alpha values for shadows and the rendering of text is different on 10.13 some antialias blue and brown pixels are different.

Rendering text on 10.14 will be really different with default settings... see https://angristan.xyz/how-to-fix-font-rendering-macos-10-14-mojave/

**Comment by justvanrossum** [comment]
This is mostly implemented in the current test suite. Differences will exist, we have fuzzy image compare, and the possibility to skip tests based on the OS version.
