### ISSUE TITLE
Translate not working o SVG export.

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#26]
When trying to export artwork to svg translate didn't work. on the preview inside drawbot the pages look good and even if i export to other image format. Just in case here is my code.
Best regards.

```
canvas = 500
lista = ["Font1","Font2","Font3"]

for i in lista:
    newPage(canvas,canvas)
    font(i)
    fontSize (200)
    lineHeight (150)
    capHeight = fontCapHeight()
    textWidth, textHeight = textSize("Rng")
    translate (canvas/2-textWidth/2, canvas/2-capHeight/2)
    text("Rng", (0,0))
    saveImage("output/thumb.png", multipage=True)
    saveImage("output/thumb.svg", multipage=True)

```

**Comment by justvanrossum** [comment]
It's transforming in general, it seems. textBox() does the same. Here's a simplified test + output files.
[SVGTransformTest.zip](https://github.com/typemytype/drawbot/files/84023/SVGTransformTest.zip)

**Comment by typemytype** [comment]
should be solved here https://github.com/typemytype/drawbot/commit/9928077434efaef027307411e15557704f4394cd

how could I oversee this... :)

**Comment by guidoferreyra** [comment]
Great, how can I update the app?

**Comment by typemytype** [comment]
a new app is pushed to download, you should receive an notification next time you open DrawBot

good luck!
