### ISSUE TITLE
formatted string markup language

### ISSUE THREAD

**Issue by typoman** [typemytype/drawbot#260]
If I want to change some formatting while writing I thought it would be more convenient to have some inline markup syntax that could be interpreted by drawbot and then translated to formattedString object. I was wondering if this is an interesting idea to pursue and if it's so, then how the markup should be. I can give some examples:

`{indent:10}some text here{size:20}another text{lineHeight:10}other text{font:Input-Bold}`

This also could become more compact, for example:
`{i:10}some text here{s:20}another text{lh:10}other text{f:Input-Bold}`

**Comment by typemytype** [comment]
mmm, maybe dont invent the wheel: look at nsattributedstring reading a RTF file. A formatted string is basically a wrapper around an nsattributedstring

**Comment by typoman** [comment]
Good point about the RTF file. But I have to say not all the features of the formatted string is easy to access in TextEdit app or some another app that I could use for making the RTF file. Also I think it would be more consistent to do everything in one editor so I don't have to switch to another editor other than drawbot. Typing the markup language inline while typing is more convenient than having to abandon the keyboard and use a mouse to find the menu to make the text Bold or something else. This way everything is under the hands and there is no need to choose any menu. Does it make sense?

**Comment by justvanrossum** [comment]
For reference, pango implements something in this direction: https://developer.gnome.org/pygtk/stable/pango-markup-language.html

I think for now this is out of scope for DrawBot, so I will close this issue. Please reopen whenever you have a concrete proposal.
