### ISSUE TITLE
Ad-hoc installation of font works every 2nd time

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#261]
```
my_text = FormattedString(
    'I love DrawBot',
    font='my_font.otf')
    
text(my_text, (100, 100))
```

This works the first time, then fails with
```*** DrawBot warning: font: 'my_font' is not installed, back to the fallback font: 'LucidaGrande' ***```
Then works again, then fails … etc.

**Comment by frankrolf** [comment]
I am using DrawBot Version 3.118 (3.118), on macOS 10.14.3 (18D109)

**Comment by frankrolf** [comment]
Same behavior here:
```
my_font = installFont('the_font.otf')

my_text = FormattedString(
    'I love DrawBot',
    font=my_font)
    
uninstallFont('the_font.otf')
text(my_text, (100, 100))
```

**Comment by typemytype** [comment]
I can reproduce it on 10.13

I also notice: after x-amount of re-runs the font is not uninstalled after the script is done.

Im guessing there is some sort of latency between the OS (un)installing the font locally for the app and the script requiring the fonts to draw. (my first lame answer :) )

**Comment by typoman** [comment]
I'm encountering caching of the function installFont() in High Sierra too. Quitting and restarting the DrawBot updates the font.

How to reproduce:
1. Draw text using:
```
w, h = width(), height()
margin = 50
txt = test
installFont(path_to_font)
font("installedFontName", 12)
lineHeight(12)
_box = (margin, margin, w-(margin*2), h-(margin*2))
textBox(txt, _box, align="left")
```
2. Change the font and generate it into a similar path.
3. Rerun the code from (1)

**Comment by justvanrossum** [comment]
@typoman: that is unrelated to this issue. See #112.

**Comment by typoman** [comment]
@justvanrossum Thank you for directing me to the actual issue.

**Comment by colinmford** [comment]
Hi, I'm seeing the same issue. Only I have a fallback font (adobe's blank fallback font) also in the mix. 

If I loop over this a bunch of times, maybe on the 100th loop I'll get an error:
```
my_text = FormattedString(
    'I love DrawBot',
    font='my_font.otf',
    fallbackFont = 'Fallback-Blank.otf'
)
    
text(my_text, (100, 100))
```

```  File "/Users/ford/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/drawBotDrawingTools.py", line 1779, in textBox
  File "/Users/ford/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 2310, in clippedText
  File "/Users/ford/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 1180, in __getitem__
  File "/Users/ford/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 904, in __init__
  File "/Users/ford/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 914, in _setAttribute
  File "/Users/ford/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py", line 1226, in fallbackFont
drawBot.misc.DrawBotError: Fallback font 'Fallback-Blank' is not available```

**Comment by colinmford** [comment]
@typemytype do you think there's anything that can be done here?

**Comment by typemytype** [comment]
@colinmford, I guess this is a different problem. It could not access the installed font.

see https://github.com/typemytype/drawbot/blob/master/drawBot/context/baseContext.py#L1232

try instead of a relativa path, a full path, if possible.

could you make a script that can reproduce this issue?

**Comment by justvanrossum** [comment]
Possible solution: maybe we can use `CTFontManagerCreateFontDescriptorsFromURL` instead of temporarily "installing" fonts.

**Comment by typemytype** [comment]
True, remember trying that out, got stuck somewhere... I dont remember exactly where.

needs a proper investigation... 

see the basicShaping extension, its seems to be possible to set a ctFont in a attributed string: https://github.com/typemytype/basicShapingRoboFontExtension/blob/master/BasicShaping.roboFontExt/lib/CoreTextShaping.py#L35-L37

**Comment by justvanrossum** [comment]
> its seems to be possible to set a ctFont in a attributed string

Yes: "NSFont and CTFont are toll-free bridged"

**Comment by colinmford** [comment]
Hey @justvanrossum and @typemytype,

Just a little late, but I wanted to thank you for fixing this one! I can confirm that it was consistently not working in DrawBot 3.126, but it is now working in 3.127!

🙇‍♂️
