### ISSUE TITLE
FontParts RFont Error

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#262]
Hi all,

There seems to be an issue with instantiating an `RFont` object in the most recent version of `fontParts` shipping with Drawbot v3.118 (`DrawBot_1901022346.dmg`). This worked in previous versions.

<img width="841" alt="screen shot 2019-02-14 at 11 23 42 pm" src="https://user-images.githubusercontent.com/6578861/52835860-559c5280-30b6-11e9-8711-a0dd99ed844b.png">

```
Traceback (most recent call last):
  File "<untitled>", line 2, in <module>
  File "/Users/david/Desktop/DrawBot.app/Contents/Resources/lib/python3.6/fontParts/world.py", line 246, in RFont
TypeError: _fontshellRFont() got an unexpected keyword argument 'pathOrObject'
```

@andyclymer recommended that I use `NewFont()` instead of `RFont()` and that seems to work, but I figured I should report this anyway. I’m not sure if it is truly an issue with fontParts or just the bundling, but since I discovered it here and I figured I’d just let you figure out the best course of action.

As always, many thanks!

**Comment by justvanrossum** [comment]
This must be robotools/fontParts#407, so it'll likely be fixed in the next release, if @typemytype updates the external dependencies, which he usually does.

**Comment by andyclymer** [comment]
David and I were discussing this, I would normally use an RFont to create a new font object, but with FontParts would it be more appropriate to be using NewFont when I’m in DrawBot?

**Comment by justvanrossum** [comment]
> David and I were discussing this, I would normally use an RFont to create a new font object, but with FontParts would it be more appropriate to be using NewFont when I’m in DrawBot?

I don't think it matters much. I'm closing this, please post an issue on the fontParts repo if you have further questions about this.
