### ISSUE TITLE
random does not import shuffle

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#263]
I often use `random.shuffle` to shuffle an iterable. However, it is not available out of the box in DrawBot, so I need to resort to this workaround to avoid a clash with the existing `random`, which in fact is `random.random()`:
```
import random as rnd
rnd.shuffle('abc')
```

Avoidable, perhaps?
I can understand that not all of `random` is interesting for DrawBot, but shuffling seems like it might be. Thank you!

**Comment by justvanrossum** [comment]
I agree that `shuffle` should be imported, I've missed it occasionally, too.

But as a workaround you can just do `from random import shuffle`.

**Comment by typemytype** [comment]
should be added here: https://github.com/typemytype/drawbot/blob/master/drawBot/drawBotDrawingTools.py#L102

**Comment by typemytype** [comment]
is this change is big enough for a fresh release?

**Comment by justvanrossum** [comment]
Thanks, I just added it.

Don't know if it's worth a release, the workaround is pretty simple.

**Comment by typemytype** [comment]
top!

**Comment by typemytype** [comment]
going to build anyway, just to be updated with the embedded packages: https://github.com/typemytype/drawbot/issues/262#issuecomment-463931622

**Comment by frankrolf** [comment]
```
from random import shuffle
shuffle('abcdefghijklmnopqrstuvwxyz')
```
```
Traceback (most recent call last):
  File "<untitled>", line 2, in <module>
  File "random.pyc", line 275, in shuffle
TypeError: 'str' object does not support item assignment
```

**Comment by frankrolf** [comment]
Oh that was quick

**Comment by frankrolf** [comment]
Thank you both!

**Comment by justvanrossum** [comment]
@frankrolf:
```
shuffle(x, random=None) method of random.Random instance
    Shuffle list x in place, and return None.
    
    Optional argument random is a 0-argument function returning a
    random float in [0.0, 1.0); if it is the default None, the
    standard random.random will be used.
```

**Comment by justvanrossum** [comment]
```python
from random import shuffle

def shuffle_iterable(i):
    l = list(i)
    shuffle(l)
    return l
```

**Comment by frankrolf** [comment]
Duh, thanks so much. I never actually tried it with a string, and was confused for a second.
