### ISSUE TITLE
There’s a new version of DrawBot!

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#266]
What happens when I click on `OK`? Is DrawBot downloaded (I assume not) or does the click not do anything?
<img width="562" alt="Screen Shot 2019-03-15 at 00 45 34" src="https://user-images.githubusercontent.com/2049645/54398774-c46fca00-46bb-11e9-9e8f-82c3554066f0.png">

**Comment by justvanrossum** [comment]
Did you click it and nothing happened? Or how should I read your question?

**Comment by typemytype** [comment]
it should start the download 
see https://github.com/typemytype/drawbot/blob/master/drawBot/updater.py#L126

the button title `OK` could be `Download`...

**Comment by frankrolf** [comment]
I clicked and _apparently_ nothing happened. I was on a very slow internet connection, so my suggestion is to include a progress bar.

**Comment by typemytype** [comment]
there is a progress bar without ticks, cause DrawBot does not predict how long it going to take.

**Comment by frankrolf** [comment]
Perhaps add a spinner? I don’t see anything happening until the .dmg is in the Downloads folder.

**Comment by frankrolf** [comment]
Confirmed: Nothing happens when clicking on `OK`.
The dialog just closes, the okCallback never seems to be executed.
Console:
```
error	00:20:02.212309 +0200	DrawBot	nw_path_close_fd Failed to close guarded necp fd 5 [9: Bad file descriptor]
default	00:20:02.274730 +0200	DrawBot	Something went wrong while downloading http://static.typemytype.com/drawBot/DrawBot.dmg
default	00:20:02.276955 +0200	DrawBot	

```

**Comment by typemytype** [comment]
this should be fixed by using https see https://github.com/typemytype/drawbot/commit/1a9645b218b12e32701492b2491cf3c9f9e671bb

**Comment by justvanrossum** [comment]
This should be fixed. Please reopen if you are still experiencing this issue with a newer version of DrawBot.

**Comment by frankrolf** [comment]
Thanks for the update today! 🙌
This works now, as in the `OK` button does download the .dmg file, and mount the image.

Still, this update process is different from any other application. In order to complete the update I need to quit DrawBot, replace the package, and re-open the application.

Many apps have an “Install and restart” dialog when being updated, perhaps that’s something to consider for a future update?

**Comment by justvanrossum** [comment]
PR?

**Comment by MauriceMeilleur** [comment]
My thanks as well, but Frank is getting farther in the process than I am: for me, the OK button just closes the update announcement window. :(

**Comment by justvanrossum** [comment]
Any error messages in the Debugger window (under Help)?

**Comment by MauriceMeilleur** [comment]
Oops, should have looked: 'Something went wrong while downloading https://static.typemytype.com/drawBot/DrawBot.dmg'.

**Comment by justvanrossum** [comment]
Thanks. We just located the bug, and it's quite the miracle that it's working as far as it does for Frank...

**Comment by MauriceMeilleur** [comment]
Must be some bug—still no joy updating from inside DB, same error message. I can download and install from the DB site with no problems, though, so that. Is what I'm gonna do.

Thanks to everyone for all the work on this—looks like a good time to start exploring formatted strings in projects …

**Comment by justvanrossum** [comment]
The bug is inside DrawBot, so it'll only work again in the next update, when the update after that comes out :)

**Comment by typemytype** [comment]
an auto updater is just a lot more work to maintain...  there is already a download and the dmg is open (this bug is already fixed)

there is Sparkle framework, Squirrel and probably more

**Comment by frankrolf** [comment]
I know an auto updater is a lot of work – I’d be happy to help with it, but I don’t even know where to start. Perhaps, a simpler solution would be to show only the `Show in Browser` button (not `OK`). Like that, users would automatically expect a more manual installation process.
