### ISSUE TITLE
DrawBot installer: please include shortcut to Applications folder

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#267]
It would be so nice.
<img width="882" alt="Screen Shot 2019-03-15 at 00 48 06" src="https://user-images.githubusercontent.com/2049645/54398862-23cdda00-46bc-11e9-83d5-99d438b46892.png">

**Comment by roberto-arista** [comment]
50% of my students launch the application from the dmg file 😂

**Comment by justvanrossum** [comment]
I see that happen a lot, too...

**Comment by typemytype** [comment]
inbetween `hdiutil create` and `hdiutil convert`
```
# add a link to the Applications dir
echo "Add link to /Applications"
pushd /Volumes/"${VOL_NAME}"
ln -s /Applications
popd
 
# add a background image
mkdir /Volumes/"${VOL_NAME}"/.background
cp "${DMG_BACKGROUND_IMG}" /Volumes/"${VOL_NAME}"/.background/
```

https://asmaloney.com/2013/07/howto/packaging-a-mac-os-x-application-using-a-dmg/

**Comment by frankrolf** [comment]
Thank you! :-)
