### ISSUE TITLE
ImageObject.gaussianBlur() result not as documented

### ISSUE THREAD

**Issue by MBurvill** [typemytype/drawbot#268]
<img width="543" alt="Screenshot 2019-03-24 at 15 42 49" src="https://user-images.githubusercontent.com/12418488/54882514-bf94de00-4e52-11e9-9e52-bdf5318dc036.png">

Result of ImageObject. gaussianBlur() (above) using the code from the docs doesn't match the documented, expected result below.
([http://www.drawbot.com/content/image/imageObject.html](http://www.drawbot.com/content/image/imageObject.html))
<img width="584" alt="Screenshot 2019-03-24 at 16 36 37" src="https://user-images.githubusercontent.com/12418488/54882553-0c78b480-4e53-11e9-94ba-4113f26cc8bb.png">

Version 3.120 (3.120)
Mojave 10.14.3

**Comment by justvanrossum** [comment]
Hm that's quite dramatic indeed. It's the OS that's causing this, we'll have to see how we can address this. Thanks for reporting.

**Comment by MBurvill** [comment]
Thanks for looking into it!

**Comment by MBurvill** [comment]
Hi Just, I just wanted to let you know that this issue seems to have resolved itself since updating to 10.14.4, cheers!

**Comment by justvanrossum** [comment]
Oh awesome, thanks for letting us know. I'm glad it wasn't our bug :)
