### ISSUE TITLE
locl OpenType feature?

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#269]
I was just typing this, when I noticed it is in fact supported:
> ~~The `locl` feature doesn’t seem to be supported – or am I missing something obvious?
Setting the language for a given text doesn’t change glyph shapes although the font in question may support the locl feature:~~

 I don’t see any mention of this support in the documentation, but I think it’s worth adding.

**Comment by typemytype** [comment]
what is the difference from here https://forum.drawbot.com/topic/128/use-locl-opentype-feature/2

**Comment by typemytype** [comment]
the `language()` method is documented see drawBot but will add that it works together with the `locl` feature

**Comment by typemytype** [comment]
add to the docs https://github.com/typemytype/drawbot/commit/91055e050a21953deb5947e92c9cbeee296dd397
