### ISSUE TITLE
Live updating variables makes preview flicker in El Capitan.

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#27]
Both through Variable() as command dragging values in the script.

**Comment by guidoferreyra** [comment]
I think I readed that this is an issue of OS X? Is this correct?  Could be possible to fix it?

**Comment by typemytype** [comment]
This is indeed an OSx issue

Ive reported it back to apple, as this is also visible in Preview.app

Ive already tried several things, but Im hitting at random cause I don't have a clue

gr Frederik
www.typemytype.com

**Comment by typemytype** [comment]
this seems to be solve on 10.13 
and it was clearly an Apple pdfView issue
