### ISSUE TITLE
Overwriting the default frame rate

### ISSUE THREAD

**Issue by kontur** [typemytype/drawbot#271]
Is there API or hack I could use to overwrite the frame rate set in the [mp4 context](https://github.com/typemytype/drawbot/blob/1a9645b218b12e32701492b2491cf3c9f9e671bb/drawBot/context/mp4Context.py#L22)? 

I’m entirely new to Drawbot but was wondering if the editor somehow exposed the Drawbot internals for this kind of case where you’d want access to the internal objects? Could I somehow import the module from the Drawbot package, overwrite some things, and then pass the context explicitly?

**Comment by justvanrossum** [comment]
You have to use the `frameDuration()` call after each `newPage()`. Call it with `1/25` to get 25 FPS.

**Comment by kontur** [comment]
@justvanrossum Cheers, I didn't expect to find it there and "framerate" didn't find anything in the docs. I added the line to doc string in the PR, could be worth pointing it out in context of saveImage (video).
