### ISSUE TITLE
“small” paper sizes

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#275]
What is the reason for listing “small” paper sizes?
It seems they are just the exact size of their non-small equivalent.

```
small_sizes = [sz for sz in sizes() if 'Small' in sz]
for small_size in small_sizes:
    normal_size = small_size.replace('Small', '')
    print(sizes().get(small_size), small_size)
    print(sizes().get(normal_size), normal_size)
```

**Comment by typemytype** [comment]
cause they are the same...

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing.paperkind

and plenty of sizes are not even added.

**Comment by frankrolf** [comment]
Huh, odd.
Thanks for the link!
