### ISSUE TITLE
.mov output is using 32-bit module

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#277]
<img width="532" alt="Screen Shot 2019-06-16 at 14 27 53" src="https://user-images.githubusercontent.com/2049645/59568026-0f92d380-9043-11e9-8860-2051a1a8e11f.png">

This pops up when exporting a movie from DrawBot running on macOS Mojave.

**Comment by typemytype** [comment]
maybe mov just has to be deprecated in favor of mp4?

**Comment by justvanrossum** [comment]
Maybe it's QTKit that is being deprecated? Can you see whether `import QTKit` gives the same warning?

**Comment by frankrolf** [comment]
It’s hard to say. I tried what you suggested and got no warning. 
However, those warnings only pop up irregularly anyway. for example, trying to export another `.mov` file as a test didn’t trigger any dialog today.

Perhaps you have a smart way of figuring out if a given module contains 32-bit code?

**Comment by justvanrossum** [comment]
It's QTKit indeed: https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_release_notes?language=objc

While there should be a way to convert our usage of QTKit to something more modern, in the meantime maybe use mp4 export, which is done with ffmpeg.

**Comment by justvanrossum** [comment]
Seems @typemytype has given up on #47 in favor of ffmpeg. I only suspect that proper use of AVFoundation may be a lot more efficient.

**Comment by typemytype** [comment]
what would be the benefit to keep .mov around, its not supported by the OS anymore and always requires a conversion to view it...

**Comment by justvanrossum** [comment]
It's not about .mov vs. .mp4, it's about QTKit vs. AVFoundation vs. ffmpeg. Writing each frame as a .png to disk and then running ffmpeg on it can't be the fastest way to write video media...

**Comment by justvanrossum** [comment]
Also, I'm not sure of .mov is in general not supported anymore. The _kind_ of .mov that QTKit builds has always been problematic. But .mov is just a container format.

**Comment by frankrolf** [comment]
I think it would be completely acceptable to deprecate .mov output in favor of .mp4

**Comment by typemytype** [comment]
I cannot open .mov anymore without Quicktime converting them

+1 for deprecating and redirecting .mov to .mp4 + deprecated warning

**Comment by justvanrossum** [comment]
-1 on "redirecting". A deprecation warning for .mov is ok, which should then suggest to use .mp4 instead. But please let users make the change themselves.

(I've _never_ been able to play .mov as made by DB without Quicktime Player having to convert it, so I'm not sure how that even plays a role in this discussion.)

**Comment by typemytype** [comment]
I guess converting .movs started in 10.9 https://developer.apple.com/documentation/qtkit

simple deprecated warning is also fine, however, I assume (not tested) generating .mov will fail on 10.15

**Comment by typemytype** [comment]
![Screen Shot 2019-06-26 at 22 32 38](https://user-images.githubusercontent.com/1190358/60212839-79408800-9862-11e9-8fe3-f8639096a597.png)

maybe until someone figures out how to get AVFoundation working
