### ISSUE TITLE
*** DrawBot warning: OpenType feature 'numr/'dnom' not available ***

### ISSUE THREAD

**Issue by colinmford** [typemytype/drawbot#283]
Hi there, getting an error when trying to access Numerator `numr` and Denominator `dnom` features, not sure why!

DrawBot: 3.118.1 (Extension)
System: Mac OS 10.13.6

Take a font like [Source Serif](https://github.com/adobe-fonts/source-serif-pro) Bold, which has simple `numr` and `dnom` [features](https://github.com/adobe-fonts/source-serif-pro/blob/master/Roman/familyGSUB.fea) as follows:
```Feature
@FIG_LINING_TAB    =  [  zero       one       two       three       four       five       six       seven       eight       nine       ];
@FIG_NUMR          =  [  zero.numr  one.numr  two.numr  three.numr  four.numr  five.numr  six.numr  seven.numr  eight.numr  nine.numr  ];
@FIG_DNOM          =  [  zero.dnom  one.dnom  two.dnom  three.dnom  four.dnom  five.dnom  six.dnom  seven.dnom  eight.dnom  nine.dnom  ];
```
```Feature
@PUNCT_SMALL_FIG    = [ bracketleft      bracketright      parenleft      parenright      period      comma      ];
@PUNCT_NUMR         = [ bracketleft.numr bracketright.numr parenleft.numr parenright.numr period.numr comma.numr ];
@PUNCT_DNOM         = [ bracketleft.dnom bracketright.dnom parenleft.dnom parenright.dnom period.dnom comma.dnom ];
```
```Feature
#--------------------------------------
feature numr { # Numerators
    lookup NUMR {
        sub @FIG_LINING_TAB by @FIG_NUMR;
        sub @PUNCT_SMALL_FIG by @PUNCT_NUMR;
    } NUMR;
} numr;


#--------------------------------------
feature dnom { # Denominators
    sub @FIG_LINING_TAB by @FIG_DNOM;
    sub @PUNCT_SMALL_FIG by @PUNCT_DNOM;
} dnom;
```

And then the following DrawBot code:
```Python
import drawBot as db

db.newPage(500,100)
s = db.FormattedString("123/45679",
    font="SourceSerifPro-Bold.otf",
    fontSize=100,
    openTypeFeatures={"dnom": True}
)

db.text(s, (20,20))
```

The above results in 
```
*** DrawBot warning: OpenType feature 'dnom' not available ***
```

Same with `numr`. If you replace `dnom` with `frac`, the code works, and both numerators and denominators show up. 

The `numr` and `dnom` features work in other programs (like Adobe InDesign), and FeaturePreview. Any idea why they aren't working here?

[DrawBot Error.zip](https://github.com/typemytype/drawbot/files/3398589/DrawBot.Error.zip)

**Comment by colinmford** [comment]
Oh, I see. It's not working because it's not in [this list](https://github.com/typemytype/drawbot/blob/54cbf2a756abe805cc705cde3218bc37f3e71a91/drawBot/context/tools/openType.py#L379), and it's not on this list because it's not [in this registry](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html).

Perhaps this can be fixed in the future by what @jjgod is [referring to here?](https://github.com/typemytype/drawbot/issues/281#issuecomment-508576805)

**Comment by typemytype** [comment]
strange `dnom` is not popping up with `listOpenTypeFeatures(pathToSource)` 

and idd strange its not listed by apple, so no selector key can be found...

**Comment by jjgod** [comment]
> strange `dnom` is not popping up with `listOpenTypeFeatures(pathToSource)`

That is exactly because #281. As I said in that issue, `CoreText.NSFontFeatureSelectorIdentifierKey`  do not always exist in macOS 10.15, you need to check for `kCTFontOpenTypeFeatureTag` instead.

> and idd strange its not listed by apple, so no selector key can be found...

This is because some OpenType features are not mapped to AAT type/selector.

To apply OpenType feature, see the header documentation here:

```
/*!
    @defined    kCTFontFeatureSettingsAttribute
    @abstract   The array of typographic feature settings.
    @discussion This key is used to specify an array of zero or more feature settings. Each setting dictionary indicates which setting should be applied. In the case of duplicate or conflicting settings the last setting in the list will take precedence. In the case of AAT settings, it is the caller's responsibility to handle exclusive and non-exclusive settings as necessary.
                An AAT setting dictionary contains a tuple of a kCTFontFeatureTypeIdentifierKey key-value pair and a kCTFontFeatureSelectorIdentifierKey key-value pair.
                An OpenType setting dictionary contains a tuple of a kCTFontOpenTypeFeatureTag key-value pair and a kCTFontOpenTypeFeatureValue key-value pair.

                Starting with OS X 10.10 and iOS 8.0, settings are also accepted (but not returned) in the following simplified forms:
                An OpenType setting can be either an array pair of tag string and value number, or a tag string on its own. For example: @[ @"c2sc", @1 ] or simply @"c2sc". An unspecified value enables the feature and a value of zero disables it.
                An AAT setting can be specified as an array pair of type and selector numbers. For example: @[ @(kUpperCaseType), @(kUpperCaseSmallCapsSelector) ].
*/
```

**Comment by typemytype** [comment]
> An OpenType setting can be either an array pair of tag string and value number

oh I never knew it could also be a tag string...

**Comment by justvanrossum** [comment]
It seems this is a limitation of CoreText: TextEdit also doesn't support numr/dnom, and it seems it can only be fixed for macOS 10.15, via what @jjgod is explaining here and in #281.

**Comment by jjgod** [comment]
Hang on, there must be some confusion here... What do you mean by "TextEdit also doesn't support numr/dnom,"? If you use `kCTFontOpenTypeFeatureTag` it should work in older macOS releases.

**Comment by justvanrossum** [comment]
> Hang on, there must be some confusion here...

I sincerely hope so!

> What do you mean by "TextEdit also doesn't support numr/dnom,"?

That the advanced typography settings on TextEdit on 10.10 do not show options for numr/dnom:

![image](https://user-images.githubusercontent.com/4246121/61850152-d22c2c00-aeb3-11e9-8e3c-03d782f2a13b.png)


> If you use kCTFontOpenTypeFeatureTag it should work in older macOS releases.

Except so far it doesn't :( But let's discuss in #281.

**Comment by typemytype** [comment]
Im closing this in favour of #281

**Comment by justvanrossum** [comment]
Let's keep this open until the issue is resolved.

**Comment by justvanrossum** [comment]
This should have been fixed in #307. Please reopen if you still experience problems with the upcoming DrawBot release (soon).

**Comment by colinmford** [comment]
@justvanrossum do I have to use any different syntax than the example I pasted above? It seems to behaving the same (no dnom or numr) in the new drawbot build (3.122), I just don't get the warning now.

Is OS 10.15 a hard requirement for this functionality? I am on 10.14.5

**Comment by typemytype** [comment]
still weird

https://github.com/typemytype/drawbot/blob/master/drawBot/context/baseContext.py#L1153-L1155

maybe cause both feature tags and feature selectors are present in the attributed string, the type setting takes the old feature selectors and not the new feature tags...

**Comment by justvanrossum** [comment]
Can you try locally with the old attrs removed? Maybe we have to do a hard version switch.

**Comment by typemytype** [comment]
jep thats it, will make PR

**Comment by colinmford** [comment]
Hey @justvanrossum and @typemytype, this seems to be working for me now, so I'm gonna close!

**Comment by justvanrossum** [comment]
Thanks for confirming!
