### ISSUE TITLE
Preview Area zoom in and zoom out not working.

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#285]
When I hit `cmd +` or `cmd -` the zoom in the preview area is not changing instead I got the osx "alert sound". ~~It works on my laptop but not in desktop. Any Ideas? Maybe is related with my keyboard?~~ EDIT: I just tested on my laptop but zoom only works with trackpad. Is this keyboard shortcut something that ever existed or I’m confused?

OS: High Sierra
DrawBot: 3.120 (3.120)
Keyboard Layout: ISO Español

Best.

**Comment by jo-lang** [comment]
i can second that 
quickly zooming in and out with ```cmd +``` and ```cmd -``` is / was super useful. 
on 10.14.6 this does not work anymore.
this is most likely OS related but if there was a way to get this into drawbot again it would be very nice.

**Comment by typemytype** [comment]
fixed https://github.com/typemytype/drawbot/commit/48537fead0686910c26a92d3c87afe9face96752
