### ISSUE TITLE
/path/to/font.otf

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#29]
Hello, I more of a question than an issue:

```font("/path/to/font.otf")``` is great, but is it also possible to get it feature working in ```BezierPath().text(font="path")```? 

:)

Best, Thom

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/drawbot/commit/c1f583cb98ec4a3bf4b0032a6920d0c58721dcdb

will send binary later on
