### ISSUE TITLE
Create circles using oval?

### ISSUE THREAD

**Issue by GitBruno** [typemytype/drawbot#291]
I am importing some geometry from Drawbot into Solidworks. (via PDF -> ILLUSTRATOR) 

Solidworks tells me my circles are peanuts? I drew the circles using the `oval` function.

    oval(x-(diameter/2), y-(diameter/2), diameter, diameter)

<img width="497" alt="Screen Shot 2019-09-03 at 5 07 13 pm" src="https://user-images.githubusercontent.com/1421477/64232824-0e808c80-cf36-11e9-9916-6e4477ff9521.png">

On a sidenote would it be better if beziers were drawn at 45-degree angle so they are straight?

**Comment by justvanrossum** [comment]
DrawBot delegates this to the OS, via `NSBezierPath.bezierPathWithOvalInRect_` (https://developer.apple.com/documentation/appkit/nsbezierpath/1520647-bezierpathwithovalinrect?language=objc) so this particular behavior is OS-defined.

Potentially we can roll our own, but so far this has never bothered me.

**Comment by justvanrossum** [comment]
The measurements you're seeing must be cause by tiny rounding errors in the floating point math involved. I bet the actual differences are smaller than the dialog reports, unless AI is actually using three decimal digits precision in storage (which it very well may). I'm not sure how precise DrawBot (via Quartz) stores the beziers when writing out PDF.

**Comment by GitBruno** [comment]
All good, thanks for the explanation! I had to draw some big things and noticed the further you go above 0 the less precise it becomes. (fewer decimal places for bigger numbers) The only thing that bothers me is in post-processing most guides and alignment tools are not smart enough to snap to the center when control points are at 45 degrees. :) I started to roll my own using the arc function but it still puts in the 45-degree point! I guess I have to *really* roll my own.

**Comment by GitBruno** [comment]
Just for folks getting here with the same problem:

```python
# https://github.com/typemytype/drawBotRoboFontExtension/blob/master/DrawBot.roboFontExt/lib/glyphContext.py#L23

def straightOval(x, y, w, h, alignCenter=False):
    if(alignCenter):
        x = x - (w/2)
        y = y - (h/2)
    c = 0.5522847493 # https://forum.drawbot.com/topic/105/drawing-a-circle-with-beziers
    hx = w * c * .5
    hy = h * c * .5
    path = BezierPath()
    path.moveTo((x + w * .5, y))
    path.curveTo((x + w * .5 + hx, y), (x + w, y + h * .5 - hy), (x + w, y + h * .5))
    path.curveTo((x + w, y + h * .5 + hy), (x + w * .5 + hx, y + h), (x + w * .5, y + h))
    path.curveTo((x + w * .5 - hx, y + h), (x, y + h * .5 + hy), (x, y + h * .5))
    path.curveTo((x, y + h * .5 - hy), (x + w * .5 - hx, y), (x + w * .5, y))
    path.closePath()
    return path
```
