### ISSUE TITLE
Some characters (presumably) throw off string width calculation

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#292]
I am trying to make a simple proof PDF which shows a character set on a page, completely filling it. I am using the overflow mechanism described here (https://www.drawbot.com/content/text/drawingText.html?highlight=overflow#drawBot.textBox) to get around inconsistent line height, possibly related to  #52 .

Here is a simplified version of the code I’m running from the command line:

```
import drawBot as db
import random
import subprocess


def draw_charset_page(my_font, content, pt_size):
    db.newPage('A4Landscape')
    margin = 10
    line_y = db.height() - 2 * pt_size - 2 * margin
    while content:
        fs = db.FormattedString(
            content,
            font=my_font,
            fontSize=pt_size,
        )

        text_box = (
            margin, line_y,
            db.width() - 2 * margin, pt_size * 2)

        line_y -= 1.2 * pt_size
        content = db.textBox(fs, text_box)


content = (
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklm?nopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
    'abcdefghijklmnopqrstuvwxyz'
)


db.newDrawing()
random_font = random.choice(db.installedFonts())
draw_charset_page(random_font, content, 40)
print(random_font)

output_path = f'{random_font} width test.pdf'
db.saveImage(output_path)
db.endDrawing()
subprocess.call(['open', output_path])

```

No matter which font, the line will always break after the `?`. Other characters I’ve identified with the same (or similar) behavior are `$` and `.` (those don’t predictably break the line in all cases).

<img width="970" alt="Screen Shot 2019-09-09 at 15 29 24" src="https://user-images.githubusercontent.com/2049645/64535186-1dd94e80-d317-11e9-8322-28ace5a3193e.png">

The full test string I am using is the AL-3 character set:

```
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćČčĎďĐđĒēĖėĘęĚěĞğĢģĪīĮįİıĶķĹĺĻļĽľŁłŃńŅņŇňŌōŐőŒœŔŕŖŗŘřŚśŞşŠšŢţŤťŪūŮůŰűŲųŸŹźŻżŽžƒȘșȚțˆˇˉ˘˙˚˛˜˝π–—‘’‚“”„†‡•…‰‹›⁄€₺₽ℓ™Ω℮∂∆∏∑−∕∙√∞∫≈≠≤≥◊ﬁﬂ
```
The resulting PDF is full of premature line breaks, and it’s often not clear which character is triggering the behavior.

---

Side note: as I’m typing this, the text box into which I am typing this also breaks the text after `?` (Safari on macOS 10.14.6), so this may well be a macOS problem.

**Comment by justvanrossum** [comment]
I see the same behavior in TextEdit, so I am assuming it's a CoreText issue.

**Comment by jjgod** [comment]
I can’t see why CoreText would be related to line breaking, would it be possible for you to provide a simplified test case for us to take a look?

**Comment by justvanrossum** [comment]
Maybe I shouldn't have used the word "issue", as I think the behavior is to be expected. 

(But if not CoreText, which component is then responsible for line breaks?)

**Comment by jjgod** [comment]
Typically, on Apple platforms, we use ICU to handle the line breaks according to specific locale and general Unicode line breaking rules.

However, this particular case might or might not involve that, and there can be other factors affecting line breaks, so it would better to look at a simplified test case to investigate further.

**Comment by frankrolf** [comment]
@jjgod If you could point me in the right direction, I can try and simplify this test case even further (just don’t really know what you are looking for).

**Comment by frankrolf** [comment]
@jjgod Here is a video where the same behavior is exhibited in TextEdit. I just pasted the charset string into the window:
```
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćČčĎďĐđĒēĖėĘęĚěĞğĢģĪīĮįİıĶķĹĺĻļĽľŁłŃńŅņŇňŌōŐőŒœŔŕŖŗŘřŚśŞşŠšŢţŤťŪūŮůŰűŲųŸŹźŻżŽžƒȘșȚțˆˇˉ˘˙˚˛˜˝π–—‘’‚“”„†‡•…‰‹›⁄€₺₽ℓ™Ω℮∂∆∏∑−∕∙√∞∫≈≠≤≥◊ﬁﬂ
```
https://www.dropbox.com/s/acnlji26j5b355e/Screen%20Recording%202019-09-10%20at%2010.24.26.mov?dl=0

The text predictably breaks after `?`, after `²³`, after `₺`, and after `/`.
`?` is a case of “always true”
The `²³` case is the most confusing one, because it’s not clear which character is actually triggering the break.
`¤` also seems to trigger a line break.

**Comment by typemytype** [comment]
the is a coreText line breaking thing...

Ive solved it by converting the text to glyphNames and append them not as text but as a glyphName

```
txt = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklm?nopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"

w, h = 228, 416

size(w*2+30, h+20)

textBox(txt, (10, 10, w, h))



t = FormattedString()
glyphNames = list(txt)
i = glyphNames.index("?")
glyphNames[i] = "question"

t.appendGlyph(*glyphNames)

textBox(t, (20+w, 10, w, h))
```

the funny thing that this problems also occurs in the drawBot editor and this html box in Safari where Im typing in now

![Screen Shot 2019-09-11 at 18 09 55](https://user-images.githubusercontent.com/1190358/64714723-629fe980-d4bf-11e9-9fca-625850d732cc.png)
![Screen Shot 2019-09-11 at 18 10 09](https://user-images.githubusercontent.com/1190358/64714731-66cc0700-d4bf-11e9-9ffa-a8f731b2710a.png)

**Comment by jjgod** [comment]
What platform/CoreText API exactly does drawBot call to handle line breaking though?

**Comment by jjgod** [comment]
Oh, it uses CTFramesetter. I will take a look.

**Comment by jjgod** [comment]
Confirmed this is what ICU returns, you might be able to get different result by customizing the `kCTLanguageAttributeName`.

**Comment by jjgod** [comment]
Or switch the line break mode to `kCTLineBreakByCharWrapping`.

**Comment by typemytype** [comment]
lines are calculated from a frameSetter with `CoreText.CTFrameGetLines(frame)`

see https://github.com/typemytype/drawbot/blob/master/drawBot/context/pdfContext.py#L156

The result will be idd different when a different language is selected (see the [drawBot example](http://www.drawbot.com/content/text/textProperties.html#drawBot.language))

but it should not split randomly on `?` `/` `turkish lira`. A quick test while setting a language, does not change the splitting on-a-questionmark-behaviour.

**Comment by frankrolf** [comment]
FYI: I solved the problem for myself by just adding zero-width spaces among the proof text:
`content = '\u200B'.join(content)  # zw space`
