### ISSUE TITLE
setting font() before newPage()

### ISSUE THREAD

**Issue by jo-lang** [typemytype/drawbot#298]
this is not really a bug but strange nonetheless. 
if ```font``` is called before ```newpage``` there are some strange line breaks.
I am aware that font should be called after newpage and it also works if done in the right order. 

```
import calendar
font("InputMonoCondensed-Regular")

small = 9.25
day_w = small * 2

newPage(200, 200)
fontSize(small  *1.25)

translate(30, height() - 35)

y = 0

days = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']

for d in range(7):
    text(days[d], (d * day_w, y))

y -= small * 4

for d in range(7):
    text(calendar.day_name[d][:2], (d * day_w, y))
```
<img width="344" alt="breaking" src="https://user-images.githubusercontent.com/18583969/65523365-78b09f80-deec-11e9-89aa-5c96bfccb107.png">

**Comment by justvanrossum** [comment]
`newPage()` resets the entire graphics state, I'm surprised you're not getting the default font. Maybe that's the bug then...

**Comment by justvanrossum** [comment]
Using `font()` before the first `newPage()` will now result in seeing the default font on the page, as expected. Resetting the state was indeed incomplete in this case.
