### ISSUE TITLE
Changing values in Variables() sets the cursor in the codeEditor

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#30]
If I type in an EditText or TextEditor in Variables the cursor jumps to the codeEditor.

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/drawbot/commit/c1f583cb98ec4a3bf4b0032a6920d0c58721dcdb

will send a binary soon

**Comment by thomgb** [comment]
This is still not solved.

**Comment by typemytype** [comment]
ow, don't know how this comment ended up in this thread... my mistake

**Comment by typemytype** [comment]
this should fix it https://github.com/typemytype/drawbot/commit/b6ed62cf1f69fdf7e45d21aa806ef8887308852e

binary will follow!
