### ISSUE TITLE
Any way to `pip install` with other project dependencies?

### ISSUE THREAD

**Issue by arrowtype** [typemytype/drawbot#300]
These days, I'm including Drawbot proofs in font projects repos. It's definitely one of the most useful ways to proof fonts (especially variable fonts). I've found that I especially like working with DrawBot when I use it as a module, so I can do most of my coding in my preferred editor, where I work the fastest.

It would be ideal if my repo READMEs could instruct others to make a virtual environment and do a `pip install -r requirements.txt` to get all dependencies, including DrawBot. Instead, I have to point them to this repo's readme and hope others can figure out how to install the DrawBot module in the venv.

Is there a reason DrawBot isn't on PyPI yet? Is it due to it only being available on Mac, or is using it as a module just seen as an edge case, at this point? I'm not trying to complain; I just wanted to understand this better, and couldn't quite find an existing issue around this.

Thanks!

**Comment by justvanrossum** [comment]
I think at some point `pip install .` worked from the drawbot repo root. If not, we need to edit `setup.py` until it does. After that we should indeed look into uploading to pypi.

**Comment by typemytype** [comment]
there is also pip with git support, this should work:

`pip install git+https://github.com/typemytype/drawBot`

**Comment by justvanrossum** [comment]
It doesn't, as setup.py imports drawBot before it is installed:

https://github.com/typemytype/drawbot/blob/1fbc3be69751ba025d93c2f12cd6c15a8d895b1f/setup.py#L7

So `pip install .` fails:

```
    ERROR: Command errored out with exit status 1:
     command: /Users/just/code/git/drawbot/testpip/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-req-build-0x26h8_5/setup.py'"'"'; __file__='"'"'/private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-req-build-0x26h8_5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-req-build-0x26h8_5/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-req-build-0x26h8_5/setup.py", line 7, in <module>
        from drawBot.drawBotSettings import __version__
      File "/private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-req-build-0x26h8_5/drawBot/__init__.py", line 1, in <module>
        from .drawBotDrawingTools import _drawBotDrawingTool
      File "/private/var/folders/r6/16l72gg51gqcwbgpk9gtv0mc0000gn/T/pip-req-build-0x26h8_5/drawBot/drawBotDrawingTools.py", line 1, in <module>
        import AppKit
    ModuleNotFoundError: No module named 'AppKit'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by justvanrossum** [comment]
If that were fixed (I quickly tried by hardcoding `__version__` in setup.py) it fails because it doesn't list any dependencies.

So we have two issues here:
- `__version__` should not be taken from installed drawbot package (perhaps we can copy the fonttools approach)
- setup.py needs to list its dependencies (and only those that it needs to run, not the "optional" ones that are bundled with the app), so it'll be a smaller list than what is listed in `requirements.txt`.

**Comment by typemytype** [comment]
oh yep, let me fix that... it should idd not import but exec the content of the imported file

**Comment by typemytype** [comment]
I guess, the current list of requirements can not really be made smaller

**Comment by justvanrossum** [comment]
As of a few minutes ago, you can do:

`pip install git+https://github.com/typemytype/drawbot`

Yay!! Thanks @typemytype.

**Comment by justvanrossum** [comment]
Next up: proper upload to PyPI, but that may take a bit longer.

**Comment by roberto-arista** [comment]
🤩

**Comment by arrowtype** [comment]
`pip install git+https://github.com/typemytype/drawbot` seems to work great!

Awesome. :) Thank you!
