### ISSUE TITLE
listNamedInstances' is not defined

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#306]
When I try to use `listNamedInstances()` as indicated in the docs I get `NameError: name 'listNamedInstances' is not defined`

Any help? I’m using the last DrawBot Version 3.120 (3.120) and I tested with Skia font.

**Comment by justvanrossum** [comment]
It seems that function is indeed not yet in the current release.

**Comment by guidoferreyra** [comment]
Just seen there is a new released version. listNamedInstances was in the docs before the release :)

**Comment by typemytype** [comment]
Ive setup read the docs now differently: in the future it will take the latest stable tagged release for the docs.

This allows drawBot to make changes into the master without modifying the documentation of the release version

enjoy `listNamesInstances`!!!

**Comment by guidoferreyra** [comment]
Thanks a lot!
