### ISSUE TITLE
QTKit not available anymore on 10.15

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#312]
```
/drawBot/context/movContext.py", line 2, in <module>
    import QTKit
ModuleNotFoundError: No module named 'QTKit'
```

I would even opt to deprecate mov totally

**Comment by typemytype** [comment]
also see https://developer.apple.com/documentation/qtkit

**Comment by justvanrossum** [comment]
`.mov` is already deprecated with a nice warning, but perhaps we need a better error message on 10.15.

**Comment by typemytype** [comment]
Its seems like on `pyobjc 7` there is no QTKit anymore

this ends up into a `RunTimeError` instead of an `ImportError`

![image](https://user-images.githubusercontent.com/1190358/104812050-d793d980-57ff-11eb-95fa-75b9197071eb.png)

I vote for a complete removal of QTKit and mov support...

**Comment by benkiel** [comment]
Sad that we loose frameDuration in mp4s

**Comment by justvanrossum** [comment]
> Sad that we loose frameDuration in mp4s

It's possible to add .mov support via AVFoundation (#47), but I personally have no incentive for this.

Either way, closing this, as QTKit's days are definitely over since 1fdfe14dd7d7e287c846f59c50f6854bbb3cd0e6

**Comment by typemytype** [comment]
related to `frameDuration`: this still works, only it has to be the same for every frame/page, if its not the same DB will pick the first one, and show a warning

see https://github.com/typemytype/drawbot/blob/master/drawBot/context/mp4Context.py#L44-L46
