### ISSUE TITLE
ScreenSize as papersize

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#32]
You have a nice collection of pre-programmed paper sizes.
I use pretty often the size of my screen. Like so:
size(AppKit.NSScreen.mainScreen().frame().size.width, AppKit.NSScreen.mainScreen().frame().size.height)
Wouldn't it be nice to pre-program this into: size("screen")?

:)

Can AppKit handle multiple screens?

**Comment by justvanrossum** [comment]
NSScreen.screens is a list of screens, so yes :) I've never had the need to create a canvas the size of my screen, though.

**Comment by typemytype** [comment]
what would happen with multiple screens? take the mainScreen?

**Comment by thomgb** [comment]
Take the screen in which Drawbot is :)

**Comment by karstenw** [comment]
Make it twofold:

```Python
size( getscreens()[getdrawbotscreen()] )
````
where getscreens() returns a list of size tuples and getdrawbotscreen() returns the index where the frontmost of drawbot windows is on.

For getdrawbotscreen() to decide on screen overlapping windows to check which screen the midpoint of the content area resides on.

Perhaps size() needs to be adapted to accept tuples.

**Comment by typemytype** [comment]
added https://github.com/typemytype/drawbot/commit/0cf3e02efa44a0e918ef316d4da6266581ed7dfa

`size("screen")` will take the main screen size

**Comment by thomgb** [comment]
awesome! thnx
