### ISSUE TITLE
We should invent a way to integrate pip

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#322]
So it becomes real easy to install third party packages, so we have to bundle less. See for example #321.

**Comment by anthrotype** [comment]
note that pip explicitly doesn't support a programmatic API. They recommend to call it as a subprocess, since it messes with global state.

**Comment by justvanrossum** [comment]
Yeah. We pretty much need a location for `--target`.

**Comment by typemytype** [comment]
a fix for uninstalling a package (pip does not accept a path to a specific package) is to run `pip show <package>` first and check if the location contains the  `~/Library/Application Support/DrawBot/` path

**Comment by justvanrossum** [comment]
Implemented via cdcb4ca321cdefc0970ccf7bcbf5148f304f8351 (#324)
