### ISSUE TITLE
Problem drawing FormattedString

### ISSUE THREAD

**Issue by andyclymer** [typemytype/drawbot#337]
With this code:

``` python
fs = FormattedString("A\n")
text(fs, (0, 0))
```

I get a traceback on this line:

https://github.com/typemytype/drawbot/blob/04096d968b9522702fa7010096e49206c140ff36/drawBot/context/baseContext.py#L907

```
Traceback (most recent call last):
  File "<untitled>", line 5, in <module>
  File "drawBot/drawBotDrawingTools.pyc", line 1607, in text
  File "drawBot/context/baseContext.pyc", line 906, in makeTextBoxes
AttributeError: 'NSConcreteAttributedString' object has no attribute 'deleteCharactersInRange_'
```

It looks like the FormattedString should be a NSMutableAttributedString but instead it's a NSConcreteAttributedString? However I can't tell how this might have happened.

**Comment by justvanrossum** [comment]
Good catch, thanks! Fixed in #338.

**Comment by typemytype** [comment]
this is still raising an error:

```
fs = FormattedString("A\n\n")
text(fs, (0, 0))
```

**Comment by justvanrossum** [comment]
Very different error, though.

**Comment by typemytype** [comment]
no, the `length` is modified, and that should not happen, or we should ask for the `para` before changing the `rng`

**Comment by justvanrossum** [comment]
I think the para fails because the effective string at that point is empty.

**Comment by justvanrossum** [comment]
The main problem I see right now is that

```python
    width, height = attributedSubstring.size()
```

gives the wrong height for an empty string.

**Comment by andyclymer** [comment]
(Thank you so much for looking into this!)
