### ISSUE TITLE
Updater may be lying sometimes

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#342]
Whenever the current version number cannot be retrieved for some reason, there will be a message proudly proclaiming "You have the latest version!", which is then very unlikely to be the truth... See #341.

**Comment by typemytype** [comment]
when it fails to retrieve the version from the repo the fallback version is "0.0". [see](https://github.com/typemytype/drawbot/blob/master/drawBot/updater.py#L39-L40)

This means the prefs shows this message when no update is needed [see](https://github.com/typemytype/drawbot/blob/master/drawBot/ui/preferencesController.py#L391)

The pref callback should check if the currentVersion is not the fallback version.

will make an PR
