### ISSUE TITLE
viewBox for svg

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#347]
see https://forum.drawbot.com/topic/225/svg-attributes-viewbox

proposal: ˋsaveImage(svgPath, viewBox=(x, y, w, h))ˋ

as and extra arg while saving a svg, the viewBox can be different from the width and height of the document.

**Comment by justvanrossum** [comment]
What is the use case for the viewBox not being the same as (width, height)? That doesn't follow for me from the forum post.

**Comment by typemytype** [comment]
Googled a nice  write up: https://www.sarasoueidan.com/blog/svg-coordinate-systems/

Maybe the fallback/default should keep the same dimensions as width height

**Comment by justvanrossum** [comment]
My question is not how/why it can be different, but why in DrawBot would you _want_ them to be different. I see no such question in the forum post, only that a missing viewBox is a problem.

So I suggest to add `viewBox="0 0 <width> <height>"`, and I think that would solve the problem perfectly.

**Comment by typemytype** [comment]
the question on the forum is idd a request to add a viewBox

I guess its handy to have a setting for svg: as this is very similar to dpi for images

**Comment by justvanrossum** [comment]
Please keep things simple, and don't add features we're not quite sure are actually needed.

**Comment by typemytype** [comment]
oke makes sense
