### ISSUE TITLE
most of the bezierPath attributes are immutable

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#349]
make it more clear in the docs that the list of `onCurvePoints` is immutable

**Comment by justvanrossum** [comment]
Make it also more clear that these attrs are only useful for visualizing points, as they lack structural info about sub paths.

**Comment by typemytype** [comment]
done https://github.com/typemytype/drawbot/commit/3db198752c7dc3099aac2f8cdec13cac3aec6836
