### ISSUE TITLE
bez.traceImage() doesn't work on 10.15

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#358]
`OSError: [Errno 86] Bad CPU type in executable: '/Users/just/code/git/drawbot/dist/DrawBot.app/Contents/Resources/mkbitmap'`

**Comment by typemytype** [comment]
those binaries are coming from http://potrace.sourceforge.net

**Comment by typemytype** [comment]
drawBot has version `mkbitmap 1.11` (made in 2013...) the latest one is `mkbitmap 1.16`

will test if this works on 10.15 and update

**Comment by typemytype** [comment]
this should be fixed...
