### ISSUE TITLE
Turning Kerning off

### ISSUE THREAD

**Issue by colinmford** [typemytype/drawbot#371]
Hi guys!

I was wondering if there is a method for turning kerning *off?* It seems to be on by default all the time (which usually is a good thing!) but sometimes I want to have control over whether it is on or off.

The following code still results in a string with kerning on, when I would expect it to be off:
```python
import drawBot as db

db.newPage(500,100)
s = db.FormattedString("AVAVATo",
    font="SourceSerifPro-Bold.otf",
    fontSize=100,
    openTypeFeatures={"kern": False}
)

db.text(s, (20,20))
```

Result:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/671409/78583843-5be31600-7805-11ea-8b76-e1f5994347ff.png">

Expected (shown in FontGoggles):
<img width="711" alt="image" src="https://user-images.githubusercontent.com/671409/78583807-51c11780-7805-11ea-84de-c1037fcf0984.png">

[DrawBot Error.zip](https://github.com/typemytype/drawbot/files/4439743/DrawBot.Error.zip)

Is there another method I should be using?

Thanks!

**Comment by justvanrossum** [comment]
You're doing everything right and this must be a bug: I can confirm that turning kerning of this way does not work (but should).

**Comment by colinmford** [comment]
Thanks, @justvanrossum! Glad I'm not just missing something. For the time being I've had to resort to ripping the kerns out of the font file using FontTools, it would be nicer if it could be easier than that... though I know with this Quartz stuff it's rarely easy.

**Comment by justvanrossum** [comment]
It may be a shallow bug in DrawBot, but I haven't yet had the opportunity to dig in.

**Comment by justvanrossum** [comment]
Here's a workaround:

```python
import CoreText

f = FormattedString()
f.font("ACaslonPro-Regular")
f.fontSize(100)
# f.tracking(10)  # no effect when turning off kerning as below
f.append("ToT,")

a = f._attributedString
a.addAttribute_value_range_(CoreText.kCTKernAttributeName, 0, (0, len(f)))

text(f, (100, 100))
```

But this disables tracking... (Probably related to https://github.com/typemytype/drawbot/issues/366#issuecomment-605734208)

**Comment by colinmford** [comment]
@justvanrossum Thanks for the work-around! Bummer about the tracking, but it might work in my situation as it rarely has tracking involved.

**Comment by typemytype** [comment]
cause https://developer.apple.com/documentation/uikit/nskernattributename?language=objc

and in DB the if statement must be `if self._tracking is not None:`

https://github.com/typemytype/drawbot/blob/master/drawBot/context/baseContext.py#L1308-L1309

but maybe tracking should be set by: https://developer.apple.com/documentation/coretext/kcttrackingattributename?language=objc

**Comment by colinmford** [comment]
Thanks @typemytype & @justvanrossum !
