### ISSUE TITLE
image("some.pdf", (offsetx,offsety))

### ISSUE THREAD

**Issue by thomgb** [typemytype/drawbot#38]
A pdf ignores the offset. It will be displayed as (0,0).

**Comment by justvanrossum** [comment]
Fixed in https://github.com/typemytype/drawbot/commit/785badef3b34776a4058bfddd5b342e663f8a0bb.

**Comment by justvanrossum** [comment]
Fixed in https://github.com/typemytype/drawbot/commit/a57296f.

**Comment by typemytype** [comment]
a new binary is uploaded
