### ISSUE TITLE
weird behaviour when using drawBot as a module

### ISSUE THREAD

**Issue by jansindl3r** [typemytype/drawbot#386]
I have done this [thing](https://gist.github.com/jansindl3r/fda2020bdfdbdaaec5addd6e257ed140 ) that helps to track progress in my fonts. It works fine when used directly from DrawBot extension in RoboFont. When I open it in robofont directly and import DrawBot as a module, it doesn't work as expected. When I change `scaleRatio` it doesn't export updated `.pdf`. What is interesting is, if I keep saving it under same name, the size increases but the content doesn't change. Even though the `.pdf` file is removed., then it creates a new file and kind of continues in increasing the file size and still having the same content.

**Comment by typemytype** [comment]
There is one stack where multiple scripts could add drawing instructions. If you wish to start with a clean stack you need to wrap your code with: `newDrawing` [see docs](https://www.drawbot.com/content/canvas/pages.html#drawBot.newDrawing).

```python
import drawBot

drawBot.newDrawing()
drawBot.endDrawing()
```

**Comment by jansindl3r** [comment]
alright, that's clever. Didn't know about this, thanks!
