### ISSUE TITLE
tailIndent docs

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#388]
👋

It took me a while to understand that tailIndent() needs a negative value to work as expected. Shouldn't it be mentioned in the specs?

**Comment by typemytype** [comment]
Could also be positive: as a absolute **width**  of the paragraph. This can even exceeds the bounds of a text box.

When the value is negative its calculated from the bounds of the text box.
  
read here https://developer.apple.com/documentation/uikit/nsparagraphstyle/1525556-tailindent?language=objc

**Comment by typemytype** [comment]
but +1 for clarifying this in the docs!

**Comment by roberto-arista** [comment]
💫
