### ISSUE TITLE
Switch between open windows

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#39]
In OS X apps you can switch between the open windows with the shortcut  cmd + `.  This doesn't work on Drawbot, I think it's very handy shortcut.

**Comment by justvanrossum** [comment]
Weird, that shortcut works fine for me, I use it all the time.

**Comment by typemytype** [comment]
I see, same here

**Comment by guidoferreyra** [comment]
@typemytype do you have the same issue or works fine for you? For me doesn't work in any of my computers. My keyboard is in spanish maybe this is related...

**Comment by typemytype** [comment]
it doesn't work here
weird cause in my other apps it works just fine...

**Comment by typemytype** [comment]
it seems like the pdfView is catching this shortcut but doest doe anything...

it works if you collapse both the pdf view as the thumbnail view

**Comment by guidoferreyra** [comment]
True.

**Comment by typemytype** [comment]
I guess this will fix it https://github.com/typemytype/drawbot/commit/252957e3fac95b9a6abd6a20458c9a1a45394488

this is actually a bug in Quartz.PDFView

**Comment by typemytype** [comment]
just uploaded a new binary, could you test it out and report

thanks!

**Comment by guidoferreyra** [comment]
Yes of course but i don't know how to update my app. Should I download the repo and compile the app? I don't know how to do that.

**Comment by typemytype** [comment]
I uploaded a binary (3.75)
go to http://www.drawbot.com/content/download.html
or in the DrawBot prefs check now for updates

**Comment by guidoferreyra** [comment]
ohh oh, sorry for such dumb question.
I tested but is not working for me :(

**Comment by typemytype** [comment]
and in Console.app there is DrawBot still throws an Range or index out of bounds error?

**Comment by typemytype** [comment]
and you are sure you have version 3.75?

**Comment by guidoferreyra** [comment]
Yes, still throwing "Range or index out of bounds"
Im on Version 3.75 (3.75)

**Comment by typemytype** [comment]
could you try downloading it again? will be still 3.75

fixed it differently, cause keyboard can look differently... sight 
https://github.com/typemytype/drawbot/commit/c46603d9c16785e0920b9fcc600a8fd60953ef17

**Comment by guidoferreyra** [comment]
IT WORKS! :)

**Comment by typemytype** [comment]
super, thanks!
