### ISSUE TITLE
strange text opacity display bug

### ISSUE THREAD

**Issue by gferreira** [typemytype/drawbot#395]
- same fill with transparency
- glyphs on the left are drawn with `text`, glyphs on the right with `BezierPath.text`
- display bug (left): transparency is not displayed

![Screen Shot 2020-07-17 at 05 07 43](https://user-images.githubusercontent.com/62717/87763712-963c5600-c7eb-11ea-9128-adb14bae1bd5.png)

DrawBot 3.126 + macOS 10.13

thanks!

**Comment by justvanrossum** [comment]
Please also paste the code as text, then I don't have to retype it...

**Comment by gferreira** [comment]
here it is:

```python
fontSize(500)
fill(0, 0.2)
translate(100, 300)

for char in 'abcdefg':
    text(char, (0, 0))
    
for char in 'abcdefg':
    B = BezierPath()
    B.text(char, (700, 0), align='right', fontSize=500)
    drawPath(B)
```

groeten!

**Comment by gferreira** [comment]
ps. if you scale the PDF preview to a very small size, the transparency finally appears on the left side:

![Screen Shot 2020-07-17 at 13 48 56](https://user-images.githubusercontent.com/62717/87811035-5c437200-c834-11ea-809b-270c98f1198f.png)

**Comment by justvanrossum** [comment]
Thanks!

I can reproduce on 10.10, but not on 10.15, so it's possibly an os bug on earlier os-es. Unless we have some conditional code that's buggy. This needs to be checked.

**Comment by justvanrossum** [comment]
It seems to be an optimization where even though the characters are drawn individually, they are drawn as it they're one string. Compare for example a string with negative tracking so the glyphs overlap. Also compare when drawing something else (for example `rect(0, 0, 10, 10)`) after each character: then this optimization also doesn't happen.

**Comment by gferreira** [comment]
thanks for checking – what a nice little bug…

it’s easy to work around it, and it’s gone on later macOS, so I guess we can live with it. at least it’s documented here now :)
