### ISSUE TITLE
PDF header

### ISSUE THREAD

**Issue by michielkauwatjoe** [typemytype/drawbot#40]
when importing DrawBot and generating a PDF, I'm getting an error after an update;

`failed to find PDF header: `%PDF' not found.`

as a warning, but second PDF won't build with this error:

`It is advised to use 'size()' at the top of a script`

Is this a new issue or am I doing something wrong?

**Comment by justvanrossum** [comment]
Not sure what you mean. Example code?

**Comment by michielkauwatjoe** [comment]
Sorry, I'll try to explain: the following fails after first saveImage it seems, before it didn't have a problem with multiple runs.

import drawBot

drawBot.size('A3Landscape')
for ...
    drawBot.newDrawing()
    for ...
        drawBot.newPage(self.w, self.h)
        ... do stuff
    drawBot.saveImage(path-to-pdf)

**Comment by justvanrossum** [comment]
Still can't reproduce...
```python
import drawBot

drawBot.size('A3Landscape')
for i in range(2):
    drawBot.newDrawing()
    for j in range(2):
        drawBot.newPage(500, 500)
        rect(10, 10, 200, 200)
    drawBot.saveImage("PDF-issue-40-%s.pdf" % i)
```

**Comment by justvanrossum** [comment]
But something has changed with size() and newPage() indeed: you can't call size() after you've already drawn things, or call size() twice. Same for newPage(). So maybe that's it?

**Comment by michielkauwatjoe** [comment]
Thanks, the example works. Is there a way to reset the context or clear drawBot after saving the PDF? Size needs to be set once before I run my export routines but needs to be different from time to time...

**Comment by justvanrossum** [comment]
newDrawing() should do that. (In the example the first size() does nothing, as newDrawing() resets everything.)

I'm stil interested in your non-working example, as that PDF warning sounds suspicious.

**Comment by michielkauwatjoe** [comment]
Right, so I probably switched newDrawing() and size(). Here's the relevant code I think:

```
import drawBot
import datetime
import traceback
from wayfinding.objects.destination import Destination
from wayfinding.objects.directionsign import DirectionSign
from wayfinding.objects.identificationsign import IdentificationSign
from wayfinding.objects.customsign import CustomSign
from wayfinding.mathandlogic import MathAndLogic

class Export(object):
    u"""
    Exports data to PDF.
    """
    ratio = None
    w = None
    h = None
    x0 = None
    y0 = None
    wImage = None
    wmm = None
    paperSize = None
    fonts = {'bold': 'CorpidC3-Bold', 'regular': 'CorpidC3-Regular'}

    def export(self, **kwargs):
        p = self.currentProject

        if kwargs['exportType'] == 'signContents':
            drawBot.size('A4')
            self.w = drawBot.width()
            self.h = drawBot.height()
            self.wmm = 210
            self.hmm = 297
            self.x0 = 55
            self.y0 = 100
            self.paperSize = 'A4'
        else:
            drawBot.size('A3Landscape')
            self.w = drawBot.width() # A3 width in pixels.
            self.h = drawBot.height()
            self.wmm = 420           # A3 width in millimeters.
            self.wImage = 950        # Blueprint width in pixels
            self.x0 = 55
            self.y0 = 100
            self.paperSize = 'A3'

            # Image ratio to scale down.
            self.ratio = float(self.wImage) / p.width

        self.checkFonts()

        if kwargs['exportType'] in ['currentView', 'signPlanOverview', 'destinationOverview']:
            self.exportDocument(**kwargs)
            ...

    def exportDocument(self, **kwargs):
        u"""
        Exports a single document.
        """
        p = self.currentProject
        floors = self.getExportFloors(p, kwargs['exportIsAllFloors'],
                                        kwargs['exportIsFloorRange'],
                                        kwargs['exportFloorRange'])

        drawBot.newDrawing()

        # Page for each floor.
        for floorNumber in floors:
            self.labelPositions = []
            floor = self.getFloor(floorNumber=floorNumber)
            exportObjects = self.getExportObjects(floor, kwargs['exportType'])
            MathAndLogic.setIntersections(floor)

            drawBot.newPage(self.w, self.h)
            self.exportBlueprint(p, floorNumber, kwargs['exportSize'])
            self.exportTitle(kwargs['exportType'])
            self.exportDestinations(floor, exportObjects['destinations'])
            self.exportDecisionAreas(floor, exportObjects['decisionAreas'])
            self.exportFlows(floor, exportObjects['flows'])
            self.exportSignGroups(floor, exportObjects['signGroups'])
            self.exportLabels(floor, exportObjects, kwargs['exportType'])
            self.exportMetadata(floor, exportIsConcept=kwargs['exportIsConcept'],
                                    exportType=kwargs['exportType'],
                                    exportComments=kwargs['exportComments'])
            self.exportScale(floor)
            self.exportCompass()
            self.exportFooter(floor, kwargs['exportIsConcept'])

        drawBot.saveImage("%s%s-%s.pdf" % (p.exportPath, kwargs['exportType'], self.joinFloors(floors)))
```

**Comment by justvanrossum** [comment]
If you could reduce that to a snippet we can just run, that would be great :)

**Comment by typemytype** [comment]
using `size()` in a multi page document is not advised.
`size()` actually exists for historical reasons

its advised to use:

```Python
newDrawing() # initiate a clear document

newPage(w, h) # add a page
# draw stuff
```

to know width, height of predefined sizes before you draw or setup a document use: `sizes("A4")` this returns a width, height tuple.

**Comment by michielkauwatjoe** [comment]
I'm setting size after newDrawing and the second error (warning) has disappeared, still get the first one however. Might be a mistake on my side, I'll do some testing. If I stil yet the header error I'll send you a snippet. Also I'll start using newPage(), thanks!

**Comment by michielkauwatjoe** [comment]
The PDF header error seems to occur when loading an image; tested with both png and tif files. Here's the example:

[issue.py.zip](https://github.com/typemytype/drawbot/files/124455/issue.py.zip)

**Comment by justvanrossum** [comment]
Ok, I see the warning now. It also happens when just running in DrawBot, but the msg gets sent to the low level stderr, so it gets hidden there. The warning is not written by DrawBot but by the OS.

**Comment by justvanrossum** [comment]
Ah, I have a suspicion what causes it: when placing and image, DrawBot tests to see whether it may be PDF data by attempting to instantiate a PDFDocument. If that fails, it's not PDF. I'm pretty sure that causes the warning. Frederik: should we revert to checking the file extension?

**Comment by michielkauwatjoe** [comment]
Yes, it seems to be an Objective C error that happens when opening a PDF. The funny thing is the output is fine.

**Comment by typemytype** [comment]
the `isPDF`check could also look for the ext and eliminate those directly

```Python
def isPDF(path):
    if os.path.splitext(path)[-1].lower() != ".pdf":
        return False
    url = AppKit.NSURL.fileURLWithPath_(path)
    return AppKit.PDFDocument.alloc().initWithURL_(url) is not None
```

**Comment by justvanrossum** [comment]
Or maybe (inspired by the actual issue here...):
```python
def isPDF(path):
    return open(path).read(4) == "%PDF"
```

**Comment by typemytype** [comment]
yeah, what if the path is a URL?


gr Frederik
www.typemytype.com

**Comment by typemytype** [comment]
NSData could be used

```Python
def isPDF(path):
    url = AppKit.NSURL.fileURLWithPath_(path)
    data = AppKit.NSData.dataWithContentsOfURL_(url)
    if data is None:
        return False
    if data.getBytes_range_(None, (0, 4)) != "%PDF":
        return False
    return AppKit.PDFDocument.alloc().initWithURL_(url) is not None
```

**Comment by justvanrossum** [comment]
Hm, but that's very wasteful if the file isn't a PDF, unless we can write it in a way that the data is only fetched once, regardless of image type. If that's hard: let's stick to file extensions.

**Comment by michielkauwatjoe** [comment]
Getting a traceback when loading an image, seems to be related to this issue:

Traceback (most recent call last):
  File "vanilla/vanillaBase.pyc", line 204, in action_
  File "Callbacks.pyc", line 791, in exportOkayCallback
  File "Export.pyc", line 43, in export
  File "Export.pyc", line 116, in exportDocument
  File "/Users/michiel/source/git/WayFinding/WayFindingApp/dist/WayFinding.app/Contents/Resources/lib/python2.7/drawBot/drawBotDrawingTools.py", line 293, in saveImage
    self._drawInContext(context)
  File "/Users/michiel/source/git/WayFinding/WayFindingApp/dist/WayFinding.app/Contents/Resources/lib/python2.7/drawBot/drawBotDrawingTools.py", line 100, in _drawInContext
    attr(*args, **kwargs)
  File "/Users/michiel/source/git/WayFinding/WayFindingApp/dist/WayFinding.app/Contents/Resources/lib/python2.7/drawBot/context/baseContext.py", line 1556, in image
    self._image(path, (x, y), alpha, pageNumber)
  File "/Users/michiel/source/git/WayFinding/WayFindingApp/dist/WayFinding.app/Contents/Resources/lib/python2.7/drawBot/context/pdfContext.py", line 235, in _image
    _isPDF, image = self._getImageSource(path, pageNumber)
  File "/Users/michiel/source/git/WayFinding/WayFindingApp/dist/WayFinding.app/Contents/Resources/lib/python2.7/drawBot/context/pdfContext.py", line 213, in _getImageSource
    _isPDF, _ = isPDF(url)
TypeError: 'bool' object is not iterable

**Comment by typemytype** [comment]
Strange I cannot find what I missed while adding the function `isPDF` and renaming the bools to `_isPDF` see https://github.com/typemytype/drawbot/commit/29cd60c8c92471bc88edc0c7122c88de487674c4

are you sure you have to the latest version? and reinstalled is as module?

**Comment by michielkauwatjoe** [comment]
Yes it's updated to the latest version. I'm softlinking to the module from site-packages, could that be the problem?

**Comment by michielkauwatjoe** [comment]
Sorry, I meant linking through a pth file, not a softlink.

**Comment by typemytype** [comment]
oh, my bad, should return a tuple

fixed https://github.com/typemytype/drawbot/commit/e6fb85827999fe4fa34208a0d396da434e8dba1e

should work in 3.77

thanks

**Comment by michielkauwatjoe** [comment]
Great, drawing an image working again and the error is gone. Thanks for fixing!
