### ISSUE TITLE
fontContainsCharacters() return not supported characters 

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#405]
Hi! I think it will be nice feature if fontContainsCharacters() will return a list of the unsupported characters.

**Comment by gferreira** [comment]
hello @guidoferreyra,

you can get the missing characters in one line using a list comprehension:

```python
[char for char in txt if not fontContainsCharacters(char)]
```

changing the function’s return value would break existing scripts…

**Comment by guidoferreyra** [comment]
Hi Gustavo
> you can get the missing characters in one line using a list comprehension:

Great didn’t think about that! Thanks a lot!

> changing the function’s return value would break existing scripts…

Yes, after I made the issue I was thinking on that.

Thanks again
