### ISSUE TITLE
Random DrawBot crashes.

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#41]
Usually after closing a DB window and creating a new one. Happens quite a lot, at least on 10.10.2.

**Comment by justvanrossum** [comment]
[DrawBotCrash.txt](https://github.com/typemytype/drawbot/files/139813/DrawBotCrash.txt)

**Comment by typemytype** [comment]
I not able to reproduce it...

**Comment by justvanrossum** [comment]
I know, it happens pretty randomly, but it does happen (to me) regularly. Twice today alone. Can you make sense of the crash report?
