### ISSUE TITLE
DNS error for drawbot.com

### ISSUE THREAD

**Issue by justinpenner** [typemytype/drawbot#416]
[drawbot.com](http://drawbot.com) does not resolve, while [www.drawbot.com](http://www.drawbot.com) does.

This looks like a repeat of an issue from 2017 that was marked as resolved: https://github.com/typemytype/drawbot/issues/90

**Comment by typemytype** [comment]
this should be fixed...

**Comment by justinpenner** [comment]
Both URLs appear to be working now. Thanks!

**Comment by typemytype** [comment]
Thanks!
