### ISSUE TITLE
shadow() parameters don't respond to current transformation

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#42]
This may be a Quartz thing and unsolvable, but it's a little surprising if you're scaling an entire image.

**Comment by typemytype** [comment]
see https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGContext/index.html#//apple_ref/c/func/CGContextSetShadowWithColor

    offset	Specifies a translation in base-space.

**Comment by justvanrossum** [comment]
Then we should probably document that, too. The blur radius, too, btw.

**Comment by typemytype** [comment]
almost done :)

how should the blur be scaled?

Im able to extract the current transformation matrix from the context and get the scale value. The offset is easy to scale with the extracted scaleX and scaleY. The blur is one value: the average of scaleX, scaleY?

**Comment by typemytype** [comment]
to extract transformation matrix from a context https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGContext/index.html#//apple_ref/c/func/CGContextGetUserSpaceToDeviceSpaceTransform

**Comment by justvanrossum** [comment]
I'm not sure :( But scaleX and scaleY are not enough, as that would fail for rotations.

**Comment by typemytype** [comment]
should be fixed in https://github.com/typemytype/drawbot/commit/0cea3144ec8842417290f0e8373e14692502bdfb

**Comment by justvanrossum** [comment]
You're just scaling the offset instead of transforming it completely, that can't be correct.

**Comment by justvanrossum** [comment]
Let's not forget this. As it is now, it shouldn't end up into a release.

**Comment by typemytype** [comment]
I know ;)

I will remove the fake scaling of offset and blur
And just add it to the docs that those values are context  transformation
independent

On Saturday, 27 February 2016, Just van Rossum <notifications@github.com>
wrote:

> Let's not forget this. As it is now, it shouldn't end up into a release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typemytype/drawbot/issues/42#issuecomment-189600319>.
>


-- 
gr Frederik
www.typemytype.com

**Comment by typemytype** [comment]
solved by adding a line to the docs about the shadow offset and blur base-space
