### ISSUE TITLE
Image cache should ideally be invalidated if the source image changed.

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#43]

**Comment by typemytype** [comment]
see https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/

**Comment by justvanrossum** [comment]
Or do an os.stat() if DB has been reactivated. Low priority, but I don't want this to get lost.

**Comment by typemytype** [comment]
a dumb solution but at least the cache is gone after you come back to DrawBot  https://github.com/typemytype/drawbot/commit/b3493259150c1d068618c6dc844c2b8ec8f7d580
