### ISSUE TITLE
incorrect path.bounds (?)

### ISSUE THREAD

**Issue by slobzheninov** [typemytype/drawbot#434]
Hello!
I was trying to get bounds of a path (made of path.text), but its width and height seem to be incorrect. On the screenshots, the S is path and the grey area is its bounds:

![image](https://user-images.githubusercontent.com/60325634/128941838-6c981b2c-3dec-4f83-b65e-7b2b670336ed.png)

translating the path changes the bounds’s width and height:

![image](https://user-images.githubusercontent.com/60325634/128942033-e5c46365-e686-4b08-b9e1-ca3d1ccf8b6c.png)

Am I misunderstanding something or is it a bug?
Thanks!

**Comment by justvanrossum** [comment]
The returned tuple is `(xmin, ymin, xmax, ymax)`, sounds like you interpret it as `(x, y, width, height)`.

(I see this is not documented clearly: we should improve that.)

**Comment by slobzheninov** [comment]
Thank you, yes I thought it was width and height indeed!
