### ISSUE TITLE
UI Idea: a "Prettify Source" menu

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#437]
Or how to call it. "Beautify"? "Reformat"?

It should be easy to implement with https://pypi.org/project/black/

**Comment by justvanrossum** [comment]
(This is not my idea, but is a question from a student, and I think it's a good one.)

**Comment by typemytype** [comment]
+1 to make code more readable :)

PEP 8 refers to *Style Guide* so maybe 

* Code/Source Styling
* Clean Up Code/Source
* Optimise Code/Source

**Comment by justvanrossum** [comment]
"Clean up code" is my favorite among those three. I find "Format code" also an option.
