### ISSUE TITLE
VScode IntelliSense doesn't work in the suggested examples.

### ISSUE THREAD

**Issue by setanarut** [typemytype/drawbot#440]
VScode IntelliSense doesn't work that way. (official example)

```python
import drawBot

drawBot.newDrawing()
drawBot.newPage(1000, 1000)
drawBot.rect(10, 10, 100, 100)
drawBot.saveImage("~/Desktop/aRect.png")
drawBot.endDrawing()
```
VScode IntelliSense works that way. Would using it this way cause a problem? I'm not an expert, just wondering.
<img width="888" alt="Ekran Resmi 2021-10-18 21 18 31" src="https://user-images.githubusercontent.com/36481442/137786859-680b14a1-221a-4d16-b291-89fe96d45a18.png">

**Comment by hazarek** [comment]
Oh you mean, if you don't use _drawBotDrawingTool as db but plain import drawBot as db. Right?

yes.

**Comment by justvanrossum** [comment]
"no" as in "VS doesn't pick it it", or "no" to "Can you try"?

**Comment by hazarek** [comment]
> "no" as in "VS doesn't pick it up", or "no" to "Can you try"?

VS doesn't pick it up

**Comment by roberto-arista** [comment]
👋

I am using VSCode quite often with `drawBot`, I'll try to get a look into this!

**Comment by bennettzug** [comment]
@roberto-arista did you ever look into this? No worries if not, just don't want to start digging into something if you've already done a bunch of work towards it.

**Comment by roberto-arista** [comment]
hey @bennettzug! not really, I am working in VSCode mostly using the import suggested above
`from drawBot import _drawBotDrawingTool as db`
and I find it quite ok
