### ISSUE TITLE
stroke(None) renders differently from stroke(0, 0, 0, 0)

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#448]
Dear @justvanrossum and @typemytype,

I assumed that `stroke(None)` and `stroke(0, 0, 0, 0)` would render the same result, but if I run this script:

```python
newPage(50, 50)
fontSize(12)

stroke(None)
fill(1, 0, 0, 1)
text("Stroke", (5, 10))

stroke(0, 0, 0, 0)
fill(1, 0, 0, 1)
text("Stroke", (5, 25))

saveImage('stroke.png')
```

The results on a output PNG are slightly different:

![stroke](https://user-images.githubusercontent.com/2218712/143596615-beb8d64a-2cc9-40da-a1b4-06b4fa7454b2.png)

Am I missing something?
I know it's a minor thing, but I am curious 🤓

Thanks!
👋

**Comment by justvanrossum** [comment]
`stroke(None)` and `stroke()` are equivalent and draw no stroke, `stroke(0, 0, 0, 0)` draws a black stroke with 0 alpha. Apparently the OS renderer treats that as different. I'm not quite surprosed, though. Please use `stroke(None)` to say "no stroke".

**Comment by roberto-arista** [comment]
I will, thanks : )
