### ISSUE TITLE
Stroke color for text follows fill color, happily ignores custom color.

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#45]
I noticed that text can no longer be stroked in a custom color:

```
newPage(1000, 1000)
fill(0.5)
stroke(1,0,1)
strokeWidth(100)
fontSize(666)
font("HelveticaNeue-Bold")

text('HA', (20, 20))
rect(600, 700, 200, 200)
```

Expected: 
Text has pink stroke

What is actually happening:
Text has grey stroke (same as fill color)

**Comment by justvanrossum** [comment]
Works correctly for me from git version on 10.10.

**Comment by frankrolf** [comment]
All right, this comment was for the official, pre-compiled Version 3.78 (3.78).
I will try and build DrawBot from source, and report back after.

**Comment by justvanrossum** [comment]
Release 3.78 also works correctly on 10.10.2 :( So yes, probably the 10.11.3 info matters...

**Comment by justvanrossum** [comment]
Confirmed under 10.11.

**Comment by justvanrossum** [comment]
Again confirmed, any news on this? I have no idea where to look. @aaronbell

**Comment by frankrolf** [comment]
This problem persists on 10.12, DrawBot Version 3.85

**Comment by typemytype** [comment]
arglll, please report back to Apple 

it seems like they messed up somehow with injecting swift 

https://developer.apple.com/library/content/releasenotes/General/APIDiffsMacOSX10_11/Swift/CoreGraphics.html

seems also an issue on iOS
http://stackoverflow.com/a/19482471

probably the var `Quartz.kCGTextFillStroke` is not set correctly or mapped to a fill and stroke

**Comment by justvanrossum** [comment]
That stackoverflow article describes a good workaround, though. We should adopt it.

**Comment by typemytype** [comment]
by drawing it twice?

I don't know if I like that...

gr Frederik
www.typemytype.com

**Comment by justvanrossum** [comment]
It would be nice if there wasn't a bug in the OS, but there is. This method is not even unreasonable: internally it would otherwise draw it twice anyway.

**Comment by typemytype** [comment]
this should solve it: https://github.com/typemytype/drawbot/commit/8bf48474439c5bed776a5ce067e201e12f3b8f2f

will test this tomorrow on 10.11 and 10.12...

**Comment by frankrolf** [comment]
This is fixed.
