### ISSUE TITLE
Can't confirm email on DrawBot forum

### ISSUE THREAD

**Issue by joeisdead** [typemytype/drawbot#456]
I've tried registering an account with multiple email addresses, but I never receive a verification email.

I've checked my spam/junk folders but there's still nothing. Is there anywhere else I can post a query about some code?

**Comment by typemytype** [comment]
I validated your email manually, it seems like the forum gets lots of bots over, not only for coffee

**Comment by joeisdead** [comment]
Thanks! Although it's still saying my email is not confirmed yet. Did you verify joe********es@gmail.com?

**Comment by typemytype** [comment]
I only see your `@students.leeds-art.ac.uk` mail...

**Comment by joeisdead** [comment]
Sorry got it now! Managed to make a post :)

Kind Regards,
Joe Parker-Rees
