### ISSUE TITLE
Support for google colab?

### ISSUE THREAD

**Issue by rushic24** [typemytype/drawbot#468]
I'm trying to install drawbot using `!pip install git+https://github.com/typemytype/drawbot`,
but its stuck in installing since 20 mins in google colab. Is it possible to make it easier?

**Comment by typemytype** [comment]
couple of remarks:
* drawBot requires macOS
* does that environment support git? and has it installed git?

**Comment by rushic24** [comment]
Oh, colab is running Ubuntu Linux I guess. Git is preinstalled.

You can try it at https://colab.research.google.com/ for free if you have a google account.

**Comment by typemytype** [comment]
there is a DrawBot skia version, not with full support (yet)

see https://github.com/justvanrossum/drawbot-skia
