### ISSUE TITLE
AVFoundation

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#47]
if someone is in the right mood to convert the QTKit mov movie context to AVFoundation
see https://github.com/typemytype/drawbot/blob/master/drawBot/context/movContext.py

https://developer.apple.com/library/mac/technotes/tn2300/_index.html

**Comment by justvanrossum** [comment]
This would still be nice, but in the meantime we have `.mp4` export which is better and faster than the current `.mov` export.

**Comment by justvanrossum** [comment]
Here's a Swift example: https://gist.github.com/JaleelNazir/ce17ac24ec99636a230b3de8a98d7000

**Comment by justvanrossum** [comment]
But it seems to require CoreVideo, which is not included in PyObjC I think (can't find it).

**Comment by justvanrossum** [comment]
Oh, except that all those things are accessible via Quartz.

**Comment by typemytype** [comment]
closing in favor of the current ffmpeg implementation
