### ISSUE TITLE
Grey border around output on macOS 12.2 (drawbot 3.128)

### ISSUE THREAD

**Issue by rsms** [typemytype/drawbot#480]
There's a semi-transparent border added to all output. I don't recall this happening on macOS 10.15.

Example script:

```py
size(200, 200)
fill(1, 1, 0.8)
rect(0, 0, 200, 200)
saveImage("~/Downloads/out.pdf")
```

<img width="1222" alt="Screen Shot 2022-06-07 at 16 37 19" src="https://user-images.githubusercontent.com/47046/172501341-e1f980ed-825e-42d8-b082-6fcd1142ce9f.png">

- macOS: 12.2
- drawbot: 3.128

**Comment by rsms** [comment]
It doesn't appear on SVG or PNG output, so this is likely a PDF-specific bug
<img width="789" alt="Screen Shot 2022-06-07 at 16 44 43" src="https://user-images.githubusercontent.com/47046/172501670-9b59a84a-57eb-475f-9fc9-dafa466c8537.png">
<img width="941" alt="Screen Shot 2022-06-07 at 16 43 34" src="https://user-images.githubusercontent.com/47046/172501675-0e58ad0c-d2d1-471e-a4b4-c8ece25e28d7.png">

**Comment by typemytype** [comment]
Ive seen this too, its confusing... but its not in the pdf :(
open the pdf in any other app and you will not see that border.

(DrawBot and Preview use the same pdf view provided by macOS)

**Comment by rsms** [comment]
> open the pdf in any other app and you will not see that border

Woah, you're right. What a weird macOS bug.
Thanks!

**Comment by rsms** [comment]
And hey, thank you for making DrawBot! ♡
