### ISSUE TITLE
Bungee color font wrong metrics

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#481]
```python
size(350,250)
font ("BungeeColor-Regular")
s = 13
y = 10
for line in range (5):
    fontSize(s)
    text ("The quick brown fox", (10, y))
    s += 2
    y += 30
```

[Bungee Color font](https://github.com/djrrb/Bungee/releases/download/1.1.0/Bungee-fonts.zip)

<img width="380" alt="image" src="https://user-images.githubusercontent.com/1190358/184719115-e1acce09-2083-43fe-bc50-e6f35707d0a5.png">

**Comment by typemytype** [comment]
there is also something weird going on in text edit:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1190358/184720128-d32f78a2-9f2a-4b84-b5a1-cd13868e922e.png">

**Comment by djrrb** [comment]
Yikes! This font was produced with 2015-era color font technology and I think it is overdue for a rebuild. I’m sorry for the trouble with that. I don’t know exactly what’s going on but I agree this is probably a font issue and not a drawbot issue.

It seems like the SVG-in-OT font gets better results:

https://github.com/djrrb/Bungee/raw/master/fonts/Bungee_Color_Fonts/svg/BungeeColor-Regular_svg.ttf

<img width="249" alt="Screen Shot 2022-08-15 at 10 36 24 PM" src="https://user-images.githubusercontent.com/6578861/184786311-50ae7df7-fc22-4759-b82a-fdbc9961c8d1.png">

At this point I think the SBIX font can probably get removed. Thanks for letting me know about this!

**Comment by justvanrossum** [comment]
It's the "BungeeColor-Regular_sbix_MacOS.ttf" font that does the wobble. The CPAL/COLR ("Windows") and SVG fonts indeed work fine.

```python
size(350,250)

p = '/Users/just/Downloads/fonts/Bungee_Color_Fonts/BungeeColor-Regular_sbix_MacOS.ttf'

# p = '/Users/just/Downloads/fonts/Bungee_Color_Fonts/BungeeColor-Regular_svg.ttf'

# p = '/Users/just/Downloads/fonts/Bungee_Color_Fonts/BungeeColor-Regular_colr_Windows.ttf'

font(p)
s = 13
y = 10
for line in range (5):
    fontSize(s)
    text ("The quick brown fox", (10, y))
    s += 2
    y += 30
```

**Comment by justvanrossum** [comment]
> but I agree this is probably a font issue and not a drawbot issue

Could even be an OS issue: presumably it worked fine in 2015!
