### ISSUE TITLE
missing module »cmath«

### ISSUE THREAD

**Issue by READ** [typemytype/drawbot#498]
Hi all,
since the update to 3.129 (python3.10) it seems that the module »cmath« is missing.
When I'm using the pandas-tool (https://pandas.pydata.org) or just using `import cmath` an error Message pops up: »ModuleNotFoundError: No module named 'cmath'«

**Comment by typemytype** [comment]
mmm I see, it seems not be included into the app bundle

**Comment by justvanrossum** [comment]
Our `"cpython-%s%sm-darwin.so"` module pattern as used here:

https://github.com/typemytype/drawbot/blob/444c9d930e355c2deb1a99c53b7e70b4ba61638b/setupApp.py#L67

...seems to be no longer valid in 3.9. The `m` is gone. So presumably a lot of the stdlib is accidentally not bundled with the latest DrawBot.

**Comment by typemytype** [comment]
_mmmmmm_, not good

we should check if DB has to embed all those std lib modules, py2app does this now better then it used to embed those packages.

**Comment by justvanrossum** [comment]
How does py2app embed the stdlib?

**Comment by typemytype** [comment]
on my intel machine DrawBot is missing `encodings` (no local py3.9 installed)
