### ISSUE TITLE
ImportError: No module named...

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#5]
Dear Frederik,
I am trying to import some modules like csv or decimal, but Drawbot doesn't find them. Libraries installed with pip (like reportlab for example) or installed in the site-packages folder with the setup.py procedure work. 

I can import csv or decimal using Terminal, Nodebox1 or Robofont scripting panel.
Any suggestion?

Thanks
![schermata 2014-02-08 alle 22 52 40](https://f.cloud.github.com/assets/2218712/2118487/630bf862-910b-11e3-9bc5-b3b36dc36048.png)

**Comment by DRUOCM** [comment]
Hi, I'm having the same issue while trying to install PageBot.
Is there a way to add modules manually after the installation of Drawbot? A symlink somewhere or something?

**Comment by justvanrossum** [comment]
Modules installed under the OS version of Python 2.7 are visible within DrawBot, after a restart of the app.

(There is a known issue with numpy/scipy, though: see #100)
