### ISSUE TITLE
Module xmlWriter missing

### ISSUE THREAD

**Issue by MrBrezina** [typemytype/drawbot#50]
When using drawbot as a module (`import drawBot`) I got this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "drawBot/__init__.py", line 1, in <module>
    from drawBotDrawingTools import _drawBotDrawingTool
  File "drawBot/drawBotDrawingTools.py", line 9, in <module>
    from context import getContextForFileExt
  File "drawBot/context/__init__.py", line 4, in <module>
    from svgContext import SVGContext
  File "drawBot/context/svgContext.py", line 8, in <module>
    from xmlWriter import XMLWriter
ImportError: No module named xmlWriter
```

Where do I get the xmlWriter? It does not seem to be in PyPI or pre-installed with Python. I am using Python 2.7.10.

**Comment by typemytype** [comment]
As mentioned on twitter I guess you have an older version of fontTools. See https://github.com/behdad/fonttools/tree/master/Lib

When using drawbot as a module some external packages are required. `setupAsModule.py` does some test. I will add the xmlWriter dependency in the tests.

**Comment by typemytype** [comment]
Done in https://github.com/typemytype/drawbot/commit/0a30af2271ce3ce5d997028ed356717154f2ca7e

**Comment by MrBrezina** [comment]
Thank you. I had fontTools installed via homebrew. That version must be older than the current one on GH. Installing the most recent version fixed it.
