### ISSUE TITLE
a api callback to get the number of pages in a pdf

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#51]
proposals:
- numberOfPages(pathToPDF)
- pdfNumberOfPages(pathToPDF)
- imagePages(pathToPDF) ?? no

this is useful as `image(pathToPDF, (x, y), pageNumber=2)` is possible to draw a specific page from a multipage pdf.

**Comment by justvanrossum** [comment]
The concept should also apply to animated gifs, no?
My favorite then: `numberOfPages(pathToPDForGIF)`
Btw. `imageSize()` would also be affected.

**Comment by typemytype** [comment]
Should an specific frame be accessible? By page/frame number?

Yep imageSize should also get a pageNumber argument

On Monday, 23 May 2016, Just van Rossum <notifications@github.com> wrote:

> The concept should also apply to animated gifs, no?
> My favorite then: numberOfPages(pathToPDForGIF)
> Btw. imageSize() would also be affected.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/typemytype/drawbot/issues/51#issuecomment-220965926>
>


-- 
gr Frederik
www.typemytype.com

**Comment by justvanrossum** [comment]
I'm not saying a desperately need that feature, it just seems nicely symmetrical to me.

**Comment by typemytype** [comment]
`gifsicle` has an option to split gifs into framed 

See explode  https://www.lcdf.org/gifsicle/man.html

**Comment by typemytype** [comment]
could you check that latest commits?

https://github.com/typemytype/drawbot/commit/663e636a0fcf784d42f76500ec518b3bf4277076

what about .mov?

**Comment by typemytype** [comment]
I would rather remove .mov support or at least jumpt to AVFoundation to support it... and see from there if DrawBot could extract frames...

lets continue the mov AVFoundation thing here https://github.com/typemytype/drawbot/issues/47

and close this issue as page numbers support is been added
