### ISSUE TITLE
Upgrade notarization to use notarytool instead of altool

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#511]
For reference:
- https://github.com/googlefonts/fontra-pak/pull/7
- https://github.com/googlefonts/fontra-pak/blob/main/.github/workflows/python-app.yml
- https://github.com/googlefonts/fontra-pak/blob/main/macos/print_notarize_log.py

Important:
- team ID must be used: add as `NOTARIZE_TEAM_ID` repo secret
- No new app-specific password should be needed

**Comment by typemytype** [comment]
fixed in #513
