### ISSUE TITLE
`imageSize()` with svg images

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#517]
I can't get the correct width and height from a svg file with `imageSize()`. Even though the svg has a `viewBox` attribute with positive width and height, `imageSize()` returns `(0, 0)`

**Comment by justvanrossum** [comment]
Does image() support SVG to begin with?

**Comment by roberto-arista** [comment]
I was able to draw some svgs on a canvas, so I assume drawbot supports them

**Comment by justvanrossum** [comment]
Ah, it doesn't work on 10.15 for example. It's mostly an OS support thing.

That said the `imageSize()` implementation goes through some hoops to support PDF, (animated) GIF and "others". Maybe it needs some SVG handling code.

**Comment by typemytype** [comment]
A lots goes wrong while drawing svg as images... 

but we could get the size from the nsimage object, we just have to flag `_hasPixels  = True` with the ext `.svg` [here](https://github.com/typemytype/drawbot/blob/master/drawBot/drawBotDrawingTools.py#L1949-L1967)

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/1190358/222520344-c09845d2-bdc6-482d-83f6-cb82bbe31605.png">

**Comment by roberto-arista** [comment]
my workaround for now is this:
```python
import xml.etree.ElementTree as ET
tree = ET.parse(imagePath)
_, _, imageWidth, imageHeight = [float(i) for i in tree.getroot().attrib["viewBox"].split()]
```

**Comment by roberto-arista** [comment]
I understand that svg support as input format might be complicated and unreliable. I ended up converting the svg files in pdf with [cairosvg](https://cairosvg.org) and it worked fine. I'll open a pull request to add to the docs which formats are supported by the image proporties functions and the ImageObject.
