### ISSUE TITLE
Internal Links on PDFs generated with DrawBot behave differently on Preview+Safari compared to Acrobat Reader

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#535]
Hey all!

Steps to reproduce:
- take [this](https://www.drawbot.com/content/canvas/pages.html?highlight=linkDestination#drawBot.linkRect) example from the docs
- export it to PDF
- open it in both Preview and Acrobat Reader

Preview seems to get it wrong. Try the yellow and orange square. They both lead to the last page.
Instead on Acrobat Reader they lead to two different pages.

**Comment by justvanrossum** [comment]
Can you create such a document in another way, and demonstrate that both Preview and Reader get it right? This to exclude the possibility the bug is in Preview rather than with DrawBot.

**Comment by roberto-arista** [comment]
I'll try to make something with indesign tomorrow

**Comment by roberto-arista** [comment]
I've generated this document with InDesign.

[test_links.pdf](https://github.com/typemytype/drawbot/files/11966094/test_links.pdf)

The links behave in the same way both in Preview and InDesign. So I guess it's a DrawBot bug.

**Comment by typemytype** [comment]
if you change the script to make the destination points be more visible it makes more sense...

```python
# a variable with the amount of pages we want
totalPages = 10
# create the first page with a index
newPage()
# set a font size
fontSize(30)
# start a loop over all wanted pages 
for i in range(totalPages):
    # set a random fill color
    fill(i/(totalPages-1), .5, i/(totalPages-1))
    # draw a rectangle
    rect(10, 50 * i, 50, 50)
    fill(1)
    textBox(f"{i}", (10, 50 * i, 50, 50))
    # add a clickable link rectangle with a unique name
    linkRect(f"beginPage_{i}", (10, 10 + 50 * i, 50, 50))

# start a loop over all wanted pages
for i in range(totalPages):
    # create a new page
    newPage()
    fontSize(200)
    text(f"Page {i}", (30, 30))
    # add a link destination with a given name
    # the name must refer to a linkRect name
    oval(width()/2-10, height()/2-10, 20, 20)
    linkDestination(f"beginPage_{i}", (width()/2, height()/2))
```

**Comment by roberto-arista** [comment]
Apparently Preview does not get it wrong. When in continuous scroll mode (⌘1) the view jumps immediately after the `linkDestination` location. If in Single Page Mode (⌘2) it shows the correct one. So I think we can close the issue. Sorry for the trouble.

I'll take this opportunity to update the example script with what @typemytype posted here.
