### ISSUE TITLE
Text of Bezier Path sample code not working

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#54]
Hi! the text of the bezier path sample code (http://www.drawbot.com/content/shapes/bezierPath.html) is not working for me. The little triangles are drawn but the text no. Am I doing something wrong or maybe it's a bug?

Regards.

**Comment by typemytype** [comment]
I just improved the bezierPath.py example (https://github.com/typemytype/drawbot/commit/0d031bb1ecf66922a8387d6d30f9bc220f41dac6)

The text was added after drawing the path, so it was not visible. Ive added a second `drawPath` at the end of the script that draws the path, with the text.

good luck

**Comment by guidoferreyra** [comment]
Thanks!
