### ISSUE TITLE
Cursor disappears, adds interesting guessing element to editing

### ISSUE THREAD

**Issue by LettError** [typemytype/drawbot#55]
OSX Yosemite, 10.10.5 (14F1808), Version 3.82 (3.82)

Not sure if this is related, but this prints to console:
13/07/16 22:19:47,997 DrawBot[90918]: CGContextSetStrokeColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by typemytype** [comment]
Im aware of this issue
I guess its something in PyObjC

But DrawBot still works fine on the latest macOS Sierra beta...

**Comment by justvanrossum** [comment]
How does #45 behave on Sierra beta?

**Comment by typemytype** [comment]
Ive reported the cmd + number selection + drag 

 reported that they fixed something, and I had to test again, but I was not solved, same delay...



gr Frederik
www.typemytype.com

**Comment by justvanrossum** [comment]
Maybe click on #45 :)

**Comment by frankrolf** [comment]
This problem persists on 10.12, DrawBot Version 3.85

**Comment by justvanrossum** [comment]
This may be fixed in 10.13?

**Comment by typemytype** [comment]
was this solved with the vanilla patch?

**Comment by justvanrossum** [comment]
I thought that this was a very different issue. It also predates "my" cursor problem, so it's unrelated to the vanilla hack.

**Comment by justvanrossum** [comment]
Reading back, it sounds like a similar issue indeed. Reading back more, I'm not even sure I understand the issue. @LettError, did this issue just go away? Was it similar to #155?

The comments on this issue are so confusing an mixed up that I think we better just close it. Because this:

> Ive reported the cmd + number selection + drag

Was that even related to what Erik described here?
