### ISSUE TITLE
Arabic type settings mixed with Latin characters looks to be wrong

### ISSUE THREAD

**Issue by GaetanBaehr** [typemytype/drawbot#567]
In Drawbot if the Arabic text starts with a Latin word, the Latin word appears at the wrong place, here on the left, but it should be on the right.
<img width="1683" alt="image" src="https://github.com/typemytype/drawbot/assets/45567679/6f3c085b-f551-421b-8b34-c38e7d6e3e41">
In text edit at first it behave the same

<img width="800" alt="image" src="https://github.com/typemytype/drawbot/assets/45567679/1b3b186d-2290-4aae-9d30-ac18ad341278">
but if we change the writing direction to right to left, then the text is correct

<img width="1142" alt="image" src="https://github.com/typemytype/drawbot/assets/45567679/e8854625-e7b0-4777-84d5-f0f75987cc97">
As far as I know, in Drawbot looks to be impossible to change the writing direction.

**Comment by GaetanBaehr** [comment]
here the texte ` Grtsk میتوان در بسیاری `

**Comment by justvanrossum** [comment]
Yes, maybe we need a `writingDirection()` function or something like it. I'm not sure how this should work internally.

**Comment by typemytype** [comment]
CoreText has support we can wrap: https://developer.apple.com/documentation/coretext/ctwritingdirection?language=objc

**Comment by justvanrossum** [comment]
Can this be part of our `language()` function, or do you think it's better to add a new API function?

**Comment by typemytype** [comment]
well a `writingDirection(direction)` sound good and explicit... 

with `direction` options:
* `None` -> kCTWritingDirectionNatural (also the default)
* `"l2r"` -> kCTWritingDirectionLeftToRight
* `"r2l"` -> kCTWritingDirectionRightToLeft

It could possible be automated related to `language('ar')` but then we need to find out what the language direction is...

**Comment by typemytype** [comment]
https://github.com/typemytype/drawbot/pull/568

**Comment by MrBrezina** [comment]
@typemytype 

> It could possible be automated related to language('ar') but then we need to find out what the language direction is...

It is probably best not attempted as a single language can be written in two scripts with different directionality, e.g. Uzbek.

**Comment by typemytype** [comment]
true, @MrBrezina I prefer an explicit api, no magic guessing
