### ISSUE TITLE
listOpenTypeFeatures() on non-OpenType fonts

### ISSUE THREAD

**Issue by josh-hadley** [typemytype/drawbot#575]
I was surprised to find that `listOpenTypeFetures()` returns a non-empty list when called on Skia (which has AAT features, but no OpenType).

```
>>> db.font("Skia-Regular")
'Skia-Regular'
>>> db.listOpenTypeFeatures()
['dlig', 'frac', 'liga', 'lnum', 'onum', 'ordn', 'pnum', 'subs', 'sups', 'titl', 'tnum']
```

I guess these might be "converted" tags based on the AAT features, which is sensible. But I don't see any way to _activate_ these features through drawbot (that is: `openTypeFeatures(<feature>=True)` has no apparent effect). I imagine there's some way to do it through CoreText, but there doesn't seem to be anything exposed in drawbot for it.

**Comment by typemytype** [comment]
```python
font("Skia-Regular")
fontSize(50)

text("fi", (100, 100))

openTypeFeatures(liga=False)
text("fi", (100, 200))
```

The `liga` feature is on by default, so you can switch it off: 
<img width="560" alt="image" src="https://github.com/user-attachments/assets/99632d87-8b89-46c4-b4a8-36d903b8ebeb">

**Comment by frankrolf** [comment]
Thanks @typemytype ! :-)
The screenshot is quite confusing, with the output going from bottom to top :-)

@josh-hadley and i were talking about fractions yesterday, so I figured he was interested in the `frac` feature:

![Screenshot 2024-09-26 at 16 02 54](https://github.com/user-attachments/assets/4e711ed4-9df0-479b-b27f-877a0159500c)

I found out that Skia _does_ support fractions – but you’ll need to use U+2044 FRACTION SLASH to compose it (not `1/2`)

```
font("Skia-Regular")
fontSize(50)

openTypeFeatures(tnum=False)
text("abc123 (before)", (100, 200))
openTypeFeatures(tnum=True)
text("abc123 (after)", (100, 100))

openTypeFeatures(frac=False)
text("1⁄2 1/2 (before)", (500, 200))
openTypeFeatures(frac=True)
text("1⁄2 1/2 (after)", (500, 100))
```

**Comment by typemytype** [comment]
(the origin in DrawBot is bottom left)

I have no idea how the OT features are organised in Skia, you will have the same issue in Indesign or other layout applications.

**Comment by josh-hadley** [comment]
Ah OK thanks both! I guess I need to dig into the Skia AAT tables a bit more to see how the features are set up.
