### ISSUE TITLE
Freezing after longer operations

### ISSUE THREAD

**Issue by dyyybek** [typemytype/drawbot#60]
Sometimes when i run a script and it runs for about 20-30 seconds, the program freezes.
This is not happening every time i run it but i know that it's doing its job because i have my gif generated every time. It's just the drawbot that freezes.

Also is it possible to add something like a progress bar? The beachball is quite unsettling.

v3.84
OS 10.11.5

**Comment by dyyybek** [comment]
I decided to run the thing for 30 minutes.

Console is reporting:
`DrawBot[6088]: Core Image is now using the software OpenGL renderer. This will be slow.`

After 7 minutes my gif was generated.
Drawbot is still frozen though console is still reporting.
Memory usage is bloated to 10GB and steadily growing.

**Comment by typemytype** [comment]
Can you send me an example script?

Memory issues will occur when using giant page size with tons of frames.

**Comment by dyyybek** [comment]
https://we.tl/26CfpD0Nhd

Download's too big for github. I had to attach example files that i'm processing.

`line 62: for count in range(0, 40):`
if range is (0, 40) it will go "forever" but if you set it to (0, 2) it will finish.

**Comment by karstenw** [comment]
I just ran it in my own Drawbot fork https://github.com/karstenw/drawbot which is at version 3.78 on OSX 10.6.

It took 21 seconds and used 2.2GB RAM.

The freezing you observe is most likely the virtual memory cleaning up. If you observed 10G usage, page outs are very likely and Python is not good at that. I've waited up to 30 minutes for a script to clean it's act up that used more RAM than available.

**Comment by dyyybek** [comment]
So this is just a matter of available resources? Not an issue with my code? Is there a way to handle these troublesome operations better?

**Comment by karstenw** [comment]
You are putting 6 full sized images at 15% on each frame. That takes a toll.

Drawbot may not be the best vehicle for that task.

I'd try pure Python with Pillow to compose each frame and write it as an image to disk. A second script could use these and create an animation.

When you first posted it it I played a little with the script. It's not a solution to the problem but if I remember correctly the file reader is improved.

[drawbot_issue_#60_v3.py.zip](https://github.com/typemytype/drawbot/files/543164/drawbot_issue_.60_v3.py.zip)

**Comment by justvanrossum** [comment]
A better indication that DrawBot is actually still working rather than "frozen to death" would be cool. Also: a way to cancel a running script, but that is really tricky to do.

**Comment by typemytype** [comment]
cancel script is implement with a period command shortcut.

the usage of big assets will always be troublesome and eating out memory as DrawBot needs to build internally a PDF will all the pages/frames. 

Some users had success with writing each frame separately to disk and compile the gif or mp4 from there with: `from drawBot.context.toold.gifTools import generateGif` see https://github.com/typemytype/drawbot/blob/master/drawBot/context/tools/gifTools.py#L11

where you provide a list at image paths

good luck, I'm going to close this issue. please reopen of this is still an issue
