### ISSUE TITLE
Variable() buttons

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#62]
Hey! I love using the `Variable()` function for setting up quick UIs. I was wondering if it was possible to have a button in my `Variable()`-based UI that has a callback? I get a traceback for overwriting existing argument.

```
def doSomething(sender):
    print 'done'

Variable([
            dict(name='MyButton', ui="Button", 
            args=dict( 
                callback=doSomething,
                )
            )
        ],
        globals())
```

I get this traceback because the argument is already used:

```
TypeError: type object got multiple values for keyword argument 'callback'
```

I realize that because drawbot is constantly regenerating the canvas,  a button with a callback is functionally no different than a checkbox with an `if` statement. But UI-wise it makes more sense, and for some button-y things ("Generate UFO" for instance) where I don't necessarily require the canvas to be redrawn. 

As an aside, I was also going to try and see if I could implement a `Variable()` spin-off that only regenerates the canvas when an "OK" button is pressed. Or at that point do you think it is easier to build my own Vanilla UI, and somehow connect it to drawbot?

Thank you for whatever ideas you may have!

**Comment by typemytype** [comment]
This feels like a reversed drawBot :)

`Variable` is idd re-running the code with new values and the callback is used to trigger the re-run. 

I would recommend to build a small vanilla window and button
and you could also use all vanilla-like-views inside drawBot :)

```python
from random import random

import drawBot
import vanilla

class TestController(object):
    
    def __init__(self):
        self.w = vanilla.Window((200, 300))       
        self.w.b = vanilla.Button((10, 10, -10, 22), "Hit me", callback=self.hitMeCallback)
        self.w.c = drawBot.ui.drawView.DrawView((10, 40, -10, -10))
        self.w.open()
       
    def hitMeCallback(self, sender):
        drawBot.newDrawing()
        drawBot.newPage(400, 400)
        drawBot.fill(random(), random(), random())
        drawBot.rect(10, 10, 100, 100)
        pdf = drawBot.pdfImage()
        self.w.c.setPDFDocument(pdf)
       
TestController()
```

**Comment by djrrb** [comment]
You are the best! Thank you for showing me how it's done!

I hadn't fully thought it through, but yeah probably makes sense to do it
all in Vanilla. Thanks again, and case closed as far as I am concerned!

**Comment by djrrb** [comment]
I'm going to go ahead and close this. Thank you again!
