### ISSUE TITLE
textBox alignment with FormatttedString

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#63]
In this example, I would my FormattedString expect to be in the center, but it isn’t:

```
page_format = 'LetterLandscape'
newPage(page_format)
page_width, page_height = sizes()[page_format]

fs = FormattedString('Hello Beautiful')
textBox(fs, (0, 0, page_width, page_height), align='center')
```

I know you can center the string by using `align='center'` in the FormattedString itself, but I wonder why it shouldn’t work the other way around.

Slightly related – could there be an option for vertical centering in a Text Box?

**Comment by typemytype** [comment]
A FormattedString has his own alignment, as multiple alignments are possible inside a single FormattedString. 

> but I wonder why it shouldn’t work the other way around.

that would mean it has to loop through all the attributes of a FormattedString (NSAttributedString) to  check if there is an alignment set and add one if needed / overwrite it.

I like that a FormattedString is a closed thing where it just represents text with his attributes.

> Slightly related – could there be an option for vertical centering in a Text Box?

I recently added `textSize("myString", width=200)` where `width` is a constrain, it will calculate the `height` of the text with a given `width` (and vice versa for a `height` constrain)

This makes it possible to calculate the height of text and eventually center vertically text anywhere...
