### ISSUE TITLE
change BezierPath drawToPointPen and drawToPen to draw and drawPoints

### ISSUE THREAD

**Issue by typemytype** [typemytype/drawbot#66]
It should act more like a glyph/pen like object, so it can be easily interchanged with a glyph in other pen.

@justvanrossum ?

trying to use BooleanOperation on with BezierPath and it fails now

**Comment by typemytype** [comment]
or a BezierPath could have a `getPen` and `getPointsPen` returning pens to draw into the bezierPath object

**Comment by justvanrossum** [comment]
A pen != glyph. A BezierPath *is* a Pen, but yeah, it's not a glyph. I don't think a BezierPath should be a glyph, as it has no width, name, unicode, etc. Maybe it's a weakness in the BooleanOperator API instead?

**Comment by typemytype** [comment]
I know, just looking how to use already existing pen-ish modules with BezierPath objects...
and in some cases it usefull not to have `drawToPen` but have `draw` instead (same for `drawToPointsPen` --> `drawPoints`

**Comment by justvanrossum** [comment]
Why should it have a `draw()` method? That makes it more glyph-like, which it shouldn't necessarily be. On the one hand it may be a nice symmetry (`draw()` and `drawPoints()`), on the other hand I proposed the `drawToPen()` name to avoid possible confusion with drawPath(p).

**Comment by justvanrossum** [comment]
Can we define path operators on the BezierPath itself, and apply some magic internally so it works with BooleanOperations?

**Comment by typemytype** [comment]
why: a bezierPath can be a middle part by being a pen where something can draw in, hold data and being able to draw the data into something else, lets keep it for now like it is

> Can we define path operators on the BezierPath itself, and apply some magic internally so it works with BooleanOperations?

this could work for BO and be handy to have union, difference, intersection and xor on a bezierPath.

**Comment by justvanrossum** [comment]
I understand why this stuff is useful, and I would love to have it, I'm asking why does BezierPath() need to have draw() and drawPoints() methods. Or rather: why does BooleanOperations require them? Shouldn't BO have a "pure-pen" input? If all it does is call x.draw() on it's input then that's a little weak.

**Comment by typemytype** [comment]
BooleanOperations needs objects that have a drawPoints method to extract data from and it draws back into a point pen.

I've implemented BO directly in a bezierPath with some 'magic' :)
see https://github.com/typemytype/drawbot/commit/94433aeba6217d12e060aaf31d9dd8061080790d
