### ISSUE TITLE
Docs failed to build in last update

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#67]
FYI, for example http://www.drawbot.com/content/text/formattedString.html

**Comment by typemytype** [comment]
forgot to mock some packages...

thanks for notifying 

https://github.com/typemytype/drawbot/commit/742e36f266919033158359f3b6518776b376c603
https://github.com/typemytype/drawbot/commit/0fed2533a39f6382dd6ed666565abf240b28296e
