### ISSUE TITLE
openTypeFeatures() leaking to other script

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#72]
Run this first:
```
font("Hoefler Text")
fontSize(100)
openTypeFeatures(lnum=True)
text("Abcde 0123", (50, 100))
```

Then run this in a second window:
```
font("Hoefler Text")
fontSize(100)
text("Abcde 0123", (50, 100))
```

The second window shows the OT features set in the first script (lining figures) instead of the default (old style).

**Comment by typemytype** [comment]
solved in https://github.com/typemytype/drawbot/commit/906c593a3ee554f6a8795603a3efa848f17d3512
