### ISSUE TITLE
Calling multiple font() via path will not work with identical name tables 

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#73]
I am using a drawbot script that compares two fonts:

```
paths = [u"/path/to/myFont1.ttf", u"/path/to/myFont2.ttf"]
for fontName in paths:
    font(fontName, 100)
    text('HELLO', (20, 20))
    translate(0, 100)
```

I expect each line to appear in a different font, but what happens is that all lines appear the same way, set in one of the fonts in the list (not always the same one).

These two fonts have outline differences, but have identical name tables. Sure enough, if I change the name table in one of the fonts, they both appear as expected.

The reason I want to call fonts via their path is so I can avoid name table conflicts that come from installing. Is it possible for `font()` to handle multiple fonts that share the same postscript name and other font info. Thanks so much!

**Comment by justvanrossum** [comment]
The fonts still get (temporarily) installed, and all font rendering then proceeds as usual, so conflicts like this are not easy to avoid, I'm afraid.

Suggestion: write a fontTools script that makes a temporary copy with a hacked name table (maybe the ps name is enough).

**Comment by djrrb** [comment]
Thanks for letting me know! Yes, changing nameID=6 seems to do it!
