### ISSUE TITLE
tracking(0) somehow disables kerning

### ISSUE THREAD

**Issue by justvanrossum** [typemytype/drawbot#74]
When explicitly setting tracking to 0, kerning doesn't show anymore. It does work for other values.

```python
size(500, 500)
font("Arial")
fontSize(100)
text("ToTAVA", (50, 50)) # yes kerning
tracking(0)
text("ToTAVA", (50, 150))  # no kerning
tracking(0.001)
text("ToTAVA", (50, 250)) # yes kerning
```

**Comment by justvanrossum** [comment]
Just in case this is an OS bug: this is on 10.10.2

**Comment by typemytype** [comment]
From what I remember setting tracking or NSKernAttributeName will always disable the  kerning retrieved from a font. Have to test...

**Comment by justvanrossum** [comment]
That's not the case on my end. I see kerning at all settings for tracking except 0.

**Comment by justvanrossum** [comment]
```python
size(500, 500)
font("Arial")
fontSize(100)
text("ToTAVA", (50, 50)) # yes kerning
tracking(0)
text("ToTAVA", (50, 150))  # no kerning
tracking(3)
text("ToTAVA", (50, 250)) # yes kerning
print "tracking +3:", textSize("ToTAVA")[0]
tracking(0)
print "tracking 0:", textSize("ToTAVA")[0]
```

```
tracking +3: 362.53125
tracking 0: 377.880859375
```

**Comment by typemytype** [comment]
I see.

the spec https://developer.apple.com/reference/appkit/nskernattributename

```
 The value 0 means kerning is disabled.
```
It should never set value 0 to prevent to switch off font kerning

**Comment by justvanrossum** [comment]
It also says the default for this value is 0, which is weird, because it behaves differently when actually set to 0 :) Oh well. Thanks for merging my PR!

**Comment by justvanrossum** [comment]
The API designer clearly didn't fully grasp the distinction between kerning and tracking.

**Comment by typemytype** [comment]
nope

but a wild guess: if you get the attributes of an attributed string in between a kerning pair, maybe, maybe, maybe, perhaps, perhaps that value pops up in the `NSKernAttributeName` key
