### ISSUE TITLE
access canvas attributes

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#76]
Dear Frederik,
few weeks ago I started using Drawbot for teaching programming basics in a bachelor course. Yesterday I introduced matrix transformations. I wonder whether it is possible to access the actual status of the canvas (transformation, color, selected font)?
That would be rather helpful for debugging (especially code written by someone else).

Something like:
```python
print self.drawBot.state
```
which delivers
```python

{'fill':  (0,0,1),
'stroke': (1,0,0),
'fontName': 'Verdana',
'transformation matrix': (xx, xy, yx, yy, x, y)}
```

What do you think?
Thanks

**Comment by typemytype** [comment]
I like the option `drawBot.debug` that returns the full stack of current attributes with all the default values.

This would not be able to set or change a value.

@justvanrossum an other ideas or objections

**Comment by justvanrossum** [comment]
`debug` sounds rather generic. Maybe `graphicsStateDebug()`?

**Comment by roberto-arista** [comment]
🍊🌻😂🐙🌋🍩✈️📛📌💈
(just a few random emojis in order to not let this proposal fall into oblivion)

**Comment by justvanrossum** [comment]
I think a save() / restore() context manager (`with` statement) makes things a lot easier to deal with. See #140. I personally don't see much use for such a debug function.
