### ISSUE TITLE
Expose GIF options

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#78]
It would be great to have access to the dithering options here:
https://www.lcdf.org/gifsicle/man.html
Also, it would be cool if anti-aliasing would be possible.
A GIF with a b/w illustration (for instance, a filled glyph) is 1-bit and looks quite jaggy.

See here:
![comparison_eighthnote](https://cloud.githubusercontent.com/assets/2049645/21333362/0ef27a22-c604-11e6-9853-0c7744f44481.gif)

**Comment by justvanrossum** [comment]
By default, a GIFs background is transparent, and because GIF only knows 1 bit transparency, anti-aliasing doesn't work properly in that case. Draw a white background and it will look a lot better.

**Comment by frankrolf** [comment]
Thanks for the suggestion @justvanrossum! Looks much better indeed:
![eighthnote](https://cloud.githubusercontent.com/assets/2049645/21341060/528b9026-c63f-11e6-9067-d7cf4a78dd0a.gif)
Since my problem was mostly about a limitation of the GIF format, I will close this issue. Still, I think the access to gifsicle’s options would be great.
