### ISSUE TITLE
textBox text size

### ISSUE THREAD

**Issue by typoman** [typemytype/drawbot#79]
I started to use formatted string to create a dynamic document and used textBox in order to handle the page margins. Right now if the text overflows the textBox I want to make a newPage but I don't want the textBox to draw anything if it overflows. I can't get to use the size() method on the formatted string to predict overflowing either because the textBox is working differently. So I thought there could be couple of solutions:

1. textBox could be added to bezierPath as a method. Then it possible to check its bounding size.
2. textBox could have an argument that prevents it from drawing (Like dontDraw == True?) Then it's possible to check if it overflows without it being drawn.
3. If it was possible to access the NSBezierPath of textBox also one could check the bounding box.

**Comment by justvanrossum** [comment]
There is the newish `textOverflow()` function that is exactly like `textBox()` except it doesn't draw.

**Comment by typoman** [comment]
I actually realized that this helps a lot to fix one issue (sorry I couldn't find any documentation about it before). But still a method to calculate textBox size or bounding box would be necessary in a situation where one wants to find out where was the last line of text, right?

**Comment by justvanrossum** [comment]
I think @typemytype was working on something like that. I'm not sure about the status.

**Comment by typemytype** [comment]
this is being added to `textSize` 
there is an option to provide both width or height constrains

see http://www.drawbot.com/content/text/drawingText.html#drawBot.textSize

**Comment by typemytype** [comment]
@typoman is this resolved?
