### ISSUE TITLE
traceImage mkbitmap potrace No such file or directory

### ISSUE THREAD

**Issue by MBurvill** [typemytype/drawbot#80]
Version 3.89 (3.89)

When attempting to trace an image, I get this error. I tracked down the binaries _mkbitmap_ and _potrace_ from the package contents of DrawBot, and copied them to the location of my script, and this worked. But I don't think it's convenient to have to copy the binaries to the location of any script that uses the traceImage method. Is this the expected behaviour? What can we do to fix it?

> ('/bin/sh: /Users/username/Google Drive/mkbitmap: No such file or directory\n', '')
> ('/bin/sh: /Users/username/Google Drive/potrace: No such file or directory\n', '')
> Traceback (most recent call last):
>   File "myscript.py", line 12, in <module>
>   File "drawBot/context/baseContext.pyc", line 272, in traceImage
>   File "drawBot/context/tools/traceImage.pyc", line 337, in TraceImage
>   File "drawBot/context/tools/traceImage.pyc", line 213, in importSVGWithPen
>   File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
>   File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/xml/dom/expatbuilder.py", line 922, in parse
> IOError: [Errno 2] No such file or directory: '/var/folders/dn/7ws86nq52rn6dfk0tyy30vdm0000gn/T/tmpkpFVad.svg'

**Comment by typemytype** [comment]
this should be solved here: https://github.com/typemytype/drawbot/commit/39258d77379d8065852b11281e6fe41381b0dca2

please test version 3.90 and close this issue when resolved

thanks!
