### ISSUE TITLE
Performance issues in loading drawBot as a module

### ISSUE THREAD

**Issue by yanone** [typemytype/drawbot#82]
I’m having trouble using drawBot as a module (v3.9): It takes around 11 seconds to load.
I’ve traced it down to this call in `drawBotDrawingTools.py`: `from context import getContextForFileExt` which alone takes around 10 seconds, but I stopped investigating there. I wonder whether all the contexts need to be loaded or whether they could be loaded dynamically only once they are needed.
My machine is very old (2009 MBP) but I will not get another one any time soon.

**Comment by justvanrossum** [comment]
I just commited a fix: https://github.com/typemytype/drawbot/commit/30e46273c49d9270cd00623a472c035d472629f0

Can you see how much that improves it on your end? The culprit is in importing vanilla, that just takes a loong time.

**Comment by anthrotype** [comment]
> The culprit is in importing vanilla, that just takes a loong time

I also encountered this issue for other projects using vanilla.
Do you know why that's the case?

**Comment by justvanrossum** [comment]
No, we'd have to investigate. But for one: vanilla/__init__.py loads a LOT of stuff. I have no time right now, but it would be nice to find out if there's anything specific that causes it. It may not even be the importing itself, but something like connecting to the window server.

**Comment by yanone** [comment]
Your latest commit reduced the loading time for me (PDF writing from the command line) from ca. 11s to less than 1s.
Thank you.
