### ISSUE TITLE
Modules missing in DrawBot 3.90

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#84]
```import colorsys```

→ ```Traceback (most recent call last):
  File "combining.py", line 5, in <module>
ImportError: No module named colorsys```

**Comment by typemytype** [comment]
must `colorsys` be embedded?

**Comment by justvanrossum** [comment]
It was before, I've used it and have show it to students. It's limited but still pretty useful.

**Comment by typemytype** [comment]
not all standard libraries are embedded, that would make the build huge.

the latest build has all font related packages switched to UFO3 (this is my mistake or forgetfulness)
and somewhere on the road `colorsys` is needed by a package and is not required anymore in the UFO3 version...

DrawBot includes the site packages of the default python see https://github.com/typemytype/drawbot/blob/master/drawBot/scriptTools.py#L77-L103

and simple enough this should work:

`get_python_lib(standard_lib=True)`

to retrieve the standard lib path :)
I will add this to `sys.path`

**Comment by justvanrossum** [comment]
And then the build could become smaller, as *nothing* of the std lib would have to be embedded.

**Comment by typemytype** [comment]
:1st_place_medal:

**Comment by frankrolf** [comment]
I just happened to use `colorsys` in the first script I ran. I think it’s quite useful and would love to have it back. (Also, is it possible to make a version history available on drawbot.org? Of course I overwrote the old version of the app with the new one).

**Comment by typemytype** [comment]
this should be solved here: https://github.com/typemytype/drawbot/commit/23ca7e4f3c84a8c4a0654e145f0bf95513e0adce
with a date stamp: https://github.com/typemytype/drawbot/commit/96fa2aaa98e23c94f700045606ed8002f8623b80

and from now on a dated copy will be saved on https://github.com/typemytype/drawbot/commit/e2c55f6727f9b8bdc6aa3b012239e1032901a76f

**Comment by typemytype** [comment]
first one already in version history :)

**Comment by frankrolf** [comment]
The DMGs downloaded from the version history page are all 0kB, which is a bit too small in my opinion.

**Comment by typemytype** [comment]
should be fixed here https://github.com/typemytype/drawbot/commit/d017689c9af6b0c7ffb7807226fe56a134b2967b
