### ISSUE TITLE
[wish] Add awareness of code changes on disk

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#85]
Robofont has this – when a Python file is changed on disk, the app recognizes that & reloads the file.
DrawBot doesn’t have it, but it would be so useful. Sometimes I just like to move my code to another editor, it would be cool to not have to reopen the file.

Along those lines, it would be cool to add an option to the preferences:
“Don’t open empty file when starting the application”

**Comment by typemytype** [comment]
wish one https://github.com/typemytype/drawbot/commit/007fba6d96c3368cc3bcb56611f3fd8bb994eded

wish two https://github.com/typemytype/drawbot/commit/62ba0515f107d6bd906c6d09d2e802b492a697d6

its your lucky day!

**Comment by frankrolf** [comment]
Wow! #blessed 🙌

**Comment by justvanrossum** [comment]
Wish one: it doesn't work (for me) in the following scenario:
- create a new doc in DB
- edit some stiff, save
- open in other editor, make changes, save
- go back to DB: external changes are not loaded

**Comment by justvanrossum** [comment]
It only doesn't work after the initial save of a fresh untitled document, if you save one more time (even without changes) it does work.

**Comment by typemytype** [comment]
seems like the document is setting the fileURL after writing it, fix it soon!

**Comment by typemytype** [comment]
should be fixed here https://github.com/typemytype/drawbot/commit/668148a62d80bd7735b7a40b69db265c8aa77423

**Comment by justvanrossum** [comment]
That works. Next problem:

- edit in DB, save
- edit more, but *don't* save
- save in external editor, save
- switch back to DB: unsaved edits are gone without any warning

**Comment by typemytype** [comment]
mmm, a pop up should appear
<img width="438" alt="screen shot 2017-01-13 at 14 01 53" src="https://cloud.githubusercontent.com/assets/1190358/21930926/e9a0da54-d998-11e6-8d17-dd6aa37fc209.png">

**Comment by typemytype** [comment]
seems like the editor doest set the document.updateChangeCount after a save...

**Comment by justvanrossum** [comment]
Hm, yes, that seems to be the case.

**Comment by typemytype** [comment]
this should do it: https://github.com/typemytype/drawbot/commit/5caa230b0d2d241cfb4e834037c4cac54c3fe027
pff
