### ISSUE TITLE
[wish] please add the ability to add rounded courners to (custom) shapes

### ISSUE THREAD

**Issue by bramfritz** [typemytype/drawbot#86]
i expect it would work something like this:
https://processing.org/reference/rect_.html
but it would be great to also apply this system on custom shapes.

**Comment by typemytype** [comment]
that is idd super handy, Ive added an example here https://github.com/typemytype/drawbot/blob/master/examples/roundedRect.py

but I guess this will be threaded similarly as the star example. It will be there in the examples but not embedded.
