### ISSUE TITLE
[wish] Add a way go back to previously drawn pages

### ISSUE THREAD

**Issue by mathieureguer** [typemytype/drawbot#87]
It would be great to be able go back to a previous page and do some drawing there.
Something like:
```python 
setCurrentPage(pageIndex)
rect(0, 0, 100, 100)
```

**Comment by typemytype** [comment]
It would be more like how drawing in images works: http://www.drawbot.com/content/image/imageObject.html

Proposal:

`pages()`

Returns a list of all pages

`page = paged(index)`

Return a specif page

```
with page:
     rect(10, 10, 100, 100)
```

Draw into a page with the with statement

**Comment by mathieureguer** [comment]
That sounds great and super clean!
I did not realize the imageObject was so close to a page in a page already.

**Comment by typemytype** [comment]
see https://github.com/typemytype/drawbot/commit/ff7531610a8723621187499a299c5a8e72344944
and https://github.com/typemytype/drawbot/commit/9554f9e0f067df433c0069a71854ab7ae407c9c0

**Comment by mathieureguer** [comment]
😍
