### ISSUE TITLE
DNS error for http://drawbot.com/

### ISSUE THREAD

**Issue by gferreira** [typemytype/drawbot#90]
✘ http://drawbot.com/ → “server DNS could not be found”
✔︎ http://www.drawbot.com/ works fine

cc @LettError

**Comment by typemytype** [comment]
solved

**Comment by LettError** [comment]
Solved? How?

**Comment by typemytype** [comment]
not sovled, I typed the url instead of clicked...

this is a Gandi setting..

**Comment by typemytype** [comment]
this should be solved!!!

please all try and report

**Comment by gferreira** [comment]
working fine here. thanks!!

**Comment by LettError** [comment]
solved.
