### ISSUE TITLE
ImageObject always drawn as pixel based image

### ISSUE THREAD

**Issue by mathieureguer** [typemytype/drawbot#92]
`ImageObject` seems to produce only pixel renders when drawn on a page, even when the page is saved as a pdf.
http://www.drawbot.com/_downloads/imageObject.py will output low res pixelated text rather than outlines. I can't remember if that was always the case, but it would be awesome if it could be drawn as actual outlines.
Could this be because `ImageObject` have no path and drawbot uses file extensions to figure out how to draw an image?

**Comment by typemytype** [comment]
Yeah an ImageObject will be always be pixel based.

Ive commit `pages` support see https://github.com/typemytype/drawbot/commit/ff7531610a8723621187499a299c5a8e72344944
but did not pushed a new download yet...
