### ISSUE TITLE
Memory leak when creating GIF animations

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#93]
I noticed Drawbot is prone to memory leaks when creating a large GIF file (I am using drawbot as a Python module). This doesn’t seem to happen when creating a movie.

![screen shot 2017-02-02 at 13 23 34](https://cloud.githubusercontent.com/assets/2049645/22573268/fb192f24-e95c-11e6-8125-fcf5f523e708.png)
I was trying to create a GIF with 6752 frames (sorry). At this point, Python was using 32 GB of memory.

**Comment by typemytype** [comment]
euh that is possible.

The pdf is build in memory, so large pdfs will require a lot of memory...
Maybe there should be an option to write pdfs in chunks and merge them later.

**Comment by justvanrossum** [comment]
But that doesn't explain the difference in memory behavior between GIF and MOV.

**Comment by typemytype** [comment]
gifs are build by an external tool gifsicle, that requires a list of images on disk, this clears already some memory.

movs are build internally with cocoa, and I guess this just doubles memory usage...

**Comment by justvanrossum** [comment]
But the report says that generating GIF leaks, and generating MOV doesn't. It could be that it's leaking when run as a module because of the lack of an event loop, and that autoreleased objects are not released.

**Comment by frankrolf** [comment]
FWIW I found the same to be true when generating many PNG images.

**Comment by LettError** [comment]
Maybe related: generating around 70 jpegs at 4K resolution causes memory problems too. In a script I write each page from an external pdf to a jpg. Drawbot only has a single drawing open at any time. But something leaks.

**Comment by justvanrossum** [comment]
Maybe https://github.com/typemytype/drawbot/commit/b42f7dd82a4fcba89af9f3efee1fb4924e047220 fixes it. Erik, can you build & from source?

**Comment by LettError** [comment]
trying, hang on.

**Comment by LettError** [comment]
I have not compiled from source in.. a while it seems. Need to install wx, jedi

**Comment by justvanrossum** [comment]
Thanks for confirming. Pretty sure it solves the original issue (big/long gifs), too.
