### ISSUE TITLE
GIF & frameDuration

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#94]
Take with a grain of salt:
When building an animated GIF, the `frameDuration` setting does not seem to have a lot of influence. Anything beyond 30FPS is not reflected in the GIF. I tried to find out if there is some kind of limitation in the file format, but I cannot trust anything after reading this:
http://nullsleep.tumblr.com/post/16524517190/animated-gif-minimum-frame-delay-browser

I’d accept any answer for this, just wanted to point it out.

**Comment by justvanrossum** [comment]
Two things are going on:
- it depends a lot on the viewer it seems.
- the precision of the GIF delay value is quite limited.

The GIF format stores the frame delays as 1/100th of a second, so framerates over 100 are not possible anyway, and the precision is very limited. DB does `int(frameDuration * 100)` to calculate the GIF frame delay, and that means that (for example) in a range of frame durations from 1/26th to 1/33rd of a second there will be no difference in GIF frame delay (all rounds down to 3 hundredth of a second).

From http://www.w3.org/Graphics/GIF/spec-gif89a.txt:
```
vii) Delay Time - If not 0, this field specifies the number of
hundredths (1/100) of a second to wait before continuing with the
processing of the Data Stream. The clock starts ticking immediately
after the graphic is rendered. This field may be used in
conjunction with the User Input Flag field.
```
