### ISSUE TITLE
Incorrect color rendering on external display

### ISSUE THREAD

**Issue by rileycran** [typemytype/drawbot#95]
Color rendering with transparency is incorrect on my external display. 

Interestingly, a screenshot will accurately reflect the incorrect rendering.

The simple code:

```
fill(1,0,0,0.3)

rect(100,100,100,100)
```

Renders like this on my Macbook pro Retina display:
<img width="207" alt="screen shot 2017-02-27 at 12 24 17 pm" src="https://cloud.githubusercontent.com/assets/7476499/23378624/9dac8b52-fce8-11e6-9689-412d292c0975.png">

And like this on my external Samsung S23B300:

![screen shot 2017-02-27 at 12 24 13 pm](https://cloud.githubusercontent.com/assets/7476499/23378287/bf5bbc10-fce7-11e6-88f2-d0c091652781.png)

Moving the window between the two displays shows the bug consistently, and using a transparency value of '1' in the code above renders the color correctly on both screens. 

Per @ninastoessinger's suggestion, I tried setting a color space, but this did not resolve the issue.

**Comment by typemytype** [comment]
and this happens in both the DrawBot app as in the DrawBot extension?

Nevertheless this is weird :)

What system are you on?
What happens if you generate a pdf and check it in Preview.app?

**Comment by rileycran** [comment]
Yes, it occurs in both the app and the extension. 

I'm on 10.11.15 (a fair bit behind in updates).

Saving PDFs results in the colors being rendered correctly on both displays.

**Comment by typemytype** [comment]
is this still an issue?

I dont have such a monitor to test.... so I cannot reproduce this

**Comment by rileycran** [comment]
This issue does appear to be mostly resolved in 3.97, but running the same code multiple times, and moving the window between multiple monitors, causes the color to be rendered slightly differently on each 'run'. 

![screen shot 2017-10-27 at 11 52 45 am](https://user-images.githubusercontent.com/7476499/32120431-5f9f13dc-bb0d-11e7-81a3-be59d70082ba.png)
 
Running the same simple code from above, I was able to produce all three of these colors by:

1) Moving the drawbot window to the external monitor, running the code.

2) Moving back to the Macbook pro retina screen, and running the code 3 times, taking a screenshot on each iteration to capture the color.

Looks like the OS is confusing drawbot's color rendering in some way, based on monitor profile?

**Comment by justvanrossum** [comment]
I've only ever seen this happen on MacOS 10.11. I'm convinced it's an OS bug that we can't work around, apart from suggesting "upgrade your OS".
