### ISSUE TITLE
how to handle imports in Drawbot

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/drawbot#96]
Hi Frederik,
I have a myMainScript.py with the following code:
`from mySharedFunctions import drawCircle`
`drawCircle(0, 0, 100, 100)`

and a mySharedFunctions.py with the following code
`def drawCircle(x, y, width, height): 
    oval(x, y, width, height)`

when I run myMainScript.py I get the following error
`Traceback (most recent call last):
  File "myMainScript.py", line 3, in <module>
  File "/Users/robertoarista/Desktop/test import drawbot/mySharedFunctions.py", line 3, in drawCircle
NameError: global name 'oval' is not defined`

how do I import oval in the mySharedFunctions.py script?
Should I install drawbot as a module?

Thanks

**Comment by justvanrossum** [comment]
No, you can just do `from drawBot import *` at the top of your module.

**Comment by roberto-arista** [comment]
🙌🙌🙌🙌
