### ISSUE TITLE
Get translate info.

### ISSUE THREAD

**Issue by guidoferreyra** [typemytype/drawbot#98]
I think it could be great if there was a function that would return how much the canvas has been translated.
For instance, It would be useful for return to zero point like a typewriter.

Regards.

**Comment by justvanrossum** [comment]
`save()` and `restore()` to the rescue.

**Comment by guidoferreyra** [comment]
Yes this is what I use when I want to return to zero but sometimes (I can’t remember now a specific case) I wanted to operate with the translated number and sometimes it could be complex (for me ha) the use of save() and restore().

**Comment by andyclymer** [comment]
The `restore()` doesn't jump back to the start, it just restores back to the previous `save()`. You can then use as many `save()` and `restore()` states as you need which might make it easier to keep track of when you just want to jump back one step:

```
save()
translate(0, 800) # move to the start of the column
save() # save the state *again*
translate(10, 0) # indent by 10 units
# do something
restore() # restore back to the start of the column before the indent
# do something else
restore() # restore back to the origin
```

**Comment by frankrolf** [comment]
Random idea: Would it be possible to flag a specific `save`, in order to quickly `restore` to that state?
Something like `save('foo')` ……… `restore('foo')`

**Comment by typemytype** [comment]
mmm, no `save` <-> `restore` are simple instructions that does not need additional complexity.

I rather would like to add something that you can `get` the current state, store in a variable and then `set` it back when ever you want. 

That would solve two issues :) 
this one and https://github.com/typemytype/drawbot/issues/76
where the return value could be checked (and maybe adjusted)

**Comment by justvanrossum** [comment]
I'm very much in favor of letting things be what they are and not add any get or set. The principle is very simple and clean. It's a stack, and you just have to make sure you bracket changes you want to undo with save/restore. Keep them relatively close together. Make sure functions that change things are bracketed with save/restore. The fact you keep asking for these things suggests you're not using them the right way.

But perhaps we can consider some syntactic sugar:

```python
with temporaryGraphicsSate():  # a better name would be needed...
    translate(x, y)
    rotate(10)
    drawStuff(.....)
```

This would be equivalent to:

```python
save()
translate(x, y)
rotate(10)
drawStuff(.....)
restore()
```

That may make it somewhat easier to keep the save/restore calls balanced. But I'm not convinced of this, either.
