### ISSUE TITLE
Append a glyph by name to a FormattedString?

### ISSUE THREAD

**Issue by andyclymer** [typemytype/drawbot#99]
Occasionally it could be useful to append a glyph to a FormattedString by name. I've been hacking around with this but can't seem to get it to work, but could it be possible?

I'm able to get a glyph's index out of a NSFont object by using the glyph's name, but I can't seem to find a way to add that to a string. I know that in other places with C the integer of the glyph index is just as good as the character, but maybe that's not the case with ObjC.

Any thoughts on whether or not this might be possible?

**Comment by typemytype** [comment]
See http://www.drawbot.com/content/text/formattedString.html#drawBot.context.baseContext.FormattedString.appendGlyph

Should work ;)

**Comment by andyclymer** [comment]
😳 Thank you!
